// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use implexity_ad::{Dual,Scalar};
use implexity_core::{CaeError,CaeResult};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
fn sub<S:Scalar>(a:[S;3],b:[S;3])->[S;3]{std::array::from_fn(|i|a[i]-b[i])}
fn dot<S:Scalar>(a:[S;3],b:[S;3])->S{a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}
fn cross<S:Scalar>(a:[S;3],b:[S;3])->[S;3]{[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}
#[derive(Clone,Debug)]pub enum SelectedBoundaryStratum{VertexFace{barycentric:[f64;3]},EdgeEdge{parameters:[f64;2]}}
#[derive(Clone,Debug)]pub struct InstantaneousGeometry{pub signed_gap_m:f64,pub gradient:[[f64;3];4],pub gap_direction_m:f64,pub gradient_direction:[[f64;3];4],pub selected:SelectedBoundaryStratum}
impl InstantaneousGeometry{pub fn require_ordinary_feature_derivative(&self,minimum_parameter:f64)->CaeResult<()>{if !minimum_parameter.is_finite()||minimum_parameter<=0.||minimum_parameter>=1./3.{return Err(fail("strict feature derivative margin"));}let strict=match self.selected{SelectedBoundaryStratum::VertexFace{barycentric}=>barycentric.iter().all(|x|*x>minimum_parameter),SelectedBoundaryStratum::EdgeEdge{parameters}=>parameters.iter().all(|x|*x>minimum_parameter&&*x<1.-minimum_parameter)};if !strict{return Err(fail("feature-boundary tie has no admitted ordinary derivative"));}Ok(())}}
pub(crate) fn vf<S:Scalar>(p:[[S;3];4],minimum_area_ratio:f64)->CaeResult<(S,[[S;3];4],[S;3])>{
 let [point,a,b,c]=p;let u=sub(b,a);let v=sub(c,a);let w=sub(point,a);let scale=u.iter().chain(&v).map(|x|x.value().abs()).fold(0.,f64::max);if !scale.is_finite()||scale<=0.{return Err(fail("boundary face edge scale"));}let factor=S::from_f64(scale);let us=u.map(|x|x/factor);let vs=v.map(|x|x/factor);let ws=w.map(|x|x/factor);let n=cross(us,vs);let n2=dot(n,n);if n2.value()<=minimum_area_ratio*minimum_area_ratio||!n2.value().is_finite(){return Err(fail("boundary face area"));}let normal=n.map(|x|x/n2.sqrt());let beta=dot(cross(ws,vs),n)/n2;let gamma=dot(cross(us,ws),n)/n2;let bary=[S::from_f64(1.)-beta-gamma,beta,gamma];if bary.iter().any(|x|!x.value().is_finite()||x.value()<0.){return Err(fail("selected face closed barycentric domain"));}let g=dot(w,normal);let gradient=std::array::from_fn(|k|if k==0{normal}else{normal.map(|x|-bary[k-1]*x)});Ok((g,gradient,bary))
}
pub(crate) fn ee<S:Scalar>(p:[[S;3];4],orientation:f64,minimum_area_ratio:f64)->CaeResult<(S,[[S;3];4],[S;2])>{
 let [a,b,c,d]=p;let u=sub(b,a);let v=sub(d,c);let w=sub(a,c);let scale=u.iter().chain(&v).map(|x|x.value().abs()).fold(0.,f64::max);if !scale.is_finite()||scale<=0.{return Err(fail("boundary edge scale"));}let factor=S::from_f64(scale);let us=u.map(|x|x/factor);let vs=v.map(|x|x/factor);let ws=w.map(|x|x/factor);let n=cross(us,vs);let n2=dot(n,n);if !n2.value().is_finite()||n2.value()<=minimum_area_ratio*minimum_area_ratio{return Err(fail("parallel edge tie requires independent normal-cone owner"));}let aa=dot(us,us);let bb=dot(us,vs);let cc=dot(vs,vs);let dd=dot(us,ws);let e=dot(vs,ws);let s=(bb*e-cc*dd)/n2;let t=(aa*e-bb*dd)/n2;if [s,t].iter().any(|x|!x.value().is_finite()||x.value()<0.||x.value()>1.){return Err(fail("selected edge closed parameter domain"));}let normal=n.map(|x|x*S::from_f64(orientation)/n2.sqrt());let g=dot(w,normal);let gradient=[normal.map(|x|(S::from_f64(1.)-s)*x),normal.map(|x|s*x),normal.map(|x|-(S::from_f64(1.)-t)*x),normal.map(|x|-t*x)];Ok((g,gradient,[s,t]))
}
fn inputs(p:[[f64;3];4],d:[[f64;3];4],ratio:f64)->CaeResult<[[Dual<1>;3];4]>{if p.iter().flatten().chain(d.iter().flatten()).any(|x|!x.is_finite())||!ratio.is_finite()||ratio<=0.||ratio>=1.{return Err(fail("boundary geometry finite inputs/policy"));}Ok(std::array::from_fn(|i|std::array::from_fn(|j|Dual{re:p[i][j],eps:[d[i][j]]})))}
fn checked(g:InstantaneousGeometry)->CaeResult<InstantaneousGeometry>{if !g.signed_gap_m.is_finite()||!g.gap_direction_m.is_finite()||g.gradient.iter().flatten().chain(g.gradient_direction.iter().flatten()).any(|x|!x.is_finite()){return Err(fail("boundary geometry output overflow"));}Ok(g)}
pub fn vertex_face(p:[[f64;3];4],d:[[f64;3];4],ratio:f64)->CaeResult<InstantaneousGeometry>{let(g,grad,bary)=vf(inputs(p,d,ratio)?,ratio)?;checked(InstantaneousGeometry{signed_gap_m:g.re,gradient:grad.map(|x|x.map(|v|v.re)),gap_direction_m:g.eps[0],gradient_direction:grad.map(|x|x.map(|v|v.eps[0])),selected:SelectedBoundaryStratum::VertexFace{barycentric:bary.map(|v|v.re)}})}
pub fn edge_edge(p:[[f64;3];4],d:[[f64;3];4],orientation:f64,ratio:f64)->CaeResult<InstantaneousGeometry>{if orientation!=1.&&orientation!= -1.{return Err(fail("declared edge normal orientation required"));}let(g,grad,t)=ee(inputs(p,d,ratio)?,orientation,ratio)?;checked(InstantaneousGeometry{signed_gap_m:g.re,gradient:grad.map(|x|x.map(|v|v.re)),gap_direction_m:g.eps[0],gradient_direction:grad.map(|x|x.map(|v|v.eps[0])),selected:SelectedBoundaryStratum::EdgeEdge{parameters:t.map(|v|v.re)}})}
