// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use implexity_core::{CaeError,CaeResult};
use crate::moving_contact::surface_map::SurfaceFeature;
use std::collections::BTreeMap;
fn fail(s:&str)->CaeError{CaeError::contract(s)}
fn sub(a:[f64;3],b:[f64;3])->[f64;3]{std::array::from_fn(|i|a[i]-b[i])}
fn cross(a:[f64;3],b:[f64;3])->[f64;3]{[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}
fn dot(a:[f64;3],b:[f64;3])->f64{a.into_iter().zip(b).map(|(a,b)|a*b).sum()}
#[derive(Clone,Copy)]pub struct IsoSurfacePolicy{pub iso:f64,pub contrast_min:f64,pub interior_margin:f64,pub cap_domain:bool}
#[derive(Clone)]
pub struct ExposedSurface{features:Vec<SurfaceFeature>,facets:Vec<[usize;3]>,signs:Vec<bool>,mesh_identity:String,stratum_identity:String,policy:IsoSurfacePolicy}
impl ExposedSurface{
 pub fn extract(points:&[[f64;3]],tetrahedra:&[[usize;4]],density:&[f64],policy:IsoSurfacePolicy)->CaeResult<Self>{
  if points.is_empty()||points.len()!=density.len()||points.iter().flatten().any(|x|!x.is_finite())||density.iter().any(|x|!x.is_finite()||!(0. ..=1.).contains(x))||!policy.iso.is_finite()||policy.iso<=0.||policy.iso>=1.||!policy.contrast_min.is_finite()||policy.contrast_min<=0.||!policy.interior_margin.is_finite()||policy.interior_margin<=0.||policy.interior_margin>=0.5{return Err(fail("exposed isosurface inputs/policy"));}
  if density.iter().any(|x|*x==policy.iso){return Err(fail("nodal isovalue tie requires explicit stratum owner"));}
  let signs:Vec<_>=density.iter().map(|x|*x>policy.iso).collect();let mut edges=BTreeMap::<[usize;2],usize>::new();let mut features=vec![];let mut facets=vec![];let mut domain_faces=BTreeMap::<[usize;3],([usize;3],usize,usize)>::new();let mut native_vertices=BTreeMap::<usize,usize>::new();
  for t in tetrahedra{if t.iter().any(|i|*i>=points.len())||t.iter().enumerate().any(|(j,i)|t[..j].contains(i)){return Err(fail("exposed tetrahedron indices"));}let volume=dot(sub(points[t[1]],points[t[0]]),cross(sub(points[t[2]],points[t[0]]),sub(points[t[3]],points[t[0]])));if !volume.is_finite()||volume==0.{return Err(fail("exposed tetrahedron geometry degeneracy"));}for opposite in 0..4{let mut face=[t[(opposite+1)%4],t[(opposite+2)%4],t[(opposite+3)%4]];if dot(cross(sub(points[face[1]],points[face[0]]),sub(points[face[2]],points[face[0]])),sub(points[t[opposite]],points[face[0]]))>0.{face.swap(1,2);}let mut key=face;key.sort_unstable();let e=domain_faces.entry(key).or_insert((face,t[opposite],0));e.2+=1;if e.2>2{return Err(fail("nonmanifold native tetrahedral domain"));}}let inside:Vec<_>=t.iter().filter(|i|signs[**i]).copied().collect();let outside:Vec<_>=t.iter().filter(|i|!signs[**i]).copied().collect();if inside.is_empty()||outside.is_empty(){continue;}
   let mut polygon=vec![];for i in &inside{for j in &outside{let mut edge=[*i,*j];edge.sort_unstable();let id=if let Some(id)=edges.get(&edge){*id}else{let feature=SurfaceFeature::DensityEdge{nodes:edge,iso:policy.iso,contrast_min:policy.contrast_min,interior_margin:policy.interior_margin};feature.map(density)?;let id=features.len();features.push(feature);edges.insert(edge,id);id};polygon.push(id);}}
   if polygon.len()!=3&&polygon.len()!=4{return Err(fail("exposed tetrahedral polygon cardinality"));}let q:Vec<_>=polygon.iter().map(|i|features[*i].map(density)?.position(points)).collect::<CaeResult<_>>()?;let center: [f64;3]=std::array::from_fn(|k|q.iter().map(|q|q[k]).sum::<f64>()/q.len()as f64);let direction:[f64;3]=std::array::from_fn(|k|outside.iter().map(|i|points[*i][k]).sum::<f64>()/outside.len()as f64-inside.iter().map(|i|points[*i][k]).sum::<f64>()/inside.len()as f64);let mut normal=cross(sub(q[1],q[0]),sub(q[2],q[0]));if dot(normal,direction)<0.{normal=normal.map(|x|-x);}let n2=dot(normal,normal);if !n2.is_finite()||n2<=0.{return Err(fail("exposed surface normal degeneracy"));}let axis=sub(q[0],center);let tangent=cross(normal,axis);let mut order:Vec<_>=q.iter().enumerate().map(|(k,p)|(k,dot(sub(*p,center),tangent).atan2(dot(sub(*p,center),axis)))).collect();order.sort_by(|a,b|a.1.total_cmp(&b.1));let mut cyclic:Vec<_>=order.iter().map(|(k,_)|polygon[*k]).collect();let minimum=cyclic.iter().enumerate().min_by_key(|(_,i)|**i).unwrap().0;cyclic.rotate_left(minimum);for k in 1..cyclic.len()-1{let f=[cyclic[0],cyclic[k],cyclic[k+1]];let p:Vec<_>=f.iter().map(|i|features[*i].map(density)?.position(points)).collect::<CaeResult<_>>()?;if dot(cross(sub(p[1],p[0]),sub(p[2],p[0])),direction)<=0.{return Err(fail("exposed surface orientation"));}facets.push(f);}
  }
  if policy.cap_domain{for (face,_,count)in domain_faces.values(){if *count!=1{continue;}let mut polygon=vec![];for k in 0..3{let i=face[k];let j=face[(k+1)%3];if signs[i]{let id=if let Some(id)=native_vertices.get(&i){*id}else{let id=features.len();features.push(SurfaceFeature::Vertex(i));native_vertices.insert(i,id);id};polygon.push(id);}if signs[i]!=signs[j]{let mut edge=[i,j];edge.sort_unstable();let id=if let Some(id)=edges.get(&edge){*id}else{let feature=SurfaceFeature::DensityEdge{nodes:edge,iso:policy.iso,contrast_min:policy.contrast_min,interior_margin:policy.interior_margin};feature.map(density)?;let id=features.len();features.push(feature);edges.insert(edge,id);id};polygon.push(id);}}if polygon.len()<3{continue;}if polygon.len()>4{return Err(fail("domain-cap polygon cardinality"));}for k in 1..polygon.len()-1{facets.push([polygon[0],polygon[k],polygon[k+1]]);}}}
  let mesh_identity=implexity_core::json::canonical_sha256(&serde_json::json!({"points":points,"tetrahedra":tetrahedra}));let stratum_identity=implexity_core::json::canonical_sha256(&serde_json::json!({"signs":signs,"edges":edges.keys().collect::<Vec<_>>(),"facets":facets,"iso":policy.iso,"contrast_min":policy.contrast_min,"interior_margin":policy.interior_margin,"native_vertices":native_vertices.keys().collect::<Vec<_>>(),"cap_domain":policy.cap_domain}));Ok(Self{features,facets,signs,mesh_identity,stratum_identity,policy})
 }
 pub fn features(&self)->&[SurfaceFeature]{&self.features}
 pub fn facets(&self)->&[[usize;3]]{&self.facets}
 pub fn mesh_identity(&self)->&str{&self.mesh_identity}
 pub fn stratum_identity(&self)->&str{&self.stratum_identity}
 pub fn positions(&self,points:&[[f64;3]],density:&[f64])->CaeResult<Vec<[f64;3]>>{self.require_fixed_stratum(density)?;if points.len()!=density.len()||points.iter().flatten().any(|x|!x.is_finite()){return Err(fail("exposed nodal position shape"));}self.features.iter().map(|f|f.map(density)?.position(points)).collect()}
 pub fn direction(&self,points:&[[f64;3]],direction:&[[f64;3]],density:&[f64],density_direction:&[f64])->CaeResult<Vec<[f64;3]>>{self.require_fixed_stratum(density)?;if points.len()!=density.len()||direction.len()!=points.len()||density_direction.len()!=density.len()||points.iter().chain(direction).flatten().chain(density_direction).any(|x|!x.is_finite()){return Err(fail("exposed nodal direction shape"));}self.features.iter().map(|f|f.map(density)?.direction(points,direction,density_direction)).collect()}
 pub fn scatter(&self,density:&[f64],force:&[[f64;3]],out:&mut[[f64;3]])->CaeResult<()>{self.require_fixed_stratum(density)?;if out.len()!=density.len()||force.len()!=self.features.len()||force.iter().chain(out.iter()).flatten().any(|x|!x.is_finite()){return Err(fail("exposed surface force shape"));}for (f,v)in self.features.iter().zip(force){f.map(density)?.scatter(*v,out)?;}Ok(())}
 pub fn pullback(&self,points:&[[f64;3]],density:&[f64],cotangent:&[[f64;3]],point_bars:&mut[[f64;3]],density_bars:&mut[f64])->CaeResult<()>{self.positions(points,density)?;if cotangent.len()!=self.features.len()||point_bars.len()!=points.len()||density_bars.len()!=density.len()||cotangent.iter().chain(point_bars.iter()).flatten().chain(density_bars.iter()).any(|x|!x.is_finite()){return Err(fail("exposed pullback shape/finite contract"));}for (f,bar)in self.features.iter().zip(cotangent){let map=f.map(density)?;map.scatter(*bar,point_bars)?;map.density_pullback(points,*bar,density_bars)?;}Ok(())}
 pub fn scatter_direction(&self,density:&[f64],force:&[[f64;3]],force_direction:&[[f64;3]],density_direction:&[f64],out:&mut[[f64;3]])->CaeResult<()>{self.require_fixed_stratum(density)?;if force.len()!=self.features.len()||force_direction.len()!=force.len()||density_direction.len()!=density.len()||out.len()!=density.len()||force.iter().chain(force_direction).chain(out.iter()).flatten().chain(density_direction).any(|x|!x.is_finite()){return Err(fail("exposed scatter derivative shape"));}for ((f,v),dv)in self.features.iter().zip(force).zip(force_direction){f.map(density)?.scatter_direction(*v,*dv,density_direction,out)?;}Ok(())}
 pub fn boundary_edges(&self)->Vec<[usize;2]>{let mut counts=BTreeMap::new();for f in &self.facets{for (a,b)in [(f[0],f[1]),(f[1],f[2]),(f[2],f[0])]{let mut key=[a,b];key.sort_unstable();*counts.entry(key).or_insert(0)+=1;}}counts.into_iter().filter_map(|(e,n)|(n!=2).then_some(e)).collect()}
 pub fn require_closed_surface(&self)->CaeResult<()>{if self.facets.is_empty()||!self.boundary_edges().is_empty(){return Err(fail("exposed surface is not a closed sampled material boundary"));}Ok(())}
 pub fn require_fixed_stratum(&self,density:&[f64])->CaeResult<()>{if density.len()!=self.signs.len()||density.iter().enumerate().any(|(i,x)|!x.is_finite()||!(0. ..=1.).contains(x)||*x==self.policy.iso||(*x>self.policy.iso)!=self.signs[i]){return Err(fail("exposed surface changed nodal stratum: re-extraction required, ordinary derivative refused"));}for f in &self.features{f.map(density)?;}Ok(())}
}
