// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use implexity_core::{CaeError,CaeResult};
use implexity_solve::{multirate_coupling::FluxDrivenField,time_stepper::StepParameters};
use crate::{model::FsiModel,moving_contact::{contact_field::ContactField,contact_set_kinematics::ContactSetKinematics,separate_body::PairSolidField,impact::{self,Impact,ImpactTolerance,ActiveSetImpactPolicy,ActiveSetImpactReport}}};
use super::physical_pair_mass::physical_mass;
fn fail(s:&str)->CaeError{CaeError::contract(s)}
pub struct NativeFamilyImpulse<'a>{pub solid:Vec<f64>,pub fluid_unchanged:&'a[f64],pub trace_history_unchanged:&'a[f64],pub absolute_clock_s:f64,pub impulse:Impact,pub report:ActiveSetImpactReport,pub participating_families:Vec<usize>,pub all_normal_before:Vec<f64>,pub all_normal_after:Vec<f64>,pub identity:String}
pub fn apply<'a,L:ContactSetKinematics>(models:[&FsiModel;2],field:&ContactField<PairSolidField<'_>,L>,before:&[f64],fluid:&'a[f64],trace_history:&'a[f64],design:&[f64],time_scale:f64,absolute_clock_s:f64,restitution:&[f64],tolerance:ImpactTolerance,policy:ActiveSetImpactPolicy,source_graph:&str)->CaeResult<NativeFamilyImpulse<'a>>{
 let participating=(0..field.law().contact_count()).collect::<Vec<_>>();apply_subset(models,field,before,fluid,trace_history,design,time_scale,absolute_clock_s,restitution,tolerance,policy,source_graph,&participating)
}
pub fn apply_subset<'a,L:ContactSetKinematics>(models:[&FsiModel;2],field:&ContactField<PairSolidField<'_>,L>,before:&[f64],fluid:&'a[f64],trace_history:&'a[f64],design:&[f64],time_scale:f64,absolute_clock_s:f64,restitution:&[f64],tolerance:ImpactTolerance,policy:ActiveSetImpactPolicy,source_graph:&str,participating:&[usize])->CaeResult<NativeFamilyImpulse<'a>>{
 if before.len()!=field.state_size()||design.len()!=field.design_size()||before.iter().chain(design).chain(fluid).chain(trace_history).any(|v|!v.is_finite())||fluid.iter().any(|v|*v<0.)||!time_scale.is_finite()||time_scale<=0.||!absolute_clock_s.is_finite()||absolute_clock_s<0.||source_graph.len()!=64||!source_graph.bytes().all(|v|v.is_ascii_hexdigit()){return Err(fail("native family physical impulse inputs"));}
 let p=StepParameters{design,time_scale};field.check_state_domain(1,before,before,p)?;let count=field.law().contact_count();if restitution.len()!=count||count==0{return Err(fail("native family explicit restitution width"));}let(rows,gaps)=field.law().instantaneous_rows(before,design)?;
 if rows.len()!=count||gaps.len()!=count||rows.iter().any(|r|r.len()!=field.native().trace_operator().nrows()||r.iter().any(|v|!v.is_finite()))||gaps.iter().any(|v|!v.is_finite())||participating.is_empty()||participating.iter().enumerate().any(|(i,k)|*k>=count||participating[..i].contains(k))||restitution.iter().any(|e|!e.is_finite()||!(0. ..=1.).contains(e))||![tolerance.event_gap_m,tolerance.normal_velocity_m_s,tolerance.impulse_n_s,tolerance.momentum_n_s,tolerance.energy_j].iter().all(|v|v.is_finite()&&*v>0.){return Err(fail("native explicit impact-family selection"));}
 for k in 0..count{if !participating.contains(&k)&&(before[field.native().state_size()+k]!=0.||!gaps[k].is_finite()||gaps[k]<=tolerance.event_gap_m){return Err(fail("unselected physical family is not strictly open with zero multiplier; localized contact may not be omitted"));}}
 let selected_rows=participating.iter().map(|k|rows[*k].clone()).collect::<Vec<_>>();let selected_gaps=participating.iter().map(|k|gaps[*k]).collect::<Vec<_>>();let selected_restitution=participating.iter().map(|k|restitution[*k]).collect::<Vec<_>>();
 let mut velocity=Vec::new();let(mut so,mut d)= (0,0);for b in 0..2{let body=field.native().body_field(b)?;if !std::ptr::eq(body.core().model(),&models[b].soft){return Err(fail("native family borrowed body identity"));}let end=d+body.design_size();let h=body.core().history(StepParameters{design:&design[d..end],time_scale})?;let physical=body.core().to_physical(&before[so..so+body.state_size()]);velocity.extend_from_slice(&physical[h.layout.v()..h.layout.v()+h.layout.n3]);so+=body.state_size();d=end;}
 let mass=physical_mass(models,field.native(),design)?;let(impulse,report)=impact::solve_scalable_with_report(&mass,&velocity,&selected_rows,&selected_restitution,&selected_gaps,tolerance,policy)?;let mut solid=before.to_vec();let(mut so,mut d,mut vo)=(0,0,0);for b in 0..2{let body=field.native().body_field(b)?;let end=d+body.design_size();let h=body.core().history(StepParameters{design:&design[d..end],time_scale})?;let mut physical=body.core().to_physical(&before[so..so+body.state_size()]);physical[h.layout.v()..h.layout.v()+h.layout.n3].copy_from_slice(&impulse.velocity[vo..vo+h.layout.n3]);let scaled=body.core().to_scaled(&physical);solid[so+h.layout.v()..so+h.layout.v()+h.layout.n3].copy_from_slice(&scaled[h.layout.v()..h.layout.v()+h.layout.n3]);so+=body.state_size();d=end;vo+=h.layout.n3;}
 let all_normal_before=rows.iter().map(|r|r.iter().zip(&velocity).map(|(a,b)|a*b).sum()).collect::<Vec<f64>>();let all_normal_after=rows.iter().map(|r|r.iter().zip(&impulse.velocity).map(|(a,b)|a*b).sum()).collect::<Vec<f64>>();let identity=implexity_core::json::canonical_sha256(&serde_json::json!({"source_graph":source_graph,"features":field.law().bound_owner_features(&serde_json::json!({}))?,"before_bits":before.iter().map(|v|v.to_bits()).collect::<Vec<_>>(),"after_bits":solid.iter().map(|v|v.to_bits()).collect::<Vec<_>>(),"fluid_bits":fluid.iter().map(|v|v.to_bits()).collect::<Vec<_>>(),"trace_history_bits":trace_history.iter().map(|v|v.to_bits()).collect::<Vec<_>>(),"design":design,"time_scale_bits":time_scale.to_bits(),"clock_bits":absolute_clock_s.to_bits(),"restitution":restitution,"participating_families":participating,"impact_tolerance":{"event_gap_m":tolerance.event_gap_m,"normal_velocity_m_s":tolerance.normal_velocity_m_s,"impulse_n_s":tolerance.impulse_n_s,"momentum_n_s":tolerance.momentum_n_s,"energy_j":tolerance.energy_j},"maximum_pivots":policy.maximum_pivots,"impulses":impulse.impulses}));Ok(NativeFamilyImpulse{solid,fluid_unchanged:fluid,trace_history_unchanged:trace_history,absolute_clock_s,impulse,report,participating_families:participating.to_vec(),all_normal_before,all_normal_after,identity})
}
