// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use implexity_core::{CaeError,CaeResult};
use implexity_ad::Dual;
use implexity_linalg::{sparse::CsrMatrix,lu::{SparseLu,LuSymbolic,Parallelism}};
use crate::{model::FsiModel,moving_contact::{separate_body::PairSolidField,impact::MassMetric}};
use implexity_solve::multirate_coupling::FluxDrivenField;
fn fail(e:impl std::fmt::Display)->CaeError{CaeError::contract(e.to_string())}
pub struct BorrowedPhysicalMass{matrix:CsrMatrix,fixed:Vec<bool>,free:Vec<usize>,factor:SparseLu}
impl BorrowedPhysicalMass{pub fn matrix(&self)->&CsrMatrix{&self.matrix}pub fn new(matrix:CsrMatrix,fixed:Vec<bool>)->CaeResult<Self>{if matrix.nrows()!=fixed.len()||matrix.ncols()!=fixed.len(){return Err(fail("physical mass shape"));}let free:Vec<_>=(0..fixed.len()).filter(|i|!fixed[*i]).collect();let mut map=vec![usize::MAX;fixed.len()];for(i,&j)in free.iter().enumerate(){map[j]=i;}let(mut ri,mut ci,mut vs)=(vec![],vec![],vec![]);for(i,&r)in free.iter().enumerate(){let(js,v)=matrix.row(r);for(&c,&x)in js.iter().zip(v){if !x.is_finite(){return Err(fail("physical mass nonfinite"));}if map[c]!=usize::MAX{ri.push(i);ci.push(map[c]);vs.push(x);}}}let sub=CsrMatrix::from_triplets(free.len(),free.len(),&ri,&ci,&vs).map_err(fail)?.to_csc();let factor=LuSymbolic::analyze(&sub).and_then(|s|s.factor(&sub,Parallelism::Sequential)).map_err(fail)?;Ok(Self{matrix,fixed,free,factor})}}
impl MassMetric for BorrowedPhysicalMass{fn size(&self)->usize{self.fixed.len()}fn fixed(&self)->&[bool]{&self.fixed}fn apply(&self,v:&[f64])->CaeResult<Vec<f64>>{self.matrix.matvec(v).map_err(fail)}fn inverse_free(&self,f:&[f64])->CaeResult<Vec<f64>>{if f.len()!=self.size()||f.iter().any(|v|!v.is_finite()){return Err(fail("physical inverse mass input"));}let rhs:Vec<_>=self.free.iter().map(|i|f[*i]).collect();let x=self.factor.solve(&rhs).map_err(fail)?;let mut out=vec![0.;self.size()];for(&i,&v)in self.free.iter().zip(&x){out[i]=v;}Ok(out)}}
pub fn physical_mass_matrix(models:[&FsiModel;2],field:&PairSolidField<'_>,design:&[f64],direction:Option<&[f64]>)->CaeResult<(CsrMatrix,Vec<bool>)>{
if design.len()!=field.design_size()||direction.is_some_and(|d|d.len()!=design.len())||design.iter().chain(direction.into_iter().flatten()).any(|v|!v.is_finite()){return Err(fail("borrowed physical mass design shape"));}let mut matrices=vec![];let mut fixed=vec![];let mut start=0;for b in 0..2{let native=models[b];let body=field.body_field(b)?;let core=body.core();if !std::ptr::eq(core.model(),&native.soft){return Err(fail("borrowed physical mass body identity"));}let end=start+body.design_size();let parameters=core.params(&design[start..end])?;let soft=core.model();let removed=native.problem.solid.inertia_compensation*native.problem.fluid.density_kg_m3;let ratio:Vec<_>=(0..soft.ne()).map(|e|{let rho=soft.materials[soft.element_material[e]].density;(rho+removed)/rho}).collect();if ratio.iter().any(|r|!r.is_finite()||*r<1.){return Err(fail("two-body physical mass compensation domain"));}let factors=if let Some(d)=direction{let dp=core.params(&d[start..end])?;(0..soft.ne()).map(|i|soft.interpolation.mass(Dual::new(parameters[i],[dp[i]])).eps[0]*ratio[i]).collect::<Vec<_>>()}else{(0..soft.ne()).map(|i|soft.interpolation.mass(parameters[i])*ratio[i]).collect::<Vec<_>>()};matrices.push(soft.global_mass_and_reference(&factors,&vec![0.;soft.ne()])?.0);fixed.extend(&soft.fixed);start=end;}
let(mut ri,mut ci,mut vs)=(vec![],vec![],vec![]);for (block,offset)in [(&matrices[0],0),(&matrices[1],matrices[0].nrows())]{for i in 0..block.nrows(){let(js,values)=block.row(i);for(&j,&v)in js.iter().zip(values){ri.push(offset+i);ci.push(offset+j);vs.push(v);}}}Ok((CsrMatrix::from_triplets(fixed.len(),fixed.len(),&ri,&ci,&vs).map_err(fail)?,fixed))}
pub fn physical_mass(models:[&FsiModel;2],field:&PairSolidField<'_>,design:&[f64])->CaeResult<BorrowedPhysicalMass>{let(m,f)=physical_mass_matrix(models,field,design,None)?;BorrowedPhysicalMass::new(m,f)}
