// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END



#[cfg(feature = "dynamic-results")]
pub(crate) static FILES: &[(&str, &[u8])] = &[
    ("advanced_commands.css", include_bytes!("../../../viewer/advanced_commands.css")),
    ("advanced_commands.css.license", include_bytes!("../../../viewer/advanced_commands.css.license")),
    ("advanced_commands.js", include_bytes!("../../../viewer/advanced_commands.js")),
    ("advanced_commands.js.license", include_bytes!("../../../viewer/advanced_commands.js.license")),
    ("boundary_authoring.js", include_bytes!("../../../viewer/boundary_authoring.js")),
    ("cfd_workspace.css", include_bytes!("../../../viewer/cfd_workspace.css")),
    ("cfd_workspace.js", include_bytes!("../../../viewer/cfd_workspace.js")),
    ("design_bounds.js", include_bytes!("../../../viewer/design_bounds.js")),
    ("design_freedom.js", include_bytes!("../../../viewer/design_freedom.js")),
    ("editing_workspace.css", include_bytes!("../../../viewer/editing_workspace.css")),
    ("editing_workspace.js", include_bytes!("../../../viewer/editing_workspace.js")),
    ("field_tile_worker.js", include_bytes!("../../../viewer/field_tile_worker.js")),
    ("field_visibility.js", include_bytes!("../../../viewer/field_visibility.js")),
    ("fonts/OFL.txt", include_bytes!("../../../viewer/fonts/OFL.txt")),
    ("fonts/OFL.txt.license", include_bytes!("../../../viewer/fonts/OFL.txt.license")),
    ("geometry_seed.css", include_bytes!("../../../viewer/geometry_seed.css")),
    ("geometry_seed.js", include_bytes!("../../../viewer/geometry_seed.js")),
    ("gui_text.js", include_bytes!("../../../viewer/gui_text.js")),
    ("guided_setup.css", include_bytes!("../../../viewer/guided_setup.css")),
    ("guided_setup.css.license", include_bytes!("../../../viewer/guided_setup.css.license")),
    ("guided_setup.js", include_bytes!("../../../viewer/guided_setup.js")),
    ("guided_setup.js.license", include_bytes!("../../../viewer/guided_setup.js.license")),
    ("interaction.css", include_bytes!("../../../viewer/interaction.css")),
    ("interaction.js", include_bytes!("../../../viewer/interaction.js")),
    ("managed_evaluation_workspace.js", include_bytes!("../../../viewer/managed_evaluation_workspace.js")),
    ("manual_interaction.js", include_bytes!("../../../viewer/manual_interaction.js")),
    ("model.html", include_bytes!("../../../viewer/model.html")),
    ("numerical_progress.js", include_bytes!("../../../viewer/numerical_progress.js")),
    ("objective_composer.css", include_bytes!("../../../viewer/objective_composer.css")),
    ("objective_composer.js", include_bytes!("../../../viewer/objective_composer.js")),
    ("optimization_workspace.css", include_bytes!("../../../viewer/optimization_workspace.css")),
    ("optimization_workspace.js", include_bytes!("../../../viewer/optimization_workspace.js")),
    ("output_dialogs.css", include_bytes!("../../../viewer/output_dialogs.css")),
    ("output_dialogs.js", include_bytes!("../../../viewer/output_dialogs.js")),
    ("parametric_modeling.js", include_bytes!("../../../viewer/parametric_modeling.js")),
    ("physics_packages.css", include_bytes!("../../../viewer/physics_packages.css")),
    ("physics_packages.js", include_bytes!("../../../viewer/physics_packages.js")),
    ("progressive_field.css", include_bytes!("../../../viewer/progressive_field.css")),
    ("progressive_field.js", include_bytes!("../../../viewer/progressive_field.js")),
    ("provider_problem_persistence.js", include_bytes!("../../../viewer/provider_problem_persistence.js")),
    ("raymarch.js", include_bytes!("../../../viewer/raymarch.js")),
    ("rust_ext/dynamic_results.css", include_bytes!("../../../viewer/rust_ext/dynamic_results.css")),
    ("rust_ext/dynamic_results.html", include_bytes!("../../../viewer/rust_ext/dynamic_results.html")),
    ("rust_ext/dynamic_results.js", include_bytes!("../../../viewer/rust_ext/dynamic_results.js")),
    ("rust_ext/extensions.css", include_bytes!("../../../viewer/rust_ext/extensions.css")),
    ("rust_ext/extensions.js", include_bytes!("../../../viewer/rust_ext/extensions.js")),
    ("rust_ext/native.css", include_bytes!("../../../viewer/rust_ext/native.css")),
    ("sensitivity_authoring.css", include_bytes!("../../../viewer/sensitivity_authoring.css")),
    ("sensitivity_authoring.js", include_bytes!("../../../viewer/sensitivity_authoring.js")),
    ("shared_manual_history.js", include_bytes!("../../../viewer/shared_manual_history.js")),
    ("shared_manual_history.js.license", include_bytes!("../../../viewer/shared_manual_history.js.license")),
    ("study_workspace.js", include_bytes!("../../../viewer/study_workspace.js")),
    ("surface_authoring.css", include_bytes!("../../../viewer/surface_authoring.css")),
    ("surface_authoring.js", include_bytes!("../../../viewer/surface_authoring.js")),
    ("workbench.css", include_bytes!("../../../viewer/workbench.css")),
    ("workbench.js", include_bytes!("../../../viewer/workbench.js")),
];

#[cfg(not(feature = "dynamic-results"))]
pub(crate) static FILES: &[(&str, &[u8])] = &[
    ("advanced_commands.css", include_bytes!("../../../viewer/advanced_commands.css")),
    ("advanced_commands.css.license", include_bytes!("../../../viewer/advanced_commands.css.license")),
    ("advanced_commands.js", include_bytes!("../../../viewer/advanced_commands.js")),
    ("advanced_commands.js.license", include_bytes!("../../../viewer/advanced_commands.js.license")),
    ("boundary_authoring.js", include_bytes!("../../../viewer/boundary_authoring.js")),
    ("cfd_workspace.css", include_bytes!("../../../viewer/cfd_workspace.css")),
    ("cfd_workspace.js", include_bytes!("../../../viewer/cfd_workspace.js")),
    ("design_bounds.js", include_bytes!("../../../viewer/design_bounds.js")),
    ("design_freedom.js", include_bytes!("../../../viewer/design_freedom.js")),
    ("editing_workspace.css", include_bytes!("../../../viewer/editing_workspace.css")),
    ("editing_workspace.js", include_bytes!("../../../viewer/editing_workspace.js")),
    ("field_tile_worker.js", include_bytes!("../../../viewer/field_tile_worker.js")),
    ("field_visibility.js", include_bytes!("../../../viewer/field_visibility.js")),
    ("fonts/OFL.txt", include_bytes!("../../../viewer/fonts/OFL.txt")),
    ("fonts/OFL.txt.license", include_bytes!("../../../viewer/fonts/OFL.txt.license")),
    ("geometry_seed.css", include_bytes!("../../../viewer/geometry_seed.css")),
    ("geometry_seed.js", include_bytes!("../../../viewer/geometry_seed.js")),
    ("gui_text.js", include_bytes!("../../../viewer/gui_text.js")),
    ("guided_setup.css", include_bytes!("../../../viewer/guided_setup.css")),
    ("guided_setup.css.license", include_bytes!("../../../viewer/guided_setup.css.license")),
    ("guided_setup.js", include_bytes!("../../../viewer/guided_setup.js")),
    ("guided_setup.js.license", include_bytes!("../../../viewer/guided_setup.js.license")),
    ("interaction.css", include_bytes!("../../../viewer/interaction.css")),
    ("interaction.js", include_bytes!("../../../viewer/interaction.js")),
    ("managed_evaluation_workspace.js", include_bytes!("../../../viewer/managed_evaluation_workspace.js")),
    ("manual_interaction.js", include_bytes!("../../../viewer/manual_interaction.js")),
    ("model.html", include_bytes!("../../../viewer/model.html")),
    ("numerical_progress.js", include_bytes!("../../../viewer/numerical_progress.js")),
    ("objective_composer.css", include_bytes!("../../../viewer/objective_composer.css")),
    ("objective_composer.js", include_bytes!("../../../viewer/objective_composer.js")),
    ("optimization_workspace.css", include_bytes!("../../../viewer/optimization_workspace.css")),
    ("optimization_workspace.js", include_bytes!("../../../viewer/optimization_workspace.js")),
    ("output_dialogs.css", include_bytes!("../../../viewer/output_dialogs.css")),
    ("output_dialogs.js", include_bytes!("../../../viewer/output_dialogs.js")),
    ("parametric_modeling.js", include_bytes!("../../../viewer/parametric_modeling.js")),
    ("physics_packages.css", include_bytes!("../../../viewer/physics_packages.css")),
    ("physics_packages.js", include_bytes!("../../../viewer/physics_packages.js")),
    ("progressive_field.css", include_bytes!("../../../viewer/progressive_field.css")),
    ("progressive_field.js", include_bytes!("../../../viewer/progressive_field.js")),
    ("provider_problem_persistence.js", include_bytes!("../../../viewer/provider_problem_persistence.js")),
    ("raymarch.js", include_bytes!("../../../viewer/raymarch.js")),
    ("sensitivity_authoring.css", include_bytes!("../../../viewer/sensitivity_authoring.css")),
    ("sensitivity_authoring.js", include_bytes!("../../../viewer/sensitivity_authoring.js")),
    ("shared_manual_history.js", include_bytes!("../../../viewer/shared_manual_history.js")),
    ("shared_manual_history.js.license", include_bytes!("../../../viewer/shared_manual_history.js.license")),
    ("study_workspace.js", include_bytes!("../../../viewer/study_workspace.js")),
    ("surface_authoring.css", include_bytes!("../../../viewer/surface_authoring.css")),
    ("surface_authoring.js", include_bytes!("../../../viewer/surface_authoring.js")),
    ("workbench.css", include_bytes!("../../../viewer/workbench.css")),
    ("workbench.js", include_bytes!("../../../viewer/workbench.js")),
];
