// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

(() => {
  const initialize=()=>{
  if(window.ImplexityParametric||!window.S||!window.ImplexityParametricHost)return;
  const S=window.S;
  const {graphEdit,exprNames,uiLabel}=window.ImplexityParametricHost;
  let active = null;
  const element = (tag, text, parent) => { const node = document.createElement(tag); if(text !== undefined) node.textContent = text; parent?.append(node); return node; };
  const snapshot = () => S.model?.loaded ? {structure_id:S.model.structure_id,content_id:S.model.content_id} : undefined;
  const label = name => window.ImplexityText?.humanize?.(name)||(typeof uiLabel === 'function' ? uiLabel(name) : name);
  const numeric = value => { if(!String(value).trim()) throw new Error('A numeric value is required.'); const number = Number(value); if(!Number.isFinite(number)) throw new Error('Values must be finite numbers.'); return number; };
  const identifier = value => { const name = String(value).trim(); if(!/^[A-Za-z_][A-Za-z0-9_.:-]{0,63}$/.test(name)) throw new Error('Use a name of up to 64 characters, beginning with a letter or underscore.'); return name; };
  const nodeIdentifier = value => {const name=String(value).trim();if(!/^[A-Za-z_][A-Za-z0-9_.:-]{0,63}$/.test(name))throw new Error('Use a feature name of up to 64 characters, beginning with a letter or underscore.');return name;};
  function input(parent, title, value = '', type = 'text') { const box = element('label',title,parent); box.className='pm-field'; const node=element('input',undefined,box);node.type=type;node.value=value ?? '';if(type==='number') node.step='any';return node; }
  function select(parent,title,options,value) { const box=element('label',title,parent);box.className='pm-field';const node=element('select',undefined,box);for(const [key,name] of options){const option=element('option',name,node);option.value=key;}node.value=value;return node; }
  function area(parent,title,value='') {const box=element('label',title,parent);box.className='pm-field';const node=element('textarea',undefined,box);node.value=value;node.rows=3;return node;}
  function dialog(title) {
    if(!S.model?.loaded){const out=document.getElementById('grapheditout');if(out)out.textContent='Load or create a model before editing features or parameters.';return null;}
    if(active?.busy){active.status.textContent='The current change is being saved.';return null;}
    active?.node.close();const node=element('dialog',undefined,document.body);node.className='pm-dialog';element('h3',title,node);const body=element('div',undefined,node);const status=element('div','',node);status.className='pm-status';status.setAttribute('role','status');const actions=element('div',undefined,node);actions.className='pm-actions';const save=element('button','Save',actions);save.type='button';const close=element('button','Cancel',actions);close.type='button';const state={node,body,status,save,close,busy:false,expected:snapshot()};active=state;close.onclick=()=>node.close();node.addEventListener('cancel',event=>{if(state.busy)event.preventDefault();});node.addEventListener('close',()=>{node.remove();if(active===state)active=null;});return state;
  }
  function commit(state, build, selected) {state.save.onclick=async()=>{if(state.busy)return;try{const operations=build();state.busy=true;state.save.disabled=true;state.close.disabled=true;state.status.textContent='Saving…';const result=await graphEdit(operations,typeof selected==='function'?selected():selected,state.expected);if(result)state.node.close();else state.status.textContent=document.getElementById('grapheditout')?.textContent||'The change was refused. Reopen this dialog if the model changed.';}catch(error){state.status.textContent=error.message;}finally{state.busy=false;state.save.disabled=false;state.close.disabled=false;}};state.node.showModal();}
  function parameterValue(mode,raw,discrete) {
    if(mode==='bind'){const name=String(raw).trim();if(!(S.params||[]).some(p=>p.name===name))throw new Error('Choose an existing named parameter.');return {bind:name};}
    if(mode==='expr'){const expr=String(raw).trim();if(!expr)throw new Error('An equation is required.');return {expr};}
    const text=String(raw).trim();if(!text)throw new Error('A literal value is required.');const value=JSON.parse(text);if(typeof value==='number'&&!Number.isFinite(value))throw new Error('Values must be finite numbers.');if(discrete&&(!Number.isInteger(value)))throw new Error('Discrete counts must be integers.');return value;
  }
  function fieldEditor(parent, parameter, raw, discrete) {
    if(['vertices_mm','path_mm'].includes(parameter.name)&&(!raw||Array.isArray(raw))){const path=parameter.name==='path_mm',count=path?3:2;const value=area(parent,path?'Path points X, Y, Z / mm':'Profile vertices X, Y / mm',(raw||parameter.default||[]).map(point=>point.join(', ')).join('\n'));return()=>{const rows=value.value.trim().split(/\n+/).map(line=>line.split(/[,\s]+/).filter(Boolean).map(numeric));if(rows.length<(path?2:3)||rows.some(row=>row.length!==count))throw new Error(path?'Enter at least two X, Y, Z points.':'Enter at least three X, Y vertex pairs.');return rows;};}

    const row=element('div',undefined,parent);row.className='pm-value-row';const unit=parameter.units||'-';const modeValue=raw&&typeof raw==='object'&&'bind' in raw?'bind':raw&&typeof raw==='object'&&'expr' in raw?'expr':'literal';const fieldName=parameter.name.endsWith('_'+unit)?parameter.name.slice(0,-unit.length-1):parameter.name;const mode=select(row,label(fieldName)+' / '+unit,[['literal','Value'],['bind','Named parameter'],['expr','Equation']],modeValue);let value;
    const literal=typeof raw==='number'?'number':'text';value=input(row,'Definition',modeValue==='bind'?raw.bind:modeValue==='expr'?raw.expr:raw===undefined?'':JSON.stringify(raw),modeValue==='literal'?literal:'text');if(discrete&&value.type==='number')value.step='1';const help=element('div',parameter.doc||'',row);help.className='pm-hint';const choices=element('datalist',undefined,row);choices.id='pm-bind-'+Math.random().toString(36).slice(2);for(const p of S.params||[]){const option=element('option',p.units||'-',choices);option.value=p.name;}
    const update=()=>{value.type=mode.value==='literal'?literal:'text';if(mode.value==='bind')value.setAttribute('list',choices.id);else value.removeAttribute('list');value.placeholder=mode.value==='bind'?'Parameter name':mode.value==='expr'?'Equation using named parameters':'Numeric value or JSON';};mode.onchange=()=>{value.value='';update();};update();return ()=>parameterValue(mode.value,value.value,discrete);
  }
  function feature(kind, editId) {
    const registry=(S.cat?.kinds||[]).find(k=>k.kind===kind);if(!registry){const out=document.getElementById('grapheditout');if(out)out.textContent='This service does not provide that geometry feature.';return;}
    const existing=editId?S.model.document.nodes[editId]:null;const title=(kind==='fillet'?'Implicit blend':kind==='chamfer'?'Implicit chamfer':label(kind));const state=dialog((existing?'Edit ':'Add ')+title);if(!state)return;
    if(kind==='fillet'||kind==='chamfer')element('p','Blends the implicit fields of two shapes.',state.body);
    const nodes=Object.keys(S.model?.document?.nodes||{});let proposed=kind.replace(/[^A-Za-z0-9_]/g,'_')||'feature';let suffix=1;while(nodes.includes(proposed))proposed=kind.replace(/[^A-Za-z0-9_]/g,'_')+'_'+suffix++;
    const name=input(state.body,'Feature name',editId||proposed);if(existing)name.readOnly=true;
    const fields=element('div',undefined,state.body);fields.className='pm-grid';const readers=new Map();const defined=new Map((registry.params||[]).map(p=>[p.name,p]));for(const key of Object.keys(existing?.params||{}))if(!defined.has(key))defined.set(key,{name:key,units:existing.units?.[key]||''});
    for(const [key,p] of defined)readers.set(key,fieldEditor(fields,{...p,units:existing?.units?.[key]||p.units},existing&&key in (existing.params||{})?existing.params[key]:p.default,(registry.discrete||[]).includes(key)));
    const childrenBox=element('div',undefined,state.body);element('h4','Ordered children',childrenBox);const rows=[];const arity=registry.arity_declared?Number(registry.arity):registry.field_class?.leaf?0:null;
    function child(child={},index=rows.length){const row=element('div',undefined,childrenBox);row.className='pm-child';const socket=input(row,'Socket',child.name|| (arity===1?'shape':'c'+index));const candidates=nodes.filter(id=>id!==editId);const picker=select(row,'Existing feature',candidates.map(id=>[id,label(id)]),child.node||child.id||candidates.find(id=>id===S.sel)||candidates[0]||'');const remove=element('button','Remove',row);remove.type='button';remove.disabled=arity!==null;const item={row,socket,picker};remove.onclick=()=>{row.remove();rows.splice(rows.indexOf(item),1);};rows.push(item);}
    const original=existing?.children||[];if(existing)original.forEach((c,i)=>child(typeof c==='string'?{node:c,name:'c'+i}:c,i));else if(arity!==null)for(let i=0;i<arity;i++)child({},i);
    if(arity===null){const add=element('button','Add child',childrenBox);add.type='button';add.onclick=()=>child();}
    const mode=select(state.body,'Geometry root',existing?[['keep','Keep current root'],['root','Make this feature the root']]:[['keep','Keep current root'],['root','Make this feature the root'],...(arity===1&&S.model?.root?[['wrap','Wrap current root with this feature']]:[])],S.model?.loaded?'keep':'root');
    if(!existing&&arity===1){mode.onchange=()=>{if(mode.value==='wrap')rows[0].picker.value=S.model.root;rows[0].picker.disabled=mode.value==='wrap';};}
    let constraintRows=[];
    if(kind==='profile.polygon'){
      const holder=element('details',undefined,state.body);element('summary','Profile constraints',holder);
      const rows=element('div',undefined,holder);const addConstraint=value=>{const row=element('div',undefined,rows);row.className='pm-grid';const type=select(row,'Relation',[['horizontal','Horizontal'],['vertical','Vertical'],['length','Length']],value?.type||'horizontal');const start=input(row,'Start vertex / index',value?.start??0,'number'),end=input(row,'End vertex / index',value?.end??1,'number'),dimension=input(row,'Dimension / index',value?.dimension??0,'number');const remove=element('button','Remove',row);remove.type='button';const item={row,type,start,end,dimension};remove.onclick=()=>{row.remove();constraintRows=constraintRows.filter(other=>other!==item);};const update=()=>dimension.closest('label').hidden=type.value!=='length';type.onchange=update;update();constraintRows.push(item);};
      for(const value of existing?.attrs?.constraints||[])addConstraint(value);const add=element('button','Add relation',holder);add.type='button';add.onclick=()=>addConstraint();
    }
    const attributes=kind==='profile.polygon'?null:registry.struct?.length||Object.keys(existing?.attrs||{}).length?area(state.body,'Shape settings / JSON',JSON.stringify(existing?.attrs||{},null,2)):null;

    commit(state,()=>{const id=existing?editId:nodeIdentifier(name.value);const params={};for(const [key,read]of readers)params[key]=read();const children=rows.map(r=>({name:String(r.socket.value).trim(),node:r.picker.value}));if(arity!==null&&children.length!==arity)throw new Error('This feature requires '+arity+' children.');if(children.some(c=>!c.name))throw new Error('Child socket names must not be empty.');if(children.some(c=>!c.node))throw new Error('Choose an existing feature for every child.');if(new Set(children.map(c=>c.name)).size!==children.length)throw new Error('Child socket names must differ.');const attrs=kind==='profile.polygon'?{...(existing?.attrs||{}),constraints:constraintRows.map(row=>{const start=numeric(row.start.value),end=numeric(row.end.value),dimension=numeric(row.dimension.value);if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||end<=start)throw new Error('Constraint indices must be integers with start smaller than end.');return {type:row.type.value,start,end,...(row.type.value==='length'?{dimension}: {})};})}:attributes?JSON.parse(attributes.value):{};if(!attrs||Array.isArray(attrs)||typeof attrs!=='object')throw new Error('Shape settings must be a JSON object.');if(existing&&Object.keys(existing.attrs||{}).some(key=>!(key in attrs)))throw new Error('Removing shape settings requires document editing.');const ops=[];if(existing){for(const [key,value]of Object.entries(params))ops.push({op:'set_node_param',id,param:key,value});for(const c of original)ops.push({op:'disconnect',parent:id,name:typeof c==='string'?c:c.name});for(const c of children)ops.push({op:'connect',parent:id,name:c.name,child:c.node});for(const [key,value]of Object.entries(attrs))ops.push({op:'set_node_attr',id,attr:key,value});}else ops.push({op:'add_node',id,kind,params,children,attrs});if(mode.value!=='keep')ops.push({op:'set_root',id});return ops;},()=>name.value.trim());
  }
  function parameter(name) {
    const existing=(S.params||[]).find(p=>p.name===name);const definition=S.model?.document?.parameters?.[name]||{};const state=dialog(existing?'Edit parameter':'Add parameter');if(!state)return;const id=input(state.body,'Name',name||'');if(existing)id.readOnly=true;const units=input(state.body,'Authored unit',definition.units||existing?.units||'mm');if(existing)element('div','Resolved value / '+(existing.units||'-')+' = '+existing.value,state.body);const mode=select(state.body,'Definition',[['value','Independent value'],['expr','Equation']],existing?.derived?'expr':'value');const value=input(state.body,'Value',typeof definition==='number'?definition:definition.value??(existing?.derived?'':existing?.value??1),'number');const expr=input(state.body,'Equation',definition.expr||existing?.expr||'');const deps=element('div','',state.body);deps.className='pm-hint';const bounds=element('div',undefined,state.body);bounds.className='pm-grid';const lower=input(bounds,'Minimum',definition.min??existing?.min??'','number');const upper=input(bounds,'Maximum',definition.max??existing?.max??'','number');const free=input(bounds,'Free design variable','','checkbox');free.checked=Boolean(existing?.free);const update=()=>{const derived=mode.value==='expr';value.closest('label').hidden=derived;expr.closest('label').hidden=!derived;bounds.hidden=derived;deps.textContent=derived?'Dependencies: '+(exprNames(expr.value).join(', ')||'none'):'Bounds apply to an independent design variable.';};mode.onchange=update;expr.oninput=update;const updateUnits=()=>{for(const [control,title]of [[value,'Value'],[lower,'Minimum'],[upper,'Maximum']])control.closest('label').firstChild.textContent=title+' / '+(units.value.trim()||'-');};units.oninput=units.onchange=()=>{value.value='';lower.value='';upper.value='';expr.value='';free.checked=false;updateUnits();update();state.status.textContent='Unit changed. Enter the definition and any bounds in the new unit.';};updateUnits();update();commit(state,()=>{const op={op:existing?'set_parameter_definition':'add_parameter',name:existing?existing.name:identifier(id.value),units:units.value.trim()};if(mode.value==='expr'){op.expr=expr.value.trim();if(!op.expr)throw new Error('An equation is required.');if(existing){op.free=false;op.min=null;op.max=null;}}else{op.value=numeric(value.value);op.free=free.checked;const hasLower=lower.value.trim()!=='';const hasUpper=upper.value.trim()!=='';if(hasLower!==hasUpper)throw new Error('Set both bounds or leave both empty.');if(hasLower){op.min=numeric(lower.value);op.max=numeric(upper.value);if(op.max<=op.min||op.value<op.min||op.value>op.max)throw new Error('Bounds must enclose the value and have a positive span.');}else if(op.free)throw new Error('A free variable requires minimum and maximum bounds.');else if(existing){op.min=null;op.max=null;}}return [op];},S.sel);
  }
  const style=element('style',undefined,document.head);style.textContent='.pm-dialog{width:min(860px,94vw);max-height:90vh;overflow:auto;border:1px solid var(--line);border-radius:8px;padding:18px;background:var(--panel,#fff);color:var(--text,#17232e)}.pm-dialog h3{margin:0 0 12px}.pm-field{display:grid;gap:4px;margin:7px 0;font-size:12px}.pm-field input,.pm-field select,.pm-field textarea{width:100%;box-sizing:border-box}.pm-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px 14px}.pm-value-row{min-width:0;border-bottom:1px solid var(--line);padding-bottom:7px}.pm-hint,.pm-status{font-size:12px;white-space:pre-wrap}.pm-child{display:grid;grid-template-columns:1fr 2fr auto;gap:9px;align-items:end}.pm-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.pm-actions button,.pm-child button{width:auto}.pm-dialog [hidden]{display:none!important}';
  function meshImport(){
    const state=dialog('Import mesh as implicit geometry');if(!state)return;
    const file=input(state.body,'Closed STL or PLY mesh','','file');file.accept='.stl,.ply';const name=input(state.body,'Feature name','imported_mesh');const units=select(state.body,'File coordinates / unit',[['mm','mm'],['m','m']],'mm');const spacing=input(state.body,'Implicit sampling / mm',1,'number');const root=select(state.body,'Geometry root',[['root','Use imported feature'],['keep','Keep current root']],'root');state.save.textContent='Review import';
    state.save.onclick=async()=>{if(state.busy)return;try{const selected=file.files?.[0];if(!selected)throw new Error('Choose an STL or PLY file.');if(selected.size>33554432)throw new Error('The mesh exceeds the 32 MiB import payload bound.');const step=numeric(spacing.value);if(step<=0)throw new Error('Sampling must be positive.');const id=nodeIdentifier(name.value);state.busy=true;state.save.disabled=state.close.disabled=true;state.status.textContent='Reading mesh…';const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('The mesh file could not be read.'));reader.readAsDataURL(selected);});state.node.close();await window.ImplexityAdvancedCommands.open('import_mesh_geometry',{filename:selected.name,data_base64:encoded,units:units.value,spacing_mm:step,feature_id:id,make_root:root.value==='root',expected_model:state.expected});}catch(error){state.status.textContent=error.message;}finally{state.busy=false;state.save.disabled=state.close.disabled=false;}};state.node.showModal();
  }
  const toolbar=element('div',undefined,document.getElementById('grapheditbar')?.parentElement);toolbar.className='pm-grid';toolbar.id='implicitCadTools';
  const kinds=[['profile.rectangle','Rectangle profile'],['profile.circle','Circle profile'],['profile.polygon','Polygon profile'],['extrude','Extrude profile'],['revolve','Revolve profile'],['loft','Loft profiles'],['sweep.tube','Sweep circular tube'],['reflect','Reflect geometry']];const operation=select(toolbar,'Implicit CAD feature',kinds,'profile.rectangle');const addFeature=element('button','Add feature…',toolbar);addFeature.type='button';addFeature.onclick=()=>feature(operation.value);const importButton=element('button','Import mesh…',toolbar);importButton.type='button';importButton.onclick=meshImport;
  window.ImplexityParametric={feature,parameter,meshImport};
  document.getElementById('graphfeatureedit')?.addEventListener('click',()=>{const node=S.byId.get(S.sel);if(node)feature(node.kind,node.id);});
  document.getElementById('paramcreate')?.addEventListener('click',()=>parameter());
  };
  if(window.S&&window.ImplexityParametricHost)initialize();
  else window.addEventListener('implexity-parametric-ready',initialize,{once:true});
})();
