// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use implexity_core::{CaeError,CaeResult};
use implexity_linalg::sparse::CsrMatrix;
use implexity_solve::{multirate_coupling::{CouplingMode,FluxDrivenField,MultirateOptions,MultirateStepper,SubcycledField},time_stepper::{StepParameters,TimeStepper}};
use crate::interface::FluidField;
use super::{contact_field::ContactField,contact_set_kinematics::ContactSetKinematics,separate_body::{MovingFsiPairModel,PairSolidField},resources::PersistentContactFields,history_branch::{ContactHistoryBranch,ContactOwnerIdentity},macro_control::{avf_admission::AvfVelocityCertificate,phase_subdivision::{advance_constant_flux_phases,PhaseHistory},selected_transition::OnsetPolicy}};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
pub struct LoosePhaseState{pub solid:Vec<f64>,pub fluid:Vec<f64>,pub trace_lags:Vec<f64>,pub origin_s:f64,pub branch:ContactHistoryBranch,pub velocity_certificate:Option<AvfVelocityCertificate>,pub cumulative_work_defect_j:f64,pub cumulative_abs_body_work_j:f64}
pub struct LoosePhaseOutput{pub state:LoosePhaseState,pub phases:PhaseHistory,pub fluid_samples:Vec<f64>,pub fluid_ledger:std::collections::BTreeMap<String,f64>,pub fluid_diagnostics:implexity_solve::time_stepper::StepDiagnostics,pub predicted_trace:Vec<f64>,pub transmitted_force_n:Vec<f64>,pub fluid_interface_work_j:f64,pub body_interface_work_j:f64,pub interface_work_defect_j:f64,pub relative_cumulative_work_defect:Option<f64>,pub terminal_work_admission:Option<bool>,pub terminal_work_admission_error:Option<String>}
pub struct LoosePhaseDriver<'f,'m,L:ContactSetKinematics>{stepper:MultirateStepper<&'f FluidField,&'f ContactField<PairSolidField<'m>,L>>,owner:ContactOwnerIdentity,velocity:CsrMatrix,policy:OnsetPolicy,subdivisions:usize,energy_scale_j:Option<f64>,work_action_record:bool,dt:f64,horizon:usize}
impl<'f,'m,L:ContactSetKinematics> LoosePhaseDriver<'f,'m,L>{
 pub fn new(model:&MovingFsiPairModel,fields:&'f PersistentContactFields<'m,L>,design:&[f64],features:&serde_json::Value,source_graph:&str,policy:OnsetPolicy,subdivisions:usize)->CaeResult<Self>{
  let _=model.fixed_horizon_autonomous()?;let a=model.native_body(0)?;let b=model.native_body(1)?;let c=&a.problem.coupling;let energy_scale_j=c.energy_scale_j;
  if !matches!(c.mode,CouplingMode::Loose{..})||!subdivisions.is_power_of_two()||subdivisions>16||a.problem.time.macro_step_s().to_bits()!=b.problem.time.macro_step_s().to_bits()||a.problem.time.history_steps()!=b.problem.time.history_steps()||energy_scale_j.is_some_and(|x|!x.is_finite()||x<=0.){return Err(fail("canonical loose phase authored mode, cadence, subdivision or energy scale"));}
  for i in 0..2{if !std::ptr::eq(fields.contact.native().body_field(i)?.core().model(),&model.native_body(i)?.soft){return Err(fail("canonical loose phase borrowed native model identity differs"));}}let velocity=super::contact_set::native_velocity_trace_from_pair(model,fields.contact.native(),design,1.,fields.contact.law().contact_count())?;let features=fields.contact.law().bound_owner_features(features)?;let owner=ContactOwnerIdentity::new(&features,source_graph,design,1.,0.,policy)?;
  let stepper=MultirateStepper::new(&fields.fluid,&fields.contact,MultirateOptions{mode:c.mode.clone(),schur_ratio_limit:c.schur_ratio_limit,work_defect_limit:c.work_defect_limit})?.with_identity(format!("canonical_loose_contact_phase:{}:{}",model.identity(),implexity_core::json::canonical_sha256(&serde_json::json!({"features":features,"source_graph":source_graph,"subdivisions":subdivisions,"policy":{"residual_tolerance_bits":format!("{:016x}",policy.residual_tolerance.to_bits()),"maximum_newton_iterations":policy.maximum_newton_iterations,"maximum_active_set_iterations":policy.maximum_active_set_iterations,"gap_target_fraction_bits":format!("{:016x}",policy.gap_target_fraction.to_bits()),"normal_velocity_tolerance_bits":format!("{:016x}",policy.normal_velocity_tolerance_m_s.to_bits())}})))).with_field_newton(c.field_newton)?.with_linear_solves(c.linear_solves)?.with_step_cache_bytes(c.step_cache_bytes);
  if velocity.ncols()!=stepper.field_b().state_size()||velocity.nrows()!=stepper.field_a().trace_size(){return Err(fail("canonical loose phase native velocity trace shape"));}
  Ok(Self{stepper,owner,velocity,policy,subdivisions,energy_scale_j,work_action_record:c.work_defect_action_record,dt:a.problem.time.macro_step_s(),horizon:a.problem.time.history_steps()})
 }
 pub fn initial_state(&self,design:&[f64])->CaeResult<LoosePhaseState>{
  let z=self.stepper.initial_state(design)?;let l=self.stepper.layout();let solid=z[l.field_b].to_vec();if self.velocity.matvec(&solid).map_err(|e|fail(&e.to_string()))?.iter().any(|v|*v!=0.){return Err(fail("canonical loose phase initial selected branch requires exact native rest velocity"));}self.stepper.field_b().check_state_domain(1,&solid,&solid,StepParameters{design,time_scale:1.})?;let count=self.stepper.field_b().law().contact_count();if solid[solid.len()-count..].iter().any(|v|*v!=0.){return Err(fail("canonical loose phase initial selected branch requires zero native multipliers"));}let branch=ContactHistoryBranch::from_selected(&self.owner,&vec![false;count],self.policy.residual_tolerance*self.policy.gap_target_fraction)?;
  Ok(LoosePhaseState{solid,fluid:z[l.field_a].to_vec(),trace_lags:z[l.lags].to_vec(),origin_s:0.,branch,velocity_certificate:None,cumulative_work_defect_j:0.,cumulative_abs_body_work_j:0.})
 }

 pub fn admit_native_interface(&self,model:&MovingFsiPairModel,design:&[f64])->CaeResult<serde_json::Value>{
  use implexity_solve::{matrix::Jacobian,factorization::Factorization,local_condensation::LocalEliminationPartition};
  let state=self.initial_state(design)?;let field=self.stepper.field_b();let native=field.native();let p=StepParameters{design,time_scale:1.};let native_size=native.state_size();let predicted=native.predict(1,&state.solid[..native_size],None,p);native.check_state_domain(1,&predicted,&state.solid[..native_size],p)?;let zero_flux=vec![0.;native.trace_operator().nrows()];let(current,flux)=native.current_flux_jacobians(1,&predicted,&state.solid[..native_size],&zero_flux,p)?;let(Jacobian::Csr(current),Jacobian::Csr(flux))=(current,flux)else{return Err(fail("canonical loose native Schur requires current and flux CSR owners"));};
  let partition=native.local_elimination_groups()?.map(|g|LocalEliminationPartition::new(native_size,g)).transpose().map_err(|e|fail(&e.to_string()))?;let factor=Factorization::correction_with_partition(Jacobian::Csr(current),native_size,None,partition.as_ref())?;
  let mut masses=Vec::new();let mut layouts=Vec::new();let mut factors=Vec::new();let mut free=vec![false;field.state_size()];let(mut state_offset,mut design_offset,mut force_offset)=(0,0,0);let mut modes=Vec::new();
  for b in 0..2{let body=field.native().body_field(b)?;let native=model.native_body(b)?;if !std::ptr::eq(body.core().model(),&native.soft){return Err(fail("canonical loose Schur model/resource identity"));}let nd=body.design_size();let h=body.core().history(StepParameters{design:&design[design_offset..design_offset+nd],time_scale:1.})?;let coefficient=crate::run::inertia_coefficient(h.scheme);if coefficient<=0.||!coefficient.is_finite(){return Err(fail("canonical loose Schur requires native inertial body schemes"));}let n3=h.layout.n3;let u=state_offset+h.layout.u();let mut row=vec![0.;n3];for i in 0..n3{let(js,vs)=flux.row(u+i);if let Some(j)=js.iter().position(|j|*j==force_offset+i){row[i]=-vs[j];}free[u+i]=row[i]!=0.&&!native.soft.fixed[i];}
   for m in 0..native.problem.coupling.preflight_modes{let mut v=vec![0.;field.state_size()];for(node,x)in native.soft.mesh.points.iter().enumerate(){let i=3*node+m%3;if free[u+i]{v[u+i]=1.+(m/3)as f64*(x[0]+x[1]+x[2]);}}modes.push(v);}
   masses.push(h.mass_matrix().clone());layouts.push((u,n3));factors.push(row.into_iter().map(|r|r*coefficient/(self.dt*self.dt)).collect::<Vec<_>>());state_offset+=body.state_size();design_offset+=nd;force_offset+=body.trace_operator().nrows();
  }
  let mass_action=|phi:&[f64]|{let mut out=vec![0.;field.state_size()];for b in 0..2{let(u,n3)=layouts[b];let mu=masses[b].matvec(&phi[u..u+n3]).unwrap_or_else(|_|vec![f64::NAN;n3]);for i in 0..n3{out[u+i]=factors[b][i]*mu[i];}}out};let mut max_residual=0_f64;
  for _ in 0..8{let mut next=Vec::new();for phi in &modes{let(x,_,residual)=factor.solve(&mass_action(phi)[..native_size],false)?;max_residual=max_residual.max(residual);let mut v=vec![0.;field.state_size()];for i in 0..v.len(){if free[i]{v[i]=x[i];}}next.push(v);}let mut ortho:Vec<Vec<f64>>=Vec::new();for mut v in next{for q in &ortho{let mq=mass_action(q);let projection=v.iter().zip(mq).map(|(a,b)|a*b).sum::<f64>();for(a,b)in v.iter_mut().zip(q){*a-=projection*b;}}let norm=v.iter().zip(mass_action(&v)).map(|(a,b)|a*b).sum::<f64>().abs().sqrt();if norm>0.&&norm.is_finite(){for a in &mut v{*a/=norm;}ortho.push(v);}}if ortho.is_empty(){return Err(fail("canonical loose Schur has no free native inertial modes"));}modes=ortho;}
  let ratios=self.admit_interface(design,&state,&modes,&mass_action)?;Ok(serde_json::json!({"schema":"two-native-body-canonical-schur-preflight/1","ratios":ratios,"limit":model.native_body(0)?.problem.coupling.schur_ratio_limit,"mode":"loose","modes":modes.len(),"mode_policy":"authored preflight_modes per independent native body; original eight inertia subspace iterations","maximum_original_current_residual":max_residual,"mass_owner":"native solid integrator history, residual-scaled inertia; unconstrained native body modes embedded with zero multipliers","primal_correction_condition_limit":null,"ordinary_closed_derivative_admission":false,"contact_current_origin_selection":"not used for body-mode factorization","body_mode_scope":"original native inertial mode preflight; not unilateral contact compliance"}))
 }
 pub fn admit_interface(&self,design:&[f64],state:&LoosePhaseState,modes:&[Vec<f64>],mass_action:&dyn Fn(&[f64])->Vec<f64>)->CaeResult<Vec<f64>>{self.stepper.interface_schur_ratio(design,&self.pack(state)?,modes,mass_action)}
 fn pack(&self,z:&LoosePhaseState)->CaeResult<Vec<f64>>{let l=self.stepper.layout();if z.solid.len()!=l.field_b.len()||z.fluid.len()!=l.field_a.len()||z.trace_lags.len()!=l.lags.len()||!z.origin_s.is_finite()||!z.cumulative_work_defect_j.is_finite()||!z.cumulative_abs_body_work_j.is_finite()||z.cumulative_abs_body_work_j<0.||z.solid.iter().chain(&z.fluid).chain(&z.trace_lags).any(|x|!x.is_finite()){return Err(fail("canonical loose phase full state/trace history shape"));}let mut x=z.solid.clone();x.extend(&z.fluid);x.extend(&z.trace_lags);Ok(x)}
 pub fn advance(&self,n:usize,previous:&LoosePhaseState,design:&[f64],external:&[f64])->CaeResult<LoosePhaseOutput>{
  let field=self.stepper.field_b();let p=StepParameters{design,time_scale:1.};if n==0||n>self.horizon||previous.origin_s.to_bits()!=((n-1)as f64*self.dt).to_bits()||external.len()!=field.trace_operator().nrows()||external.iter().any(|v|!v.is_finite()){return Err(fail("canonical loose phase macro index or external force"));}
  let owner=self.owner.for_phase(1.,previous.origin_s)?;owner.check_parameters(design,1.,self.policy)?;previous.branch.check_binding(&owner,field.law().contact_count(),self.policy.residual_tolerance*self.policy.gap_target_fraction)?;
  let packed=self.pack(previous)?;let predicted=self.stepper.admitted_loose_prediction(&packed,p)?;let start=field.trace_operator().matvec(&previous.solid).map_err(|e|fail(&e.to_string()))?;let mut direction=vec![0.;previous.solid.len()];let mut used=vec![false;direction.len()];
  for i in 0..start.len(){let(cols,values)=field.trace_operator().row(i);if cols.len()!=1||values.len()!=1||values[0]==0.||!values[0].is_finite()||used[cols[0]]{return Err(fail("canonical loose phase requires an injective native nodal trace"));}used[cols[0]]=true;direction[cols[0]]=(predicted[i]-start[i])/values[0];}
  if field.admissible_step(n,&previous.solid,&direction,&previous.solid,p,1.)?<1.{return Err(fail("canonical loose predictor whole contact path refused"));}
  let(predicted_trace,trace_lags,fluid)=self.stepper.prepare_admitted_loose_subcycle(n,&packed,p)?;let force:Vec<_>=fluid.flux.iter().zip(external).map(|(a,b)|a+b).collect();let mut observe=|_:&super::macro_control::phase_subdivision::PhaseRecord|Ok(());
  let phases=advance_constant_flux_phases(field,&previous.solid,&force,p,&self.velocity,self.policy,&previous.branch,&owner,previous.origin_s,self.subdivisions,&mut observe,previous.velocity_certificate.as_ref())?;
  let end=field.trace_operator().matvec(&phases.final_state).map_err(|e|fail(&e.to_string()))?;let work=fluid.flux.iter().zip(end.iter().zip(&start)).map(|(f,(a,b))|f*(a-b)).sum::<f64>();let defect=fluid.pairing-work;let cumulative=previous.cumulative_work_defect_j+defect;let absolute_work=previous.cumulative_abs_body_work_j+work.abs();let energy_scale=self.energy_scale_j.unwrap_or(absolute_work);if !absolute_work.is_finite()||!cumulative.is_finite(){return Err(fail("canonical loose phase cumulative work must be finite"));}let relative=(energy_scale>0.).then(||cumulative.abs()/energy_scale);let(mut admission,mut admission_error)=(None,None);if n==self.horizon&&energy_scale>0.{match self.stepper.admit_work_defect(cumulative,energy_scale){Ok(_)=>admission=Some(true),Err(e)if self.work_action_record=>{admission=Some(false);admission_error=Some(e.to_string());},Err(e)=>return Err(e)}}let origin=n as f64*self.dt;let next_owner=self.owner.for_phase(1.,origin)?;let branch=ContactHistoryBranch::from_selected(&next_owner,&phases.final_branch.selected(),self.policy.residual_tolerance*self.policy.gap_target_fraction)?;
  let certificate_branch=ContactHistoryBranch::from_selected(&self.owner.for_phase(1./self.subdivisions as f64,origin)?,&phases.final_branch.selected(),self.policy.residual_tolerance*self.policy.gap_target_fraction)?;let certificate=phases.velocity_certificate.clone().bind_phase_endpoint(certificate_branch,&phases.final_state)?;
  let state=LoosePhaseState{solid:phases.final_state.clone(),fluid:fluid.state,trace_lags,origin_s:origin,branch,velocity_certificate:Some(certificate),cumulative_work_defect_j:cumulative,cumulative_abs_body_work_j:absolute_work};
  Ok(LoosePhaseOutput{state,phases,fluid_samples:fluid.samples,fluid_ledger:fluid.ledger,fluid_diagnostics:fluid.diagnostics,predicted_trace,transmitted_force_n:fluid.flux,fluid_interface_work_j:fluid.pairing,body_interface_work_j:work,interface_work_defect_j:defect,relative_cumulative_work_defect:relative,terminal_work_admission:admission,terminal_work_admission_error:admission_error})
 }
}
