// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use implexity_core::{CaeError,CaeResult};
use implexity_solve::{multirate_coupling::{FluxDrivenField,SubcycledField},time_stepper::StepParameters};
use implexity_physics_lbm::moving::field::event_trace::EventTickTrace;
use crate::moving_contact::mapped_pair_law::MappedPairLaw;
use crate::moving_contact::{resources::PersistentContactFields,collection::MultipleContact,history_branch::{ContactHistoryBranch,ContactOwnerIdentity},selected_transition::{OnsetPolicy,solve_contact_history_transition}};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
fn dot(a:&[f64],b:&[f64])->f64{a.iter().zip(b).map(|(a,b)|a*b).sum()}
pub struct MultiContactNativeState{pub solid:Vec<f64>,pub fluid:Vec<f64>,pub lagged_force_n:Vec<f64>,pub origin_s:f64,pub branch:ContactHistoryBranch}
pub struct MultiContactNativeTick{pub state:MultiContactNativeState,pub selected_closed:Vec<bool>,pub scaled_gaps:Vec<f64>,pub normal_velocities_m_s:Vec<f64>,pub original_residual_inf:f64,pub newton_iterations:usize,pub minimum_population:f64,pub samples:Vec<f64>,pub body_lagged_work_j:f64,pub external_body_work_j:f64,pub fluid_reaction_work_j:f64,pub lagged_work_defect_j:f64}
fn unpack(fields:&PersistentContactFields<'_,MultipleContact<MappedPairLaw>>,state:&[f64],design:&[f64],scale:f64)->CaeResult<(Vec<f64>,Vec<f64>)>{let(mut u,mut v)=(vec![],vec![]);let(mut offset,mut design_offset)=(0,0);for b in 0..2{let field=fields.contact.native().body_field(b)?;let n=field.state_size();let nd=field.design_size();if offset+n>state.len()||design_offset+nd>design.len(){return Err(fail("multi native body layout"));}let history=field.core().history(StepParameters{design:&design[design_offset..design_offset+nd],time_scale:scale})?;let physical=field.core().to_physical(&state[offset..offset+n]);let layout=&history.layout;u.extend_from_slice(&physical[layout.u()..layout.u()+layout.n3]);v.extend_from_slice(&physical[layout.v()..layout.v()+layout.n3]);offset+=n;design_offset+=nd;}if offset!=fields.contact.law().native_states()||design_offset!=design.len(){return Err(fail("multi native body prefix identity"));}Ok((u,v))}
pub fn advance_native_tick(fields:&PersistentContactFields<'_,MultipleContact<MappedPairLaw>>,previous:&MultiContactNativeState,design:&[f64],external_force_n:&[f64],sample_tick:usize,owner:&ContactOwnerIdentity,velocity_trace:&implexity_linalg::sparse::CsrMatrix,policy:OnsetPolicy)->CaeResult<MultiContactNativeTick>{let field=&fields.contact;let fluid=&fields.fluid;let nf=field.trace_operator().nrows();let dt=fluid.inner().nominal_fluid_step_s();let scale=dt/field.nominal_step_s();if !previous.origin_s.is_finite()||previous.solid.len()!=field.state_size()||previous.fluid.len()!=fluid.state_size()||previous.lagged_force_n.len()!=nf||external_force_n.len()!=nf||previous.solid.iter().chain(&previous.fluid).chain(&previous.lagged_force_n).chain(external_force_n).any(|v|!v.is_finite()){return Err(fail("multi native full state/force shape"));}owner.check_clock(previous.origin_s)?;let force:Vec<_>=previous.lagged_force_n.iter().zip(external_force_n).map(|(a,b)|a+b).collect();let params=StepParameters{design,time_scale:scale};let(result,next_branch)=solve_contact_history_transition(field,&previous.solid,&force,params,velocity_trace,policy,&previous.branch,owner)?;let(u0,v0)=unpack(fields,&previous.solid,design,scale)?;let(u1,v1)=unpack(fields,&result.state,design,scale)?;let um:Vec<_>=u0.iter().zip(&u1).map(|(a,b)|0.5*(a+b)).collect();let vm:Vec<_>=v0.iter().zip(&v1).map(|(a,b)|0.5*(a+b)).collect();let tick=fluid.event_tick(&previous.fluid,design,EventTickTrace{origin_s:previous.origin_s,event_s:previous.origin_s+0.5*dt,sample_tick,start:&u0,before_midpoint:&um,after_midpoint:&um,end:&u1,before_velocity_m_s:&vm,after_velocity_m_s:&vm})?;let reaction:Vec<_>=(0..nf).map(|i|tick.before_impulse_n_s[i]+tick.after_impulse_n_s[i]+tick.start_compensation_impulse_n_s[i]+tick.end_compensation_impulse_n_s[i]).collect();let lag:Vec<_>=reaction.iter().map(|v|v/dt).collect();let du:Vec<_>=u1.iter().zip(&u0).map(|(a,b)|a-b).collect();let body_work=dot(&previous.lagged_force_n,&du);let external_work=dot(external_force_n,&du);let fluid_work=dot(&tick.before_impulse_n_s,&vm)+dot(&tick.after_impulse_n_s,&vm)+dot(&tick.start_compensation_impulse_n_s,&v0)+dot(&tick.end_compensation_impulse_n_s,&v1);if !body_work.is_finite()||!external_work.is_finite()||!fluid_work.is_finite(){return Err(fail("multi native work overflow"));}Ok(MultiContactNativeTick{state:MultiContactNativeState{solid:result.state,fluid:tick.state,lagged_force_n:lag,origin_s:previous.origin_s+dt,branch:next_branch},selected_closed:result.active,scaled_gaps:result.scaled_gaps,normal_velocities_m_s:result.normal_velocities_m_s,original_residual_inf:result.original_residual_norm,newton_iterations:result.iterations,minimum_population:tick.minimum_population,samples:tick.samples,body_lagged_work_j:body_work,external_body_work_j:external_work,fluid_reaction_work_j:fluid_work,lagged_work_defect_j:body_work-fluid_work})}
