// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use std::{collections::BTreeMap,sync::Mutex};
use implexity_core::{CaeError,CaeResult};
use implexity_linalg::dense::DenseMatrix;
use implexity_solve::{time_stepper::{TimeStepper,StepParameters,StepRecord,StepDiagnostics,StepTangent,StepCotangent},multirate_coupling::{FluxDrivenField,SubcycledField}};
use super::{separate_body::{MovingFsiPairModel,MovingEventHistory,PairEventContext},event_step::{EventAdvancePolicy,EventTickState,EventTickStateDirection},sample_projection::PairSampleProjection};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
pub struct EventMacroStepper<'a>{model:&'a MovingFsiPairModel,context:PairEventContext<'a>,policy:EventAdvancePolicy,projection:PairSampleProjection,origin_s:f64,sizes:[usize;3],external:Vec<f64>,identity:String,local_stats:Mutex<Option<serde_json::Value>>}
impl<'a> EventMacroStepper<'a>{
 pub fn new(model:&'a MovingFsiPairModel,policy:EventAdvancePolicy,projection:PairSampleProjection,origin_s:f64)->CaeResult<Self>{let context=PairEventContext::new(model,policy)?;let solid=context.contact_field()?;let fluid=context.event_fluid_field(policy)?;let mut names=context.solid_field()?.sample_names().to_vec();names.extend(fluid.sample_names().iter().cloned());if names!=projection.source_names()||!origin_s.is_finite()||origin_s<0.{return Err(fail("event macro projection/clock"));}let sizes=[solid.state_size(),fluid.state_size(),solid.trace_operator().nrows()];let identity=implexity_core::json::canonical_sha256(&serde_json::json!({"model":model.identity(),"policy":{"restitution":policy.restitution,"maintained_gap_target_fraction":policy.maintained_gap_target_fraction,"residual_tolerance":policy.residual_tolerance,"maximum_newton_iterations":policy.maximum_newton_iterations,"maximum_localization_iterations":policy.maximum_localization_iterations,"interpolation_kernel":format!("{:?}",policy.interpolation_kernel),"impact":{"event_gap_m":policy.impact.event_gap_m,"normal_velocity_m_s":policy.impact.normal_velocity_m_s,"impulse_n_s":policy.impact.impulse_n_s,"momentum_n_s":policy.impact.momentum_n_s,"energy_j":policy.impact.energy_j}},"projection":projection.to_value(),"origin_s":origin_s,"state_order":["solid","fluid","lagged_force_n","origin_s"]}));Ok(Self{model,context,policy,projection,origin_s,sizes,external:vec![0.;sizes[2]],identity,local_stats:Mutex::new(None)})}
 pub fn with_external_force(mut self,f:Vec<f64>)->CaeResult<Self>{if f.len()!=self.sizes[2]||f.iter().any(|v|!v.is_finite()){return Err(fail("event macro external force shape"));}self.identity=implexity_core::json::canonical_sha256(&serde_json::json!({"base":self.identity,"external_force_n":f}));self.external=f;Ok(self)}
 pub fn pack(&self,s:&EventTickState)->CaeResult<Vec<f64>>{if [s.solid.len(),s.fluid.len(),s.lagged_force_n.len()]!=self.sizes||s.solid.iter().chain(&s.fluid).chain(&s.lagged_force_n).any(|v|!v.is_finite())||!s.origin_s.is_finite(){return Err(fail("event macro state layout"));}let mut z=s.solid.clone();z.extend_from_slice(&s.fluid);z.extend_from_slice(&s.lagged_force_n);z.push(s.origin_s);Ok(z)}
 pub fn unpack(&self,z:&[f64])->CaeResult<EventTickState>{if z.len()!=self.state_size()||z.iter().any(|v|!v.is_finite()){return Err(fail("event macro state vector"));}let a=self.sizes[0];let b=a+self.sizes[1];let c=b+self.sizes[2];Ok(EventTickState{solid:z[..a].to_vec(),fluid:z[a..b].to_vec(),lagged_force_n:z[b..c].to_vec(),origin_s:z[c]})}
 pub fn local_checkpoint_stats(&self)->Option<serde_json::Value>{self.local_stats.lock().ok().and_then(|s|s.clone())}
 fn tick_history(&self,z:&[f64],p:StepParameters<'_>)->CaeResult<implexity_solve::checkpointed_history::HistoryRun>{if p.time_scale!=1.{return Err(fail("event macro supports fixed authored grid only"));}let stepper=LocalEventTickStepper::new(self)?;implexity_solve::checkpointed_history::run_history(&stepper,p,z,1,Some(self.model.native_body(0)?.problem.coupling.substeps),None,self.model.native_body(0)?.problem.time.checkpoint.clone(),&implexity_solve::state_store::StoreBudget::from_environment()?)}
 fn record_local_stats(&self,n:usize,run:&implexity_solve::checkpointed_history::HistoryRun){if let Ok(mut out)=self.local_stats.lock(){*out=Some(serde_json::json!({"macro_index":n,"native_ticks":run.steps(),"recomputed_ticks":run.stats().recomputed_steps,"peak_snapshot_bytes":run.stats().peak_snapshot_bytes,"authored_policy":format!("{:?}",self.model.native_body(0).unwrap().problem.time.checkpoint)}));}}

 fn block(&self,n:usize,z:&[f64],p:StepParameters<'_>)->CaeResult<(MovingEventHistory,Vec<Vec<f64>>)>{if n==0||p.time_scale!=1.{return Err(fail("event macro supports fixed authored time grid only"));}let m=self.model.native_body(0)?.problem.coupling.substeps;let ticks:Vec<_>=(1..=m).collect();let force=vec![self.external.clone();m];Ok((self.context.advance_event_history(&self.unpack(z)?,p.design,&force,&ticks,self.policy)?,force))}
 fn end(&self,h:&MovingEventHistory)->CaeResult<Vec<f64>>{self.pack(&h.outputs.last().ok_or_else(||fail("event macro empty block"))?.state)}
}
impl TimeStepper for EventMacroStepper<'_>{
 fn identity(&self)->&str{&self.identity}fn state_size(&self)->usize{self.sizes.iter().sum::<usize>()+1}fn design_size(&self)->usize{self.model.native_body(0).unwrap().chain.len()+self.model.native_body(1).unwrap().chain.len()}fn sample_names(&self)->&[String]{self.projection.names()}fn nominal_step_s(&self)->f64{self.model.native_body(0).unwrap().problem.time.macro_step_s()}
 fn initial_state(&self,d:&[f64])->CaeResult<Vec<f64>>{let solid=self.context.contact_field()?.initial_state(d)?;let fluid=self.context.event_fluid_field(self.policy)?.initial_state(d)?;self.pack(&EventTickState{solid,fluid,lagged_force_n:vec![0.;self.sizes[2]],origin_s:self.origin_s})}
 fn initial_state_vjp(&self,d:&[f64],b:&[f64])->CaeResult<Vec<f64>>{let b=self.unpack(b)?;let mut s=self.context.contact_field()?.initial_state_vjp(d,&b.solid)?;let f=self.context.event_fluid_field(self.policy)?.initial_state_vjp(d,&b.fluid)?;for(a,v)in s.iter_mut().zip(f){*a+=v;}Ok(s)}
 fn advance(&self,n:usize,z:&[f64],p:StepParameters<'_>)->CaeResult<StepRecord>{if n==0{return Err(fail("event macro index zero"));}let run=self.tick_history(z,p)?;let field=self.context.solid_field()?;let fluid=self.context.event_fluid_field(self.policy)?;let old=self.unpack(z)?;let end=self.unpack(run.final_state())?;let mut y=field.samples(n,&end.solid[..field.state_size()],&old.solid[..field.state_size()],p)?;let mut f=vec![0.;fluid.sample_names().len()];for r in 0..run.samples().nrows{for(j,v)in f.iter_mut().enumerate(){*v+=run.samples().data[r*run.samples().ncols+j];}}y.extend(f);self.record_local_stats(n,&run);Ok(StepRecord{state:run.final_state().to_vec(),samples:self.projection.values(&y)?,ledger:BTreeMap::new(),diagnostics:StepDiagnostics::default()})}
 fn tangent(&self,_:usize,_:&[f64],_:&[f64],_:StepParameters<'_>,_:&[f64],_:Option<&[f64]>,_:f64)->CaeResult<StepTangent>{Err(fail("event macro forward tangent unavailable; native event directions remain separate"))}
 fn adjoint(&self,n:usize,z:&[f64],c:&[f64],p:StepParameters<'_>,s:&[f64],b:&[f64])->CaeResult<StepCotangent>{let mut x=self.adjoint_many(n,z,c,p,&[s.to_vec()],&[b.to_vec()])?;Ok(x.remove(0))}
 fn adjoint_many(&self,n:usize,z:&[f64],c:&[f64],p:StepParameters<'_>,s:&[Vec<f64>],b:&[Vec<f64>])->CaeResult<Vec<StepCotangent>>{if n==0||s.len()!=b.len(){return Err(fail("event macro cotangent batch/index"));}let run=self.tick_history(z,p)?;if run.final_state().len()!=c.len()||run.final_state().iter().zip(c).any(|(a,b)|a.to_bits()!=b.to_bits()){return Err(fail("event macro endpoint replay differs bitwise"));}let field=self.context.solid_field()?;let fluid=self.context.event_fluid_field(self.policy)?;let ns=field.sample_names().len();let nf=fluid.sample_names().len();let old=self.unpack(z)?;let end=self.unpack(c)?;let(mut sample_bars,mut terminal_bars,mut previous_bars,mut direct)=(vec![],vec![],vec![],vec![]);for(s,b)in s.iter().zip(b){let source=self.projection.pullback(b)?;if source.len()!=ns+nf{return Err(fail("event macro source cotangent layout"));}let(cbar,obar,dbar)=field.samples_vjp(n,&end.solid[..field.state_size()],&old.solid[..field.state_size()],p,&source[..ns])?;let mut terminal=self.unpack(s)?;for(a,b)in terminal.solid.iter_mut().zip(cbar){*a+=b;}terminal_bars.push(self.pack(&terminal)?);previous_bars.push(obar);direct.push(dbar);let mut cb=DenseMatrix::zeros(run.steps(),nf);for r in 0..run.steps(){cb.data[r*nf..(r+1)*nf].copy_from_slice(&source[ns..]);}sample_bars.push(cb);}let tick=LocalEventTickStepper::new(self)?;let result=implexity_solve::checkpointed_history::history_adjoint_many(&tick,p,&run,&sample_bars,&terminal_bars)?;let mut out=vec![];for((g,old),direct)in result.into_iter().zip(previous_bars).zip(direct){let mut previous=self.unpack(&g.initial_state)?;for(a,b)in previous.solid.iter_mut().zip(old){*a+=b;}let mut design=g.design;for(a,b)in design.iter_mut().zip(direct){*a+=b;}out.push(StepCotangent{previous:self.pack(&previous)?,design,time_scale:0.});}self.record_local_stats(n,&run);Ok(out)}
}

struct LocalEventTickStepper<'b,'a>{parent:&'b EventMacroStepper<'a>,identity:String}
impl<'b,'a> LocalEventTickStepper<'b,'a>{fn new(parent:&'b EventMacroStepper<'a>)->CaeResult<Self>{Ok(Self{parent,identity:implexity_core::json::canonical_sha256(&serde_json::json!({"parent":parent.identity(),"kind":"native_event_fluid_tick","policy":"authored_online_snapshots"}))})}}
impl TimeStepper for LocalEventTickStepper<'_,'_>{
 fn identity(&self)->&str{&self.identity}fn state_size(&self)->usize{self.parent.state_size()}fn design_size(&self)->usize{self.parent.design_size()}fn sample_names(&self)->&[String]{self.parent.context.event_fluid_field(self.parent.policy).unwrap().sample_names()}fn nominal_step_s(&self)->f64{self.parent.context.event_fluid_field(self.parent.policy).unwrap().inner().nominal_fluid_step_s()}
 fn initial_state(&self,d:&[f64])->CaeResult<Vec<f64>>{self.parent.initial_state(d)}fn initial_state_vjp(&self,d:&[f64],b:&[f64])->CaeResult<Vec<f64>>{self.parent.initial_state_vjp(d,b)}
 fn advance(&self,n:usize,z:&[f64],p:StepParameters<'_>)->CaeResult<StepRecord>{if p.time_scale!=1.{return Err(fail("event native tick nominal grid only"));}let out=self.parent.context.event_tick_lagged(&self.parent.unpack(z)?,p.design,&self.parent.external,n,self.parent.policy)?;let mut samples=out.fluid_tick.samples;let fluid=self.parent.context.event_fluid_field(self.parent.policy)?;let na=fluid.inner().sample_names().len();let m=self.parent.model.native_body(0)?.problem.coupling.substeps;for v in &mut samples[na..]{*v*=1./m as f64;}Ok(StepRecord{state:self.parent.pack(&out.state)?,samples,ledger:BTreeMap::new(),diagnostics:StepDiagnostics::default()})}
 fn tangent(&self,_:usize,_:&[f64],_:&[f64],_:StepParameters<'_>,_:&[f64],_:Option<&[f64]>,_:f64)->CaeResult<StepTangent>{Err(fail("event local tick forward tangent unavailable"))}
 fn adjoint(&self,n:usize,z:&[f64],c:&[f64],p:StepParameters<'_>,s:&[f64],b:&[f64])->CaeResult<StepCotangent>{let mut out=self.adjoint_many(n,z,c,p,&[s.to_vec()],&[b.to_vec()])?;Ok(out.remove(0))}
 fn adjoint_many(&self,n:usize,z:&[f64],c:&[f64],p:StepParameters<'_>,s:&[Vec<f64>],b:&[Vec<f64>])->CaeResult<Vec<StepCotangent>>{if p.time_scale!=1.||s.len()!=b.len(){return Err(fail("event local tick cotangent nominal grid/batch"));}let previous=self.parent.unpack(z)?;let base=self.parent.context.event_tick_lagged(&previous,p.design,&self.parent.external,n,self.parent.policy)?;let end=self.parent.pack(&base.state)?;if end.len()!=c.len()||end.iter().zip(c).any(|(a,b)|a.to_bits()!=b.to_bits()){return Err(fail("event local tick endpoint replay differs bitwise"));}let fluid=self.parent.context.event_fluid_field(self.parent.policy)?;let na=fluid.inner().sample_names().len();let m=self.parent.model.native_body(0)?.problem.coupling.substeps;let mut out=vec![];for(s,b)in s.iter().zip(b){let state=self.parent.unpack(s)?;if b.len()!=base.fluid_tick.samples.len(){return Err(fail("event local sample cotangent layout"));}let mut samples=b.clone();for v in &mut samples[na..]{*v*=1./m as f64;}let bar=super::separate_body::MovingEventTickCotangent{state:EventTickStateDirection{solid:state.solid,fluid:state.fluid,lagged_force_n:state.lagged_force_n,origin_s:state.origin_s},event_time_s:0.,fluid_samples:samples};let g=self.parent.context.event_tick_lagged_adjoint(&previous,p.design,&self.parent.external,n,self.parent.policy,&base,&bar)?;out.push(StepCotangent{previous:self.parent.pack(&super::event_step::EventTickState{solid:g.state.solid,fluid:g.state.fluid,lagged_force_n:g.state.lagged_force_n,origin_s:g.state.origin_s})?,design:g.design,time_scale:0.});}Ok(out)}
}
