// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use implexity_core::{CaeError,CaeResult};
use serde_json::{Value,json};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
#[derive(Clone,Debug,PartialEq)]pub struct ContactOwnerIdentity{identity:String,descriptor:Value}
impl ContactOwnerIdentity{
 pub fn new(contact_features:&Value,source_graph_sha256:&str,design:&[f64],time_scale:f64,absolute_clock_s:f64,policy:crate::moving_contact::selected_transition::OnsetPolicy)->CaeResult<Self>{if !policy.residual_tolerance.is_finite()||policy.residual_tolerance<=0.||!policy.gap_target_fraction.is_finite()||!(0. ..=0.5).contains(&policy.gap_target_fraction)||!policy.normal_velocity_tolerance_m_s.is_finite()||policy.normal_velocity_tolerance_m_s<0.||policy.maximum_newton_iterations==0||policy.maximum_active_set_iterations==0||source_graph_sha256.len()!=64||!source_graph_sha256.bytes().all(|c|c.is_ascii_hexdigit())||!time_scale.is_finite()||time_scale<=0.||!absolute_clock_s.is_finite(){return Err(fail("contact history source/clock identity"));}let descriptor=json!({"contact_map_sha256":implexity_core::json::canonical_sha256(contact_features),"source_graph_sha256":source_graph_sha256,"design_sha256":state_digest(design)?,"time_scale_bits":format!("{:016x}",time_scale.to_bits()),"absolute_clock_bits":format!("{:016x}",absolute_clock_s.to_bits()),"policy":policy_value(policy)});Ok(Self{identity:implexity_core::json::canonical_sha256(&descriptor),descriptor})}
 pub fn for_phase(&self,time_scale:f64,absolute_clock_s:f64)->CaeResult<Self>{if !time_scale.is_finite()||time_scale<=0.||!absolute_clock_s.is_finite(){return Err(fail("contact phase parameter identity"));}let mut descriptor=self.descriptor.clone();descriptor["time_scale_bits"]=json!(format!("{:016x}",time_scale.to_bits()));descriptor["absolute_clock_bits"]=json!(format!("{:016x}",absolute_clock_s.to_bits()));Ok(Self{identity:implexity_core::json::canonical_sha256(&descriptor),descriptor})}
 pub fn advance_clock(&self,interval_s:f64)->CaeResult<Self>{if !interval_s.is_finite()||interval_s<=0.{return Err(fail("contact branch interval identity"));}let bits=u64::from_str_radix(self.descriptor["absolute_clock_bits"].as_str().unwrap(),16).map_err(|_|fail("contact clock bits"))?;let next=f64::from_bits(bits)+interval_s;if !next.is_finite(){return Err(fail("contact branch clock overflow"));}let mut descriptor=self.descriptor.clone();descriptor["absolute_clock_bits"]=json!(format!("{:016x}",next.to_bits()));Ok(Self{identity:implexity_core::json::canonical_sha256(&descriptor),descriptor})}
 pub fn check_clock(&self,clock_s:f64)->CaeResult<()>{if !clock_s.is_finite()||self.descriptor["absolute_clock_bits"]!=json!(format!("{:016x}",clock_s.to_bits())){return Err(fail("contact history actual clock identity mismatch"));}Ok(())}
 pub fn check_parameters(&self,design:&[f64],time_scale:f64,policy:crate::moving_contact::selected_transition::OnsetPolicy)->CaeResult<()>{if self.descriptor["design_sha256"]!=json!(state_digest(design)?)||self.descriptor["time_scale_bits"]!=json!(format!("{:016x}",time_scale.to_bits()))||self.descriptor["policy"]!=policy_value(policy){return Err(fail("contact history actual parameter identity mismatch"));}Ok(())}
}
fn policy_value(p:crate::moving_contact::selected_transition::OnsetPolicy)->Value{json!({"residual_tolerance_bits":format!("{:016x}",p.residual_tolerance.to_bits()),"maximum_newton_iterations":p.maximum_newton_iterations,"maximum_active_set_iterations":p.maximum_active_set_iterations,"gap_target_fraction_bits":format!("{:016x}",p.gap_target_fraction.to_bits()),"normal_velocity_tolerance_bits":format!("{:016x}",p.normal_velocity_tolerance_m_s.to_bits())})}
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum ContactBranch{Open,SelectedClosed}
#[derive(Clone,Debug)]pub struct ContactHistoryBranch{owner:ContactOwnerIdentity,branches:Vec<ContactBranch>,gap_target_bits:u64}
fn state_digest(state:&[f64])->CaeResult<String>{if state.iter().any(|v|!v.is_finite()){return Err(fail("contact checkpoint native state finite"));}let bytes:Vec<u8>=state.iter().flat_map(|v|v.to_bits().to_le_bytes()).collect();Ok(implexity_core::json::sha256_hex(&bytes))}
impl ContactHistoryBranch{
 pub fn from_selected(owner:&ContactOwnerIdentity,selected:&[bool],gap_target:f64)->CaeResult<Self>{if selected.is_empty()||!gap_target.is_finite()||gap_target<0.{return Err(fail("contact history branch identity/target"));}Ok(Self{owner:owner.clone(),branches:selected.iter().map(|v|if *v{ContactBranch::SelectedClosed}else{ContactBranch::Open}).collect(),gap_target_bits:gap_target.to_bits()})}
 pub fn check_binding(&self,owner:&ContactOwnerIdentity,contacts:usize,gap_target:f64)->CaeResult<()>{if self.owner!=*owner||self.branches.len()!=contacts||self.gap_target_bits!=gap_target.to_bits(){return Err(fail("contact history branch bound owner/width/target mismatch"));}Ok(())}
 pub fn selected(&self)->Vec<bool>{self.branches.iter().map(|v|*v==ContactBranch::SelectedClosed).collect()}
 pub fn checkpoint(&self,state:&[f64])->CaeResult<Value>{Ok(json!({"schema":"native-contact-history-branch/1","owner_identity":self.owner.identity,"owner_descriptor":self.owner.descriptor,"state_sha256":state_digest(state)?,"gap_target_bits":format!("{:016x}",self.gap_target_bits),"branches":self.branches.iter().map(|v|match v{ContactBranch::Open=>"open",ContactBranch::SelectedClosed=>"selected_closed"}).collect::<Vec<_>>()}))}
 pub fn restore(value:&Value,state:&[f64],owner:&ContactOwnerIdentity,contacts:usize,gap_target:f64)->CaeResult<Self>{let o=value.as_object().ok_or_else(||fail("contact checkpoint object"))?;if o.len()!=6||o.get("schema").and_then(Value::as_str)!=Some("native-contact-history-branch/1")||o.get("owner_identity").and_then(Value::as_str)!=Some(owner.identity.as_str())||o.get("owner_descriptor")!=Some(&owner.descriptor)||o.get("state_sha256").and_then(Value::as_str)!=Some(state_digest(state)?.as_str())||o.get("gap_target_bits").and_then(Value::as_str)!=Some(format!("{:016x}",gap_target.to_bits()).as_str()){return Err(fail("contact checkpoint source/design/policy/clock/state identity mismatch"));}let a=o.get("branches").and_then(Value::as_array).ok_or_else(||fail("contact checkpoint branch array"))?;if a.len()!=contacts{return Err(fail("contact checkpoint contact-set width"));}let selected=a.iter().map(|v|match v.as_str(){Some("open")=>Ok(false),Some("selected_closed")=>Ok(true),_=>Err(fail("contact checkpoint typed branch"))}).collect::<CaeResult<Vec<_>>>()?;Self::from_selected(owner,&selected,gap_target)}
}
