// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use implexity_core::{CaeError,CaeResult};
use implexity_solve::{multirate_coupling::FluxDrivenField,time_stepper::StepParameters};
use crate::moving_contact::mapped_pair_law::MappedPairLaw;
use crate::moving_contact::{resources::PersistentContactFields,collection::MultipleContact,coupled_tick_primal::MultiContactNativeState,phase_scheduler::PhaseTick,history_branch::{ContactOwnerIdentity,ContactHistoryBranch},selected_transition::OnsetPolicy,selected_derivative::{SelectedContactLinearization,SelectedContactDirection,selected_linearization,require_history_branch_preserved},segment_quadrature::{SegmentClock,SegmentTrace,SegmentDirection,SegmentOutput}};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
fn add(a:&mut[f64],b:&[f64],w:f64){for(a,b)in a.iter_mut().zip(b){*a+=w*b;}}
pub struct TickDirection{pub solid:Vec<f64>,pub fluid:Vec<f64>,pub lag:Vec<f64>,pub design:Vec<f64>,pub external:Vec<f64>,pub origin_s:f64}
pub struct TickOutputDirection{pub solid:Vec<f64>,pub fluid:Vec<f64>,pub lag:Vec<f64>,pub samples:Vec<f64>,pub origin_s:f64}
pub struct TickBars{pub solid:Vec<f64>,pub fluid:Vec<f64>,pub lag:Vec<f64>,pub design:Vec<f64>,pub external:Vec<f64>,pub origin_s:f64}
pub struct FixedPhaseLinearization{pub body:Vec<SelectedContactLinearization>,pub boundaries:Vec<f64>,pub start:Vec<f64>,pub end:Vec<f64>,pub midpoints:Vec<Vec<f64>>,pub velocities:Vec<Vec<f64>>,pub grid:usize,pub sample_tick:usize,pub clock:SegmentClock,pub dt:f64}
fn uv(fields:&PersistentContactFields<'_,MultipleContact<MappedPairLaw>>,x:&[f64],design:&[f64],scale:f64)->CaeResult<(Vec<f64>,Vec<f64>)>{let(mut u,mut v,mut off,mut dp)=(vec![],vec![],0,0);for b in 0..2{let f=fields.contact.native().body_field(b)?;let h=f.core().history(StepParameters{design:&design[dp..dp+f.design_size()],time_scale:scale})?;let y=f.core().to_physical(&x[off..off+f.state_size()]);u.extend_from_slice(&y[h.layout.u()..h.layout.u()+h.layout.n3]);v.extend_from_slice(&y[h.layout.v()..h.layout.v()+h.layout.n3]);off+=f.state_size();dp+=f.design_size();}Ok((u,v))}
fn uv_bar(fields:&PersistentContactFields<'_,MultipleContact<MappedPairLaw>>,design:&[f64],scale:f64,u:&[f64],v:&[f64])->CaeResult<Vec<f64>>{let(mut out,mut off,mut dp,mut p)=(vec![0.;fields.contact.state_size()],0,0,0);for b in 0..2{let f=fields.contact.native().body_field(b)?;let h=f.core().history(StepParameters{design:&design[dp..dp+f.design_size()],time_scale:scale})?;for i in 0..h.layout.n3{out[off+h.layout.u()+i]+=u[p+i]/f.core().scale()[h.layout.u()+i];out[off+h.layout.v()+i]+=v[p+i]/f.core().scale()[h.layout.v()+i];}off+=f.state_size();dp+=f.design_size();p+=h.layout.n3;}Ok(out)}
pub fn linearize(fields:&PersistentContactFields<'_,MultipleContact<MappedPairLaw>>,previous:&MultiContactNativeState,design:&[f64],external:&[f64],base:&PhaseTick,owner:&ContactOwnerIdentity,policy:OnsetPolicy,sample_tick:usize,clock:SegmentClock)->CaeResult<FixedPhaseLinearization>{let grid=base.phases.records.len();if grid==0{return Err(fail("fixed phase derivative empty history"));}let force:Vec<_>=previous.lagged_force_n.iter().zip(external).map(|(a,b)|a+b).collect();let mut selected=previous.branch.selected();let n=fields.contact.law().native_states();let gaps=fields.contact.law().scaled_gap_rows(&previous.solid,design)?.0;for(k,active)in selected.iter().enumerate(){if (*active&&previous.solid[n+k]<=0.)||(!*active&&gaps[k]<=0.){return Err(fail("fixed grid input contact tie has no ordinary derivative"));}}let mut body=vec![];let mut midpoints=vec![];let mut velocities=vec![];for r in &base.phases.records{if selected!=r.result.active{return Err(fail("fixed grid onset/release requires event derivative"));}let po=owner.for_phase(r.time_scale,r.begin_s)?;let next=ContactHistoryBranch::from_selected(&po.advance_clock(fields.contact.nominal_step_s()*r.time_scale)?,&r.result.active,r.result.numerical_target)?;body.push(selected_linearization(&fields.contact,&r.previous,&force,StepParameters{design,time_scale:r.time_scale},policy,&r.result,&po,&next)?);let(a,va)=uv(fields,&r.previous,design,r.time_scale)?;let(b,vb)=uv(fields,&r.result.state,design,r.time_scale)?;midpoints.push(a.iter().zip(b).map(|(a,b)|0.5*(a+b)).collect());velocities.push(va.iter().zip(vb).map(|(a,b)|0.5*(a+b)).collect());selected=r.result.active.clone();}require_history_branch_preserved(&previous.branch,&base.state.branch)?;let scale=fields.fluid.inner().nominal_fluid_step_s()/fields.contact.nominal_step_s();let(start,_)=uv(fields,&previous.solid,design,scale)?;let(end,_)=uv(fields,&base.state.solid,design,scale)?;Ok(FixedPhaseLinearization{body,boundaries:(0..=grid).map(|k|k as f64/grid as f64).collect(),start,end,midpoints,velocities,grid,sample_tick,clock,dt:fields.fluid.inner().nominal_fluid_step_s()})}
impl FixedPhaseLinearization{
fn trace<'a>(&'a self,previous:&MultiContactNativeState)->SegmentTrace<'a>{SegmentTrace{origin_s:previous.origin_s,clock:self.clock,sample_tick:self.sample_tick,boundaries:&self.boundaries,start:&self.start,end:&self.end,midpoints:&self.midpoints,velocities_m_s:&self.velocities}}
pub fn tangent(&self,fields:&PersistentContactFields<'_,MultipleContact<MappedPairLaw>>,previous:&MultiContactNativeState,design:&[f64],base:&PhaseTick,d:&TickDirection)->CaeResult<TickOutputDirection>{if d.solid.len()!=previous.solid.len()||d.fluid.len()!=previous.fluid.len()||d.lag.len()!=previous.lagged_force_n.len()||d.external.len()!=d.lag.len()||d.design.len()!=design.len()||!d.origin_s.is_finite(){return Err(fail("fixed grid direction shape/clock"));}let force:Vec<_>=d.lag.iter().zip(&d.external).map(|(a,b)|a+b).collect();let mut states=vec![d.solid.clone()];for j in &self.body{states.push(j.tangent(&SelectedContactDirection{previous:states.last().unwrap().clone(),flux:force.clone(),design:d.design.clone(),time_scale:0.})?);}let mut mids=vec![];let mut velocities=vec![];for i in 0..self.grid{let(a,va)=uv(fields,&states[i],design,base.phases.records[i].time_scale)?;let(b,vb)=uv(fields,&states[i+1],design,base.phases.records[i].time_scale)?;mids.push(a.iter().zip(b).map(|(a,b)|0.5*(a+b)).collect());velocities.push(va.iter().zip(vb).map(|(a,b)|0.5*(a+b)).collect());}let scale=self.dt/fields.contact.nominal_step_s();let(start,_)=uv(fields,&states[0],design,scale)?;let(end,_)=uv(fields,states.last().unwrap(),design,scale)?;let zero=vec![0.;self.grid+1];let fluid=crate::moving_contact::segment_quadrature::direction(&fields.fluid,&previous.fluid,design,self.trace(previous),SegmentDirection{origin_s:d.origin_s,boundaries:&zero,previous:&d.fluid,design:&d.design,start:&start,end:&end,midpoints:&mids,velocities_m_s:&velocities})?.direction;let lag=fluid.impulse_n_s.iter().zip(fluid.start_compensation_n_s.iter().zip(&fluid.end_compensation_n_s)).map(|(a,(b,c))|(a+b+c)/self.dt).collect();Ok(TickOutputDirection{solid:states.pop().unwrap(),fluid:fluid.state,lag,samples:fluid.samples,origin_s:d.origin_s})}
pub fn adjoint(&self,fields:&PersistentContactFields<'_,MultipleContact<MappedPairLaw>>,previous:&MultiContactNativeState,design:&[f64],base:&PhaseTick,bar:&TickOutputDirection)->CaeResult<TickBars>{if bar.solid.len()!=previous.solid.len()||bar.fluid.len()!=previous.fluid.len()||bar.lag.len()!=previous.lagged_force_n.len()||bar.samples.len()!=base.fluid_tick.samples.len()||!bar.origin_s.is_finite()||bar.solid.iter().chain(&bar.fluid).chain(&bar.lag).chain(&bar.samples).any(|x|!x.is_finite()){return Err(fail("fixed grid cotangent shape/finite clock"));}let impulse:Vec<_>=bar.lag.iter().map(|x|x/self.dt).collect();let fb=crate::moving_contact::segment_quadrature::adjoint(&fields.fluid,&previous.fluid,design,self.trace(previous),&SegmentOutput{state:bar.fluid.clone(),impulse_n_s:impulse.clone(),start_compensation_n_s:impulse.clone(),end_compensation_n_s:impulse,samples:bar.samples.clone()})?;let mut states=vec![vec![0.;previous.solid.len()];self.grid+1];add(states.last_mut().unwrap(),&bar.solid,1.);let scale=self.dt/fields.contact.nominal_step_s();let z=vec![0.;self.start.len()];add(&mut states[0],&uv_bar(fields,design,scale,&fb.start,&z)?,1.);add(states.last_mut().unwrap(),&uv_bar(fields,design,scale,&fb.end,&z)?,1.);for i in 0..self.grid{let x=uv_bar(fields,design,base.phases.records[i].time_scale,&fb.midpoints[i],&fb.velocities_m_s[i])?;add(&mut states[i],&x,0.5);add(&mut states[i+1],&x,0.5);}let mut force=vec![0.;previous.lagged_force_n.len()];let mut db=fb.design;for i in (0..self.grid).rev(){let b=self.body[i].adjoint(&states[i+1])?;add(&mut states[i],&b.previous,1.);add(&mut force,&b.flux,1.);add(&mut db,&b.design,1.);}Ok(TickBars{solid:states[0].clone(),fluid:fb.previous,lag:force.clone(),external:force,design:db,origin_s:bar.origin_s+fb.origin_s})}
}
