// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use implexity_core::{CaeError,CaeResult};
use implexity_solve::{multirate_coupling::{FluxDrivenField,SubcycledField},time_stepper::StepParameters};
use crate::moving_contact::mapped_pair_law::MappedPairLaw;
use crate::moving_contact::{resources::PersistentContactFields,collection::MultipleContact,history_branch::{ContactOwnerIdentity,ContactHistoryBranch},selected_transition::OnsetPolicy,coupled_tick_primal::MultiContactNativeState,phase_subdivision::{PhaseHistory,advance_constant_flux_phases},segment_quadrature::{SegmentClock,SegmentTrace,SegmentOutput}};
use serde_json::{Value,json};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
fn dot(a:&[f64],b:&[f64])->f64{a.iter().zip(b).map(|(a,b)|a*b).sum()}
fn check_identity(v:&Value)->CaeResult<()>{let keys=["source_graph_sha256","model_sha256","design_sha256","contact_maps_sha256","body_layout_sha256","fluid_configuration_sha256","transition_policy_sha256","nominal_dt_bits"];if v.as_object().map(|o|o.len())!=Some(keys.len())||keys[..7].iter().any(|k|v[*k].as_str().map_or(true,|s|s.len()!=64||!s.bytes().all(|c|c.is_ascii_hexdigit())))||v["nominal_dt_bits"].as_str().map_or(true,|s|s.len()!=16||!s.bytes().all(|c|c.is_ascii_hexdigit())){return Err(fail("phase complete model/design/body/fluid/source policy identity"));}Ok(())}
fn digest(x:&[f64])->CaeResult<String>{if x.iter().any(|x|!x.is_finite()){return Err(fail("phase checkpoint nonfinite"));}Ok(implexity_core::json::canonical_sha256(&json!(x.iter().map(|x|format!("{:016x}",x.to_bits())).collect::<Vec<_>>())))}
pub struct PhaseTick{pub state:MultiContactNativeState,pub phases:PhaseHistory,pub fluid_tick:SegmentOutput,pub body_lagged_work_j:f64,pub external_work_j:f64,pub native_fluid_reaction_work_j:f64,pub lagged_work_defect_j:f64}
fn unpack(fields:&PersistentContactFields<'_,MultipleContact<MappedPairLaw>>,state:&[f64],design:&[f64],scale:f64)->CaeResult<(Vec<f64>,Vec<f64>)>{let(mut u,mut v)=(vec![],vec![]);let(mut offset,mut dp)=(0,0);for b in 0..2{let f=fields.contact.native().body_field(b)?;let n=f.state_size();let nd=f.design_size();if offset+n>state.len()||dp+nd>design.len(){return Err(fail("phase native prefix layout"));}let h=f.core().history(StepParameters{design:&design[dp..dp+nd],time_scale:scale})?;let p=f.core().to_physical(&state[offset..offset+n]);u.extend_from_slice(&p[h.layout.u()..h.layout.u()+h.layout.n3]);v.extend_from_slice(&p[h.layout.v()..h.layout.v()+h.layout.n3]);offset+=n;dp+=nd;}if offset!=fields.contact.law().native_states()||dp!=design.len(){return Err(fail("phase independent body ownership"));}Ok((u,v))}
pub fn advance(fields:&PersistentContactFields<'_,MultipleContact<MappedPairLaw>>,previous:&MultiContactNativeState,design:&[f64],external:&[f64],sample_tick:usize,owner:&ContactOwnerIdentity,velocity_trace:&implexity_linalg::sparse::CsrMatrix,policy:OnsetPolicy,grid:usize,clock:SegmentClock)->CaeResult<PhaseTick>{
 let dt=fields.fluid.inner().nominal_fluid_step_s();let scale=dt/fields.contact.nominal_step_s();let nf=fields.contact.trace_operator().nrows();
 if previous.solid.len()!=fields.contact.state_size()||previous.fluid.len()!=fields.fluid.state_size()||previous.lagged_force_n.len()!=nf||external.len()!=nf||previous.fluid.iter().chain(&previous.lagged_force_n).chain(external).any(|x|!x.is_finite()){return Err(fail("phase full native input layout"));}
 owner.check_clock(previous.origin_s)?;owner.check_parameters(design,scale,policy)?;
 let force:Vec<_>=previous.lagged_force_n.iter().zip(external).map(|(a,b)|a+b).collect();let mut observer=|_:&crate::moving_contact::phase_subdivision::PhaseRecord|Ok(());
 let phases=advance_constant_flux_phases(&fields.contact,&previous.solid,&force,StepParameters{design,time_scale:scale},velocity_trace,policy,&previous.branch,owner,previous.origin_s,grid,&mut observer)?;
 if phases.total_duration_s.to_bits()!=dt.to_bits(){return Err(fail("phase actual lattice duration unchanged"));}
 let(u0,v0)=unpack(fields,&previous.solid,design,scale)?;let(ue,ve)=unpack(fields,&phases.final_state,design,scale)?;let mut midpoints=vec![];let mut velocities=vec![];
 for r in &phases.records{let(a,va)=unpack(fields,&r.previous,design,r.time_scale)?;let(b,vb)=unpack(fields,&r.result.state,design,r.time_scale)?;midpoints.push(a.iter().zip(b).map(|(a,b)|0.5*(a+b)).collect());velocities.push(va.iter().zip(vb).map(|(a,b)|0.5*(a+b)).collect());}
 let boundaries:Vec<_>=(0..=grid).map(|k|k as f64/grid as f64).collect();let (tick,branches)=crate::moving_contact::segment_quadrature::advance_with_branches(&fields.fluid,&previous.fluid,design,SegmentTrace{origin_s:previous.origin_s,clock,sample_tick,boundaries:&boundaries,start:&u0,end:&ue,midpoints:&midpoints,velocities_m_s:&velocities})?;
 let reaction:Vec<_>=tick.impulse_n_s.iter().zip(tick.start_compensation_n_s.iter().zip(&tick.end_compensation_n_s)).map(|(a,(b,c))|a+b+c).collect();let lag:Vec<_>=reaction.iter().map(|v|v/dt).collect();let du:Vec<_>=ue.iter().zip(&u0).map(|(a,b)|a-b).collect();
 let body=dot(&previous.lagged_force_n,&du);let external_work=dot(external,&du);
 let mut fluid_work=dot(&tick.start_compensation_n_s,&v0)+dot(&tick.end_compensation_n_s,&ve);
 for i in 0..grid{let weight=boundaries[i+1]-boundaries[i];let b=&branches[i];fluid_work+=weight*(dot(&b.before_impulse_n_s,&velocities[i])+dot(&b.after_impulse_n_s,&velocities[i]));}
 let end=previous.origin_s+dt;let next_owner=owner.for_phase(scale,end)?;let branch=ContactHistoryBranch::from_selected(&next_owner,&phases.final_branch.selected(),policy.residual_tolerance*policy.gap_target_fraction)?;
 if lag.iter().any(|x|!x.is_finite())||!body.is_finite()||!external_work.is_finite()||!fluid_work.is_finite(){return Err(fail("phase native work/lag finite"));}
 Ok(PhaseTick{state:MultiContactNativeState{solid:phases.final_state.clone(),fluid:tick.state.clone(),lagged_force_n:lag,origin_s:end,branch},phases,fluid_tick:tick,body_lagged_work_j:body,external_work_j:external_work,native_fluid_reaction_work_j:fluid_work,lagged_work_defect_j:body-fluid_work})
}
pub fn checkpoint(state:&MultiContactNativeState,identity:&Value,next_sample_tick:usize,grid:usize,clock:SegmentClock)->CaeResult<Value>{check_identity(identity)?;if !state.origin_s.is_finite()||!identity.is_object()||next_sample_tick==0||!grid.is_power_of_two()||grid>16{return Err(fail("phase checkpoint typed identity"));}
 Ok(json!({"schema":"persistent-phase-contact-fluid/1","identity":identity,"next_sample_tick":next_sample_tick,"grid":grid,"clock":if clock==SegmentClock::NativeTickEnd{"native_tick_end"}else{"segment_midpoint"},"solid":state.solid.iter().map(|x|format!("{:016x}",x.to_bits())).collect::<Vec<_>>(),"fluid":state.fluid.iter().map(|x|format!("{:016x}",x.to_bits())).collect::<Vec<_>>(),"lagged_force_n":state.lagged_force_n.iter().map(|x|format!("{:016x}",x.to_bits())).collect::<Vec<_>>(),"origin_bits":format!("{:016x}",state.origin_s.to_bits()),"solid_sha256":digest(&state.solid)?,"fluid_sha256":digest(&state.fluid)?,"lag_sha256":digest(&state.lagged_force_n)?,"branch":state.branch.checkpoint(&state.solid)?}))
}
pub fn restore(v:&Value,identity:&Value,owner:&ContactOwnerIdentity,contacts:usize,target:f64,shapes:[usize;3],next_sample_tick:usize,grid:usize,clock:SegmentClock)->CaeResult<MultiContactNativeState>{
 check_identity(identity)?;if v.as_object().map(|o|o.len())!=Some(13)||v["schema"]!="persistent-phase-contact-fluid/1"||v["identity"]!=*identity||v["next_sample_tick"]!=json!(next_sample_tick)||v["grid"]!=json!(grid)||v["clock"]!=json!(if clock==SegmentClock::NativeTickEnd{"native_tick_end"}else{"segment_midpoint"}){return Err(fail("phase checkpoint owner/policy identity"));}
 let read=|key:&str|->CaeResult<Vec<f64>>{v[key].as_array().ok_or_else(||fail("phase checkpoint array"))?.iter().map(|x|{let s=x.as_str().filter(|s|s.len()==16).ok_or_else(||fail("phase checkpoint bit state"))?;let bits=u64::from_str_radix(s,16).map_err(|_|fail("phase checkpoint bit state"))?;let f=f64::from_bits(bits);if !f.is_finite(){return Err(fail("phase checkpoint numeric state"));}Ok(f)}).collect()};
 let solid=read("solid")?;let fluid=read("fluid")?;let lag=read("lagged_force_n")?;if [solid.len(),fluid.len(),lag.len()]!=shapes||v["solid_sha256"]!=json!(digest(&solid)?)||v["fluid_sha256"]!=json!(digest(&fluid)?)||v["lag_sha256"]!=json!(digest(&lag)?){return Err(fail("phase checkpoint full state digest/layout"));}
 let bits=u64::from_str_radix(v["origin_bits"].as_str().ok_or_else(||fail("phase clock bits"))?,16).map_err(|_|fail("phase clock bits"))?;let origin=f64::from_bits(bits);owner.check_clock(origin)?;let branch=ContactHistoryBranch::restore(&v["branch"],&solid,owner,contacts,target)?;Ok(MultiContactNativeState{solid,fluid,lagged_force_n:lag,origin_s:origin,branch})
}
