// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use serde::{Serialize,Deserialize};
use serde_json::{Value,json};
use implexity_core::{CaeError,CaeResult};
use super::{pair_problem::{PairContactDocument,PairEventDocument,PairProblemDocument,PairFeatureDocument},model::MovingContactSpec,surface_map::SurfaceFeature,linear_path::PathPolicy,separate_body::MovingFsiPairModel,event_step::EventAdvancePolicy,selected_transition::OnsetPolicy,segment_quadrature::SegmentClock,phase_api::PhaseSchedule};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
pub const SCHEMA:&str="implexity-moving-fsi-contact-set-fixed-phase/1";
#[derive(Clone,Serialize,Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ContactSetDocument{pub schema:String,pub source_graph_sha256:String,pub bodies:[Value;2],pub contacts:Vec<PairContactDocument>,pub event:PairEventDocument,pub phase:PhaseDocument,pub initial:InitialDocument,pub external_force_n:Vec<f64>,pub observables:Value,pub responses:Value,pub macro_steps:usize,pub checkpoint_output:bool}
#[derive(Clone,Serialize,Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PhaseDocument{pub subdivisions:usize,pub clock:String,pub maximum_active_set_iterations:usize}
#[derive(Clone,Serialize,Deserialize)]
#[serde(tag="kind",rename_all="snake_case",deny_unknown_fields)]
pub enum InitialDocument{NativeRest{origin_s:f64,selected:Vec<bool>},Checkpoint{value:Value}}
pub struct ContactSetProblem{pub model:MovingFsiPairModel,pub contacts:Vec<MovingContactSpec>,pub event:EventAdvancePolicy,pub onset:OnsetPolicy,pub schedule:PhaseSchedule,pub document:ContactSetDocument,pub identity:String}
fn spec(c:&PairContactDocument)->CaeResult<MovingContactSpec>{let p=&c.path;if ![c.gap_scale_m,c.force_scale_n,p.minimum_area_ratio,p.time_resolution].iter().all(|v|v.is_finite()&&*v>0.)||!p.minimum_barycentric.is_finite()||!(0. ..1./3.).contains(&p.minimum_barycentric)||p.minimum_signed_gap!=0.||p.maximum_intervals==0||p.maximum_depth==0||p.maximum_depth>60||c.bodies[0]>1||c.bodies[1..].iter().any(|b|*b>1||*b==c.bodies[0]){return Err(fail("contact collection feature/path ownership"));}let features=c.features.iter().map(|f|Ok(match f{PairFeatureDocument::Vertex{index}=>SurfaceFeature::Vertex(*index),PairFeatureDocument::FixedTetrahedron{nodes,weights,weight_tolerance}=>SurfaceFeature::FixedTetrahedron{nodes:*nodes,weights:*weights,weight_tolerance:*weight_tolerance},PairFeatureDocument::DensityEdge{nodes,iso,contrast_min,interior_margin}=>{if !iso.is_finite()||!(0. ..=1.).contains(iso)||!contrast_min.is_finite()||*contrast_min<=0.||!interior_margin.is_finite()||!(0. ..0.5).contains(interior_margin)||nodes[0]==nodes[1]{return Err(fail("contact collection density feature domain"));}SurfaceFeature::DensityEdge{nodes:*nodes,iso:*iso,contrast_min:*contrast_min,interior_margin:*interior_margin}}})).collect::<CaeResult<Vec<_>>>()?;Ok(MovingContactSpec{body_nodes:c.body_nodes.clone(),features:features.try_into().map_err(|_|fail("contact feature shape"))?,bodies:c.bodies,replaced_planes:vec![],gap_scale_m:c.gap_scale_m,force_scale_n:c.force_scale_n,path_policy:PathPolicy{minimum_barycentric:p.minimum_barycentric,minimum_area_ratio:p.minimum_area_ratio,minimum_signed_gap:p.minimum_signed_gap,time_resolution:p.time_resolution,maximum_intervals:p.maximum_intervals,maximum_depth:p.maximum_depth}})}
impl ContactSetDocument{
 pub fn from_value(v:&Value)->CaeResult<Self>{serde_json::from_value(v.clone()).map_err(|e|CaeError::contract(e.to_string()))}
 pub fn build(self)->CaeResult<ContactSetProblem>{if self.schema!=SCHEMA||self.contacts.is_empty()||self.source_graph_sha256.len()!=64||!self.source_graph_sha256.bytes().all(|c|c.is_ascii_hexdigit())||self.macro_steps==0||self.phase.maximum_active_set_iterations==0||self.external_force_n.iter().any(|v|!v.is_finite()){return Err(fail("contact collection document domain"));}let contacts=self.contacts.iter().map(spec).collect::<CaeResult<Vec<_>>>()?;let clock=match self.phase.clock.as_str(){"segment_midpoint"=>SegmentClock::SegmentMidpoint,"native_tick_end"=>SegmentClock::NativeTickEnd,_=>return Err(fail("contact collection quadrature clock"))};let schedule=PhaseSchedule::new(self.phase.subdivisions,clock)?;let shared=PairProblemDocument{schema:"implexity-moving-fsi-pair/1".into(),bodies:self.bodies.clone(),contact:self.contacts[0].clone(),event:self.event.clone()}.build()?;if self.macro_steps>shared.model.native_body(0)?.problem.time.history_steps(){return Err(fail("contact collection history exceeds authored horizon"));}match &self.initial{InitialDocument::NativeRest{origin_s,selected}=>{if !origin_s.is_finite()||*origin_s<0.||selected.len()!=contacts.len(){return Err(fail("contact collection explicit initial branch/clock"));}},InitialDocument::Checkpoint{value}=>{if value["schema"]!="persistent-phase-contact-fluid/1"{return Err(fail("contact collection checkpoint schema"));}}}let identity=implexity_core::json::canonical_sha256(&serde_json::to_value(&self).map_err(|e|CaeError::contract(e.to_string()))?);let onset=OnsetPolicy{residual_tolerance:shared.event.residual_tolerance,maximum_newton_iterations:shared.event.maximum_newton_iterations,maximum_active_set_iterations:self.phase.maximum_active_set_iterations,gap_target_fraction:shared.event.maintained_gap_target_fraction,normal_velocity_tolerance_m_s:shared.event.impact.normal_velocity_m_s};Ok(ContactSetProblem{model:shared.model,contacts,event:shared.event,onset,schedule,document:self,identity})}
}
pub fn editor_schema()->Value{json!({"type":"object","additionalProperties":false,"required":["schema","source_graph_sha256","bodies","contacts","event","phase","initial","external_force_n","observables","responses","macro_steps","checkpoint_output"],"properties":{"schema":{"type":"string","enum":[SCHEMA]},"source_graph_sha256":{"type":"string"},"bodies":{"type":"array","minItems":2,"maxItems":2,"items":crate::editor::schema(None)},"contacts":{"type":"array","minItems":1,"items":{"type":"object","required":["body_nodes","features","bodies","gap_scale_m","force_scale_n","path"],"properties":{"body_nodes":{"type":"array"},"features":{"type":"array","minItems":4,"maxItems":4},"bodies":{"type":"array","minItems":4,"maxItems":4},"gap_scale_m":{"type":"number","unit":"m"},"force_scale_n":{"type":"number","unit":"N"},"path":{"type":"object"}}}},"event":{"type":"object"},"phase":{"type":"object","required":["subdivisions","clock","maximum_active_set_iterations"],"properties":{"subdivisions":{"type":"integer","enum":[1,2,4,8,16]},"clock":{"type":"string","enum":["segment_midpoint","native_tick_end"]},"maximum_active_set_iterations":{"type":"integer","minimum":1}}},"initial":{"type":"object"},"external_force_n":{"type":"array","items":{"type":"number","unit":"N"}},"observables":{"type":"array"},"responses":{"type":"object"},"macro_steps":{"type":"integer","minimum":1},"checkpoint_output":{"type":"boolean"}},"x-derivative-scope":"strict selected fixed-phase map; contact ties/onset/release/adaptive-grid derivatives unavailable; weighted full-tick quadrature approximation"})}
