// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use implexity_core::{CaeError,CaeResult};
use implexity_physics_lbm::moving::field::event_trace::*;
use crate::interface::FluidField;
#[derive(Clone,Copy,PartialEq,Eq)]
pub enum SegmentClock{NativeTickEnd,SegmentMidpoint}
#[derive(Clone,Copy)]
pub struct SegmentTrace<'a>{pub origin_s:f64,pub clock:SegmentClock,pub sample_tick:usize,pub boundaries:&'a[f64],pub start:&'a[f64],pub end:&'a[f64],pub midpoints:&'a[Vec<f64>],pub velocities_m_s:&'a[Vec<f64>]}
#[derive(Clone,Copy)]
pub struct SegmentDirection<'a>{pub origin_s:f64,pub boundaries:&'a[f64],pub previous:&'a[f64],pub design:&'a[f64],pub start:&'a[f64],pub end:&'a[f64],pub midpoints:&'a[Vec<f64>],pub velocities_m_s:&'a[Vec<f64>]}
pub struct SegmentOutput{pub state:Vec<f64>,pub impulse_n_s:Vec<f64>,pub start_compensation_n_s:Vec<f64>,pub end_compensation_n_s:Vec<f64>,pub samples:Vec<f64>}
pub struct SegmentTangent{pub primal:SegmentOutput,pub direction:SegmentOutput}
pub struct SegmentBars{pub previous:Vec<f64>,pub design:Vec<f64>,pub start:Vec<f64>,pub end:Vec<f64>,pub midpoints:Vec<Vec<f64>>,pub velocities_m_s:Vec<Vec<f64>>,pub origin_s:f64,pub boundaries:Vec<f64>}
fn fail(s:&str)->CaeError{CaeError::contract(s)}
fn dot(a:&[f64],b:&[f64])->f64{a.iter().zip(b).map(|(a,b)|a*b).sum()}
fn add(a:&mut[f64],b:&[f64],w:f64){for(a,b)in a.iter_mut().zip(b){*a+=w*b;}}
fn output(e:&EventTickOutput)->SegmentOutput{SegmentOutput{state:e.state.clone(),impulse_n_s:e.before_impulse_n_s.iter().zip(&e.after_impulse_n_s).map(|(a,b)|a+b).collect(),start_compensation_n_s:e.start_compensation_impulse_n_s.clone(),end_compensation_n_s:e.end_compensation_impulse_n_s.clone(),samples:e.samples.clone()}}
fn zero(o:&SegmentOutput)->SegmentOutput{SegmentOutput{state:vec![0.;o.state.len()],impulse_n_s:vec![0.;o.impulse_n_s.len()],start_compensation_n_s:vec![0.;o.start_compensation_n_s.len()],end_compensation_n_s:vec![0.;o.end_compensation_n_s.len()],samples:vec![0.;o.samples.len()]}}
fn accumulate(a:&mut SegmentOutput,b:&SegmentOutput,w:f64){add(&mut a.state,&b.state,w);add(&mut a.impulse_n_s,&b.impulse_n_s,w);add(&mut a.start_compensation_n_s,&b.start_compensation_n_s,w);add(&mut a.end_compensation_n_s,&b.end_compensation_n_s,w);add(&mut a.samples,&b.samples,w);}
fn check(t:SegmentTrace<'_>,d:Option<SegmentDirection<'_>>)->CaeResult<()>{let n=t.midpoints.len();if n==0||n>16||t.boundaries.len()!=n+1||t.velocities_m_s.len()!=n||t.boundaries[0]!=0.||t.boundaries[n]!=1.||!t.origin_s.is_finite()||t.boundaries.windows(2).any(|v|!v[0].is_finite()||!v[1].is_finite()||v[1]<=v[0]){return Err(fail("segment trace interval partition"));}let sum:f64=t.boundaries.windows(2).map(|v|v[1]-v[0]).sum();if !sum.is_finite()||(sum-1.).abs()>16.*f64::EPSILON{return Err(fail("segment trace normalized convex weights"));}if let Some(d)=d{if !d.origin_s.is_finite()||d.boundaries.len()!=n+1||d.boundaries[0]!=0.||d.boundaries[n]!=0.||d.boundaries.iter().any(|x|!x.is_finite())||d.midpoints.len()!=n||d.velocities_m_s.len()!=n{return Err(fail("segment direction interval partition"));}}Ok(())}
fn trace<'a>(t:SegmentTrace<'a>,i:usize,dt:f64)->EventTickTrace<'a>{let origin=t.origin_s+if t.clock==SegmentClock::NativeTickEnd{0.}else{(0.5*(t.boundaries[i]+t.boundaries[i+1])-1.)*dt};EventTickTrace{origin_s:origin,event_s:origin+0.5*dt,sample_tick:t.sample_tick,start:t.start,end:t.end,before_midpoint:&t.midpoints[i],after_midpoint:&t.midpoints[i],before_velocity_m_s:&t.velocities_m_s[i],after_velocity_m_s:&t.velocities_m_s[i]}}
pub fn advance(fluid:&FluidField,previous:&[f64],design:&[f64],t:SegmentTrace<'_>)->CaeResult<SegmentOutput>{Ok(advance_with_branches(fluid,previous,design,t)?.0)}
pub fn advance_with_branches(fluid:&FluidField,previous:&[f64],design:&[f64],t:SegmentTrace<'_>)->CaeResult<(SegmentOutput,Vec<EventTickOutput>)>{check(t,None)?;let dt=fluid.inner().nominal_fluid_step_s();let mut total=None;let mut branches=vec![];for i in 0..t.midpoints.len(){let branch=fluid.event_tick(previous,design,trace(t,i,dt))?;let value=output(&branch);let a=total.get_or_insert_with(||zero(&value));accumulate(a,&value,t.boundaries[i+1]-t.boundaries[i]);branches.push(branch);}Ok((total.unwrap(),branches))}
pub fn direction(fluid:&FluidField,previous:&[f64],design:&[f64],t:SegmentTrace<'_>,d:SegmentDirection<'_>)->CaeResult<SegmentTangent>{check(t,Some(d))?;let dt=fluid.inner().nominal_fluid_step_s();let mut total=None;for i in 0..t.midpoints.len(){let origin=d.origin_s+if t.clock==SegmentClock::NativeTickEnd{0.}else{0.5*(d.boundaries[i]+d.boundaries[i+1])*dt};let e=fluid.event_tick_tangent(previous,design,trace(t,i,dt),EventTickDirection{origin_s:origin,event_s:origin,previous:d.previous,design:d.design,start:d.start,end:d.end,before_midpoint:&d.midpoints[i],after_midpoint:&d.midpoints[i],before_velocity_m_s:&d.velocities_m_s[i],after_velocity_m_s:&d.velocities_m_s[i]})?;let value=output(&e.primal);let derivative=SegmentOutput{state:e.state,impulse_n_s:e.before_impulse_n_s.iter().zip(&e.after_impulse_n_s).map(|(a,b)|a+b).collect(),start_compensation_n_s:e.start_compensation_impulse_n_s,end_compensation_n_s:e.end_compensation_impulse_n_s,samples:e.samples};let a=total.get_or_insert_with(||SegmentTangent{primal:zero(&value),direction:zero(&value)});let w=t.boundaries[i+1]-t.boundaries[i];accumulate(&mut a.primal,&value,w);accumulate(&mut a.direction,&derivative,w);accumulate(&mut a.direction,&value,d.boundaries[i+1]-d.boundaries[i]);}Ok(total.unwrap())}
pub fn adjoint(fluid:&FluidField,previous:&[f64],design:&[f64],t:SegmentTrace<'_>,bar:&SegmentOutput)->CaeResult<SegmentBars>{check(t,None)?;let n=t.midpoints.len();let dt=fluid.inner().nominal_fluid_step_s();let mut bars=SegmentBars{previous:vec![0.;previous.len()],design:vec![0.;design.len()],start:vec![0.;t.start.len()],end:vec![0.;t.end.len()],midpoints:t.midpoints.iter().map(|v|vec![0.;v.len()]).collect(),velocities_m_s:t.velocities_m_s.iter().map(|v|vec![0.;v.len()]).collect(),origin_s:0.,boundaries:vec![0.;n+1]};for i in 0..n{let e=fluid.event_tick(previous,design,trace(t,i,dt))?;let value=output(&e);let w=t.boundaries[i+1]-t.boundaries[i];let mut weighted=zero(bar);accumulate(&mut weighted,bar,w);let r=fluid.event_tick_adjoint(previous,design,trace(t,i,dt),EventTickCotangent{state:&weighted.state,before_impulse_n_s:&weighted.impulse_n_s,after_impulse_n_s:&weighted.impulse_n_s,start_compensation_impulse_n_s:&weighted.start_compensation_n_s,end_compensation_impulse_n_s:&weighted.end_compensation_n_s,samples:&weighted.samples})?;add(&mut bars.previous,&r.previous,1.);add(&mut bars.design,&r.design,1.);add(&mut bars.start,&r.start,1.);add(&mut bars.end,&r.end,1.);add(&mut bars.midpoints[i],&r.before_midpoint,1.);add(&mut bars.midpoints[i],&r.after_midpoint,1.);add(&mut bars.velocities_m_s[i],&r.before_velocity_m_s,1.);add(&mut bars.velocities_m_s[i],&r.after_velocity_m_s,1.);let time=r.origin_s+r.event_s;bars.origin_s+=time;let weight=dot(&bar.state,&value.state)+dot(&bar.impulse_n_s,&value.impulse_n_s)+dot(&bar.start_compensation_n_s,&value.start_compensation_n_s)+dot(&bar.end_compensation_n_s,&value.end_compensation_n_s)+dot(&bar.samples,&value.samples);let clock_weight=if t.clock==SegmentClock::NativeTickEnd{0.}else{0.5*dt*time};bars.boundaries[i]+=clock_weight-weight;bars.boundaries[i+1]+=clock_weight+weight;}bars.boundaries[0]=0.;bars.boundaries[n]=0.;Ok(bars)}
