// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use crate::moving_contact::contact_set_kinematics::ContactSetKinematics;
use implexity_core::{CaeError,CaeResult};
use implexity_linalg::sparse::CsrMatrix;
use implexity_solve::{matrix::{Jacobian,FnAction,checked_product},multirate_coupling::{FluxDrivenField,FieldJacobians},time_stepper::StepParameters};
use crate::moving_contact::{contact_field::ContactField,mapped_pair_law::MappedPairLaw};
use crate::moving_contact::{collection::MultipleContact,selected_transition::{OnsetResult,OnsetPolicy},history_branch::{ContactHistoryBranch,ContactOwnerIdentity}};
use std::sync::Arc;
use implexity_solve::{factorization::Factorization,local_condensation::LocalEliminationPartition};
fn fail(s:impl std::fmt::Display)->CaeError{CaeError::contract(s.to_string())}
fn rows(top:Jacobian,bottom:Jacobian,n:usize)->CaeResult<Jacobian>{let (nr,nc)=top.shape();let (br,bc)=bottom.shape();if nr!=n+br||nc!=bc{return Err(fail("selected contact derivative row shape"));}let tf=top.clone();let bf=bottom.clone();Ok(Jacobian::Operator(Arc::new(FnAction::new((nr,nc),move|x|{let mut y=checked_product(&tf,x,"selected native derivative",false)?;let z=checked_product(&bf,x,"selected branch derivative",false)?;y[n..].copy_from_slice(&z);Ok(y)},move|y|{if y.len()!=nr{return Err(fail("selected branch cotangent width"));}let mut t=y.to_vec();t[n..].fill(0.);let mut z=checked_product(&top,&t,"selected native transpose",true)?;let b=checked_product(&bottom,&y[n..],"selected branch transpose",true)?;for(a,b)in z.iter_mut().zip(b){*a+=b;}Ok(z)}))))}
fn stored_rows(top:Jacobian,bottom:Jacobian,n:usize)->CaeResult<Jacobian>{let a=top.to_csr()?;let b=bottom.to_csr()?;if a.nrows()!=n+b.nrows()||a.ncols()!=b.ncols(){return Err(fail("selected current stored row shape"));}let mut e=vec![];for i in 0..n{let(js,vs)=a.row(i);e.extend(js.iter().zip(vs).map(|(&j,&v)|(i,j,v)));}for i in 0..b.nrows(){let(js,vs)=b.row(i);e.extend(js.iter().zip(vs).map(|(&j,&v)|(n+i,j,v)));}sparse(a.nrows(),a.ncols(),&e)}
fn sparse(rows:usize,cols:usize,entries:&[(usize,usize,f64)])->CaeResult<Jacobian>{let r:Vec<_>=entries.iter().map(|v|v.0).collect();let c:Vec<_>=entries.iter().map(|v|v.1).collect();let v:Vec<_>=entries.iter().map(|v|v.2).collect();Ok(Jacobian::Csr(CsrMatrix::from_triplets(rows,cols,&r,&c,&v).map_err(fail)?))}
pub struct SelectedContactLinearization{pub jacobians:FieldJacobians,pub selected:Vec<bool>,factor:Factorization,pub condition_limit:f64,pub condition_estimate:f64}
pub struct SelectedContactDirection{pub previous:Vec<f64>,pub flux:Vec<f64>,pub design:Vec<f64>,pub time_scale:f64}
pub struct SelectedContactPullback{pub previous:Vec<f64>,pub flux:Vec<f64>,pub design:Vec<f64>,pub time_scale:f64}
impl SelectedContactLinearization{
 pub fn tangent(&self,d:&SelectedContactDirection)->CaeResult<Vec<f64>>{if !d.time_scale.is_finite(){return Err(fail("selected time direction finite"));}let j=&self.jacobians;let mut rhs=checked_product(&j.previous,&d.previous,"selected previous direction",false)?;for(m,x)in [(&j.flux,&d.flux),(&j.design,&d.design)]{for(a,b)in rhs.iter_mut().zip(checked_product(m,x,"selected input direction",false)?){*a+=b;}}for(a,b)in rhs.iter_mut().zip(&j.time_scale){*a= -(*a+b*d.time_scale);}Ok(self.factor.solve(&rhs,false)?.0)}
 pub fn adjoint(&self,bar:&[f64])->CaeResult<SelectedContactPullback>{let j=&self.jacobians;let z=self.factor.solve(bar,true)?.0;let neg:Vec<_>=z.iter().map(|v|-v).collect();Ok(SelectedContactPullback{previous:checked_product(&j.previous,&neg,"selected previous pullback",true)?,flux:checked_product(&j.flux,&neg,"selected force pullback",true)?,design:checked_product(&j.design,&neg,"selected design pullback",true)?,time_scale:neg.iter().zip(&j.time_scale).map(|(a,b)|a*b).sum()})}
}
pub fn contact_set_selected_linearization<F:FluxDrivenField,L:ContactSetKinematics>(field:&ContactField<F,L>,previous:&[f64],flux:&[f64],p:StepParameters<'_>,policy:OnsetPolicy,result:&OnsetResult,owner:&ContactOwnerIdentity,branch:&ContactHistoryBranch)->CaeResult<SelectedContactLinearization>{contact_set_selected_linearization_with_condition_limit(field,previous,flux,p,policy,result,owner,branch,implexity_solve::implicit_block::BlockOptions::<()>::default().condition_limit)}
pub fn contact_set_selected_linearization_with_condition_limit<F:FluxDrivenField,L:ContactSetKinematics>(field:&ContactField<F,L>,previous:&[f64],flux:&[f64],p:StepParameters<'_>,policy:OnsetPolicy,result:&OnsetResult,owner:&ContactOwnerIdentity,branch:&ContactHistoryBranch,condition_limit:f64)->CaeResult<SelectedContactLinearization>{let end_owner=owner.advance_clock(field.nominal_step_s()*p.time_scale)?;contact_set_selected_linearization_at_end(field,previous,flux,p,policy,result,owner,&end_owner,branch,condition_limit)}
fn contact_set_selected_linearization_at_end<F:FluxDrivenField,L:ContactSetKinematics>(field:&ContactField<F,L>,previous:&[f64],flux:&[f64],p:StepParameters<'_>,policy:OnsetPolicy,result:&OnsetResult,owner:&ContactOwnerIdentity,end_owner:&ContactOwnerIdentity,branch:&ContactHistoryBranch,condition_limit:f64)->CaeResult<SelectedContactLinearization>{if !condition_limit.is_finite()||condition_limit<=1.{return Err(fail("selected derivative condition limit must be finite and exceed one"));}owner.check_parameters(p.design,p.time_scale,policy)?;branch.check_binding(end_owner,field.law().contact_count(),result.numerical_target)?;if branch.selected()!=result.active||result.original_residual_norm>policy.residual_tolerance{return Err(fail("selected derivative forward result binding"));}let n=field.law().native_states();let m=field.law().contact_count();let gaps=field.law().scaled_gap_rows(&result.state,p.design)?;if result.active.len()!=m||result.numerical_target.to_bits()!=(policy.residual_tolerance*policy.gap_target_fraction).to_bits(){return Err(fail("selected derivative actual target"));}for k in 0..m{if result.active[k]{if result.state[n+k]<=0.||!result.state[n+k].is_finite(){return Err(fail("biactive contact has no ordinary derivative"));}}else if gaps.0[k]<=0.{return Err(fail("grazing open contact has no ordinary derivative"));}}
 let inverse=field.law().inverse_force_scales(previous,p)?;let gd=field.law().scaled_gap_design_rows(&result.state,p.design)?.to_csr()?;let gc=gaps.1.to_csr()?;let mut ce=vec![];let mut de=vec![];for k in 0..m{if result.active[k]{let(js,vs)=gc.row(k);ce.extend(js.iter().zip(vs).map(|(&i,&v)|(k,i,v)));let(js,vs)=gd.row(k);de.extend(js.iter().zip(vs).map(|(&i,&v)|(k,i,v)));}else{ce.push((k,n+k,-inverse[k]));}}
 field.law().check_selected_geometry_domain(1,&result.state,previous,p)?;let mut j=field.jacobians(1,&result.state,previous,flux,p)?;j.current=stored_rows(j.current,sparse(m,n+m,&ce)?,n)?;j.previous=rows(j.previous,sparse(m,n+m,&[])?,n)?;j.flux=rows(j.flux,sparse(m,flux.len(),&[])?,n)?;j.design=rows(j.design,sparse(m,p.design.len(),&de)?,n)?;j.time_scale[n..].fill(0.);let partition=field.local_elimination_groups()?.map(|groups|LocalEliminationPartition::new(n+m,groups).map_err(fail)).transpose()?;let factor=Factorization::new_with_partition(j.current.clone(),n+m,condition_limit,None,partition.as_ref())?;let condition_estimate=factor.condition();Ok(SelectedContactLinearization{jacobians:j,selected:result.active.clone(),factor,condition_limit,condition_estimate})}
pub fn require_history_branch_preserved(previous:&ContactHistoryBranch,next:&ContactHistoryBranch)->CaeResult<()>{if previous.selected()!=next.selected(){return Err(fail("contact onset/release needs localized event-time derivative owner"));}Ok(())}

pub fn selected_linearization_with_condition_limit<F:FluxDrivenField>(field:&ContactField<F,MultipleContact<MappedPairLaw>>,previous:&[f64],flux:&[f64],p:StepParameters<'_>,policy:OnsetPolicy,result:&OnsetResult,owner:&ContactOwnerIdentity,branch:&ContactHistoryBranch,condition_limit:f64)->CaeResult<SelectedContactLinearization>{contact_set_selected_linearization_with_condition_limit(field,previous,flux,p,policy,result,owner,branch,condition_limit)}
pub fn selected_linearization<F:FluxDrivenField>(field:&ContactField<F,MultipleContact<MappedPairLaw>>,previous:&[f64],flux:&[f64],p:StepParameters<'_>,policy:OnsetPolicy,result:&OnsetResult,owner:&ContactOwnerIdentity,branch:&ContactHistoryBranch)->CaeResult<SelectedContactLinearization>{contact_set_selected_linearization(field,previous,flux,p,policy,result,owner,branch)}

#[derive(Clone,Copy)]pub struct PhaseGridInterval{origin_s:f64,native_step_s:f64,parent_scale:f64,index:usize,count:usize,begin_s:f64,end_s:f64,duration_s:f64,time_scale:f64}
impl PhaseGridInterval{
 pub fn new(origin_s:f64,native_step_s:f64,parent_scale:f64,index:usize,count:usize,begin_s:f64,end_s:f64,duration_s:f64,time_scale:f64)->CaeResult<Self>{
  if !count.is_power_of_two()||count>16||index>=count||!origin_s.is_finite()||!native_step_s.is_finite()||native_step_s<=0.||!parent_scale.is_finite()||parent_scale<=0.{return Err(fail("selected derivative phase grid domain"));}
  let scale=parent_scale/count as f64;let duration=native_step_s*scale;let total=native_step_s*parent_scale;let begin=origin_s+index as f64*duration;let end=origin_s+(index+1)as f64*duration;
  if !duration.is_finite()||duration<=0.||!total.is_finite()||!begin.is_finite()||!end.is_finite()||end<=begin||(duration*count as f64).to_bits()!=total.to_bits()||time_scale.to_bits()!=scale.to_bits()||duration_s.to_bits()!=duration.to_bits()||begin_s.to_bits()!=begin.to_bits()||end_s.to_bits()!=end.to_bits(){return Err(fail("selected derivative exact phase grid interval"));}
  Ok(Self{origin_s,native_step_s,parent_scale,index,count,begin_s,end_s,duration_s,time_scale})
 }
 fn owners(&self,parent:&ContactOwnerIdentity,design:&[f64],policy:OnsetPolicy,native_step_s:f64,time_scale:f64)->CaeResult<(ContactOwnerIdentity,ContactOwnerIdentity)>{
  Self::new(self.origin_s,self.native_step_s,self.parent_scale,self.index,self.count,self.begin_s,self.end_s,self.duration_s,self.time_scale)?;
  if native_step_s.to_bits()!=self.native_step_s.to_bits()||time_scale.to_bits()!=self.time_scale.to_bits(){return Err(fail("selected derivative phase grid field binding"));}
  parent.check_clock(self.origin_s)?;parent.check_parameters(design,self.parent_scale,policy)?;
  Ok((parent.for_phase(self.time_scale,self.begin_s)?,parent.for_phase(self.time_scale,self.end_s)?))
 }
 pub fn end_owner(&self,parent:&ContactOwnerIdentity,design:&[f64],policy:OnsetPolicy)->CaeResult<ContactOwnerIdentity>{Ok(self.owners(parent,design,policy,self.native_step_s,self.time_scale)?.1)}
}
pub fn contact_set_selected_linearization_on_grid<F:FluxDrivenField,L:ContactSetKinematics>(field:&ContactField<F,L>,previous:&[f64],flux:&[f64],p:StepParameters<'_>,policy:OnsetPolicy,result:&OnsetResult,parent_owner:&ContactOwnerIdentity,interval:&PhaseGridInterval,branch:&ContactHistoryBranch,condition_limit:f64)->CaeResult<SelectedContactLinearization>{
 let(begin,end)=interval.owners(parent_owner,p.design,policy,field.nominal_step_s(),p.time_scale)?;
 contact_set_selected_linearization_at_end(field,previous,flux,p,policy,result,&begin,&end,branch,condition_limit)
}
