// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use std::collections::BTreeMap;
use implexity_core::{CaeError,CaeResult};
use implexity_linalg::dense::DenseMatrix;
use implexity_solve::{time_stepper::{TimeStepper,StepParameters,StepRecord,StepDiagnostics,StepTangent,StepCotangent},multirate_coupling::SubcycledField,checkpointed_history::{HistoryRun,run_history,history_adjoint_many},state_store::StoreBudget};
use crate::interface::FluidField;
use super::{macro_phase::CarrierPath,segment_quadrature::{SegmentClock,SegmentTrace,SegmentDirection,SegmentOutput}};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
fn add(a:&mut[f64],b:&[f64],w:f64){for(a,b)in a.iter_mut().zip(b){*a+=w*b;}}
fn dot(a:&[f64],b:&[f64])->f64{a.iter().zip(b).map(|(a,b)|a*b).sum()}
pub struct CarrierFluidStepper<'a>{fluid:&'a FluidField,ticks:usize,first_tick:usize,grid:usize,nf:usize,nd:usize,clock:SegmentClock,duration_s:f64,identity:String,names:Vec<String>}
pub struct CarrierHistoryBars{pub fluid:Vec<f64>,pub design:Vec<f64>,pub displacement:Vec<Vec<f64>>,pub origin_s:f64}
impl<'a> CarrierFluidStepper<'a>{
 pub fn new(fluid:&'a FluidField,ticks:usize,first_tick:usize,path:&CarrierPath,nd:usize,clock:SegmentClock,identity:&str)->CaeResult<Self>{let grid=path.displacement.len().checked_sub(1).ok_or_else(||fail("carrier history empty path"))?;let nf=path.displacement.first().ok_or_else(||fail("carrier history path"))?.len();if ticks==0||first_tick==0||first_tick.checked_add(ticks-1).is_none()||grid==0||grid>16||nf==0||path.velocity.len()!=grid+1||path.displacement.iter().chain(&path.velocity).any(|v|v.len()!=nf||v.iter().any(|x|!x.is_finite())){return Err(fail("carrier history shape and native tick extent"));}let mut names=fluid.sample_names().to_vec();for kind in ["fluid","start_compensation","end_compensation"]{names.extend((0..nf).map(|i|format!("native_reaction_{kind}_impulse_{i}")));}names.push("native_reaction_work_diagnostic".into());Ok(Self{fluid,ticks,first_tick,grid,nf,nd,clock,duration_s:path.duration_s,identity:implexity_core::json::canonical_sha256(&serde_json::json!({"owner":identity,"duration_bits":format!("{:016x}",path.duration_s.to_bits()),"ticks":ticks,"first_tick":first_tick,"grid":grid,"nf":nf,"nd":nd,"clock":if clock==SegmentClock::NativeTickEnd{"native_tick_end"}else{"segment_midpoint"}})),names})}
 pub fn parameters(&self,design:&[f64],path:&CarrierPath,origin_s:f64)->CaeResult<Vec<f64>>{if design.len()!=self.nd||!origin_s.is_finite(){return Err(fail("carrier history input parameters"));}let mut x=design.to_vec();for v in &path.displacement{x.extend(v);}x.push(origin_s);self.decode(&x)?;Ok(x)}
 fn decode(&self,x:&[f64])->CaeResult<(CarrierPath,f64)>{if x.len()!=self.design_size()||x.iter().any(|x|!x.is_finite()){return Err(fail("carrier history complete finite parameters"));}let n=(self.grid+1)*self.nf;Ok((CarrierPath{displacement:x[self.nd..self.nd+n].chunks_exact(self.nf).map(|x|x.to_vec()).collect(),velocity:vec![vec![0.;self.nf];self.grid+1],duration_s:self.duration_s},*x.last().unwrap()))}
 pub fn run(&self,previous:&[f64],parameters:&[f64],policy:implexity_solve::checkpointed_history::CheckpointPolicy)->CaeResult<HistoryRun>{run_history(self,StepParameters{design:parameters,time_scale:1.},previous,1,Some(self.ticks),None,policy,&StoreBudget::from_environment()?)}
 pub fn pullback(&self,run:&HistoryRun,parameters:&[f64],terminal:&[f64],samples:&[f64],impulse:&[f64])->CaeResult<CarrierHistoryBars>{if samples.len()!=self.fluid.sample_names().len()||impulse.len()!=self.nf{return Err(fail("carrier history output bar shape"));}let mut bars=DenseMatrix::zeros(self.ticks,self.names.len());for r in 0..self.ticks{bars.data[r*self.names.len()..r*self.names.len()+samples.len()].copy_from_slice(samples);for k in 0..3{let off=r*self.names.len()+samples.len()+k*self.nf;bars.data[off..off+self.nf].copy_from_slice(impulse);}}let mut out=history_adjoint_many(self,StepParameters{design:parameters,time_scale:1.},run,&[bars],&[terminal.to_vec()])?;let g=out.remove(0);let(p,o)=self.decode(&g.design)?;Ok(CarrierHistoryBars{fluid:g.initial_state,design:g.design[..self.nd].to_vec(),displacement:p.displacement,origin_s:o})}
 fn scatter(&self,t:f64,u:&[f64],v:&[f64],p:&mut[f64]){let k=((t*self.grid as f64).floor()as usize).min(self.grid-1);let f=(t*self.grid as f64-k as f64).clamp(0.,1.);let off=self.nd;let inverse_phase_dt=self.grid as f64/self.duration_s;for i in 0..self.nf{p[off+k*self.nf+i]+=(1.-f)*u[i];p[off+(k+1)*self.nf+i]+=f*u[i];p[off+k*self.nf+i]-=inverse_phase_dt*v[i];p[off+(k+1)*self.nf+i]+=inverse_phase_dt*v[i];}}
}
impl TimeStepper for CarrierFluidStepper<'_>{
 fn identity(&self)->&str{&self.identity}fn state_size(&self)->usize{self.fluid.state_size()}fn design_size(&self)->usize{self.nd+(self.grid+1)*self.nf+1}fn sample_names(&self)->&[String]{&self.names}fn nominal_step_s(&self)->f64{self.fluid.inner().nominal_fluid_step_s()}
 fn initial_state(&self,d:&[f64])->CaeResult<Vec<f64>>{self.decode(d)?;self.fluid.initial_state(&d[..self.nd])}fn initial_state_vjp(&self,d:&[f64],b:&[f64])->CaeResult<Vec<f64>>{self.decode(d)?;let mut v=vec![0.;self.design_size()];let g=self.fluid.initial_state_vjp(&d[..self.nd],b)?;v[..self.nd].copy_from_slice(&g);Ok(v)}
 fn advance(&self,n:usize,z:&[f64],p:StepParameters<'_>)->CaeResult<StepRecord>{if n==0||n>self.ticks||p.time_scale!=1.{return Err(fail("carrier history native fixed tick grid"));}let(path,origin)=self.decode(p.design)?;let t=path.tick(n-1,self.ticks)?;let (out,branches)=super::segment_quadrature::advance_with_branches(self.fluid,z,&p.design[..self.nd],SegmentTrace{origin_s:origin+(n-1)as f64*self.nominal_step_s(),clock:self.clock,sample_tick:self.first_tick+n-1,boundaries:&t.boundaries,start:&t.start,end:&t.end,midpoints:&t.midpoints,velocities_m_s:&t.velocities})?;let na=self.fluid.inner().sample_names().len();let mut samples=out.samples;for x in &mut samples[na..]{*x*=1./self.ticks as f64;}samples.extend_from_slice(&out.impulse_n_s);samples.extend_from_slice(&out.start_compensation_n_s);samples.extend_from_slice(&out.end_compensation_n_s);let mut work=dot(&out.start_compensation_n_s,&t.start_velocity)+dot(&out.end_compensation_n_s,&t.end_velocity);for(i,b)in branches.iter().enumerate(){work+=(t.boundaries[i+1]-t.boundaries[i])*(dot(&b.before_impulse_n_s,&t.velocities[i])+dot(&b.after_impulse_n_s,&t.velocities[i]));}samples.push(work);Ok(StepRecord{state:out.state,samples,ledger:BTreeMap::new(),diagnostics:StepDiagnostics::default()})}
 fn tangent(&self,n:usize,z:&[f64],c:&[f64],p:StepParameters<'_>,dz:&[f64],dd:Option<&[f64]>,dt:f64)->CaeResult<StepTangent>{if n==0||n>self.ticks||p.time_scale!=1.||dt!=0.||dz.len()!=self.state_size(){return Err(fail("carrier tangent native fixed tick/input shape"));}let zero=vec![0.;self.design_size()];let dd=dd.unwrap_or(&zero);let(path,origin)=self.decode(p.design)?;let(dpath,dorigin)=self.decode(dd)?;let t=path.tick(n-1,self.ticks)?;let d=dpath.tick(n-1,self.ticks)?;let boundaries=vec![0.;t.boundaries.len()];let out=super::segment_quadrature::direction(self.fluid,z,&p.design[..self.nd],SegmentTrace{origin_s:origin+(n-1)as f64*self.nominal_step_s(),clock:self.clock,sample_tick:self.first_tick+n-1,boundaries:&t.boundaries,start:&t.start,end:&t.end,midpoints:&t.midpoints,velocities_m_s:&t.velocities},SegmentDirection{origin_s:dorigin,boundaries:&boundaries,previous:dz,design:&dd[..self.nd],start:&d.start,end:&d.end,midpoints:&d.midpoints,velocities_m_s:&d.velocities})?;if out.primal.state.len()!=c.len()||out.primal.state.iter().zip(c).any(|(a,b)|a.to_bits()!=b.to_bits()){return Err(fail("carrier tangent primal endpoint differs"));}let q=out.direction;let mut samples=q.samples;let na=self.fluid.inner().sample_names().len();for x in &mut samples[na..]{*x*=1./self.ticks as f64;}samples.extend_from_slice(&q.impulse_n_s);samples.extend_from_slice(&q.start_compensation_n_s);samples.extend_from_slice(&q.end_compensation_n_s);samples.push(0.);Ok(StepTangent{state:q.state,samples})}
 fn adjoint(&self,n:usize,z:&[f64],c:&[f64],p:StepParameters<'_>,s:&[f64],b:&[f64])->CaeResult<StepCotangent>{if n==0||n>self.ticks||p.time_scale!=1.||b.len()!=self.names.len()||s.len()!=self.state_size()||b.iter().chain(s).any(|x|!x.is_finite())||*b.last().unwrap()!=0.{return Err(fail("carrier history bar shape or unsupported diagnostic work derivative"));}let check=self.advance(n,z,p)?;if check.state.len()!=c.len()||check.state.iter().zip(c).any(|(a,b)|a.to_bits()!=b.to_bits()){return Err(fail("carrier history replay endpoint differs"));}let(path,origin)=self.decode(p.design)?;let t=path.tick(n-1,self.ticks)?;let ns=self.fluid.sample_names().len();let na=self.fluid.inner().sample_names().len();let mut sample=b[..ns].to_vec();for x in &mut sample[na..]{*x*=1./self.ticks as f64;}let bar=SegmentOutput{state:s.to_vec(),impulse_n_s:b[ns..ns+self.nf].to_vec(),start_compensation_n_s:b[ns+self.nf..ns+2*self.nf].to_vec(),end_compensation_n_s:b[ns+2*self.nf..ns+3*self.nf].to_vec(),samples:sample};let fb=super::segment_quadrature::adjoint(self.fluid,z,&p.design[..self.nd],SegmentTrace{origin_s:origin+(n-1)as f64*self.nominal_step_s(),clock:self.clock,sample_tick:self.first_tick+n-1,boundaries:&t.boundaries,start:&t.start,end:&t.end,midpoints:&t.midpoints,velocities_m_s:&t.velocities},&bar)?;let mut dp=vec![0.;self.design_size()];add(&mut dp[..self.nd],&fb.design,1.);let zero=vec![0.;self.nf];let left=(n-1)as f64/self.ticks as f64;let right=n as f64/self.ticks as f64;self.scatter(left,&fb.start,&zero,&mut dp);self.scatter(right,&fb.end,&zero,&mut dp);for i in 0..t.midpoints.len(){let x=left+0.5*(t.boundaries[i]+t.boundaries[i+1])*(right-left);self.scatter(x,&fb.midpoints[i],&fb.velocities_m_s[i],&mut dp);}*dp.last_mut().unwrap()=fb.origin_s;Ok(StepCotangent{previous:fb.previous,design:dp,time_scale:0.})}
}
