// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use crate::moving_contact::contact_set_kinematics::ContactSetKinematics;
use implexity_core::{CaeError,CaeResult};
use implexity_linalg::dense::DenseMatrix;
use implexity_solve::{dynamic_program::DynamicProgram,multirate_coupling::{FluxDrivenField,SubcycledField},time_stepper::StepParameters};
use crate::{problem::time::TimeKind,moving_contact::{separate_body::MovingFsiPairModel,resources::PersistentContactFields,collection::MultipleContact,mapped_pair_law::MappedPairLaw,coupled_tick_primal::MultiContactNativeState,sample_projection::PairSampleProjection}};
use super::{macro_phase::MacroPhaseOutput,macro_reverse::{FixedMacroLinearization,MacroOutputBars,MacroBars}};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
fn add(a:&mut[f64],b:&[f64])->CaeResult<()>{if a.len()!=b.len(){return Err(fail("macro response cotangent layout"));}for(a,b)in a.iter_mut().zip(b){*a+=b;}Ok(())}
pub struct MacroWindowEntry<'a,'b>{pub global_macro:usize,pub previous:&'a MultiContactNativeState,pub output:&'a MacroPhaseOutput,pub linearization:&'a FixedMacroLinearization<'b>}
pub struct MacroWindowGradient{pub name:String,pub value:f64,pub initial:MacroBars,pub external:Vec<Vec<f64>>}
pub fn sample_names<L:ContactSetKinematics>(fields:&PersistentContactFields<'_,L>)->Vec<String>{fields.contact.sample_names().iter().chain(fields.fluid.sample_names()).cloned().collect()}
fn native_samples<L:ContactSetKinematics>(fields:&PersistentContactFields<'_,L>,design:&[f64],e:&MacroWindowEntry<'_,'_>)->CaeResult<Vec<f64>>{let mut out=fields.contact.samples(e.global_macro,&e.output.state.solid,&e.previous.solid,StepParameters{design,time_scale:1.})?;let s=e.linearization.carrier_run.samples();let n=fields.fluid.sample_names().len();if s.nrows!=e.output.fluid_ticks||s.ncols<n{return Err(fail("macro response replay sample layout"));}let mut fluid=vec![0.;n];for r in 0..s.nrows{for c in 0..n{fluid[c]+=s.get(r,c);}}out.extend(fluid);Ok(out)}
pub fn evaluate<L:ContactSetKinematics>(model:&MovingFsiPairModel,fields:&PersistentContactFields<'_,L>,design:&[f64],entries:&[MacroWindowEntry<'_,'_>],projection:&PairSampleProjection,program:&DynamicProgram)->CaeResult<Vec<MacroWindowGradient>>{
 if entries.is_empty(){return Err(fail("macro objective requires complete nonempty window"));}let a=model.native_body(0)?;let b=model.native_body(1)?;let autonomous=match (&a.problem.time.kind,&b.problem.time.kind){(TimeKind::FixedHorizon{autonomous:x,..},TimeKind::FixedHorizon{autonomous:y,..})if x==y=>*x,_=>return Err(fail("macro objective requires matching fixed horizons and autonomous declarations"))};let dt=a.problem.time.macro_step_s();let horizon=a.problem.time.history_steps();if dt.to_bits()!=b.problem.time.macro_step_s().to_bits()||horizon!=b.problem.time.history_steps()||entries.len()>horizon||!dt.is_finite()||dt<=0.{return Err(fail("macro objective authored horizon/cadence differs"));}let names=sample_names(fields);if projection.source_names()!=names{return Err(fail("macro objective projection source layout"));}
 let initial=entries[0].previous;for(i,e)in entries.iter().enumerate(){if e.global_macro!=i+1||e.output.macro_dt_s.to_bits()!=dt.to_bits()||e.output.state.origin_s.to_bits()!=(e.previous.origin_s+dt).to_bits(){return Err(fail("macro objective global indices/step ownership"));}if i>0{let p=&entries[i-1].output.state;if p.origin_s.to_bits()!=e.previous.origin_s.to_bits()||p.solid.len()!=e.previous.solid.len()||p.fluid.len()!=e.previous.fluid.len()||p.lagged_force_n.len()!=e.previous.lagged_force_n.len()||p.solid.iter().chain(&p.fluid).chain(&p.lagged_force_n).zip(e.previous.solid.iter().chain(&e.previous.fluid).chain(&e.previous.lagged_force_n)).any(|(a,b)|a.to_bits()!=b.to_bits()){return Err(fail("macro objective complete history state continuity"));}}}
 let kinds=["design_volume_fraction","removed_volume_fraction","removed_volume_m3","removal_depth_m"];let bound=program.bind(projection.names(),&kinds)?;bound.admit(entries.len(),false,autonomous)?;let mut samples=DenseMatrix::zeros(entries.len(),projection.names().len());for(i,e)in entries.iter().enumerate(){let y=projection.values(&native_samples(fields,design,e)?)?;let n=samples.ncols;samples.data[i*n..(i+1)*n].copy_from_slice(&y);}
 let zero=||MacroBars{solid:vec![0.;initial.solid.len()],fluid:vec![0.;initial.fluid.len()],lag:vec![0.;initial.lagged_force_n.len()],external:vec![0.;initial.lagged_force_n.len()],design:vec![0.;design.len()],origin_s:0.};let mut out=vec![];
 for(name,v)in bound.evaluate(&samples,dt,false,autonomous)?{if v.d_period_s!=0.{return Err(fail("fixed-horizon macro period derivative unsupported"));}let mut carry=zero();let mut external=vec![vec![0.;initial.lagged_force_n.len()];entries.len()];for i in (0..entries.len()).rev(){let e=&entries[i];let width=samples.ncols;let pb=projection.pullback(&v.d_samples.data[i*width..(i+1)*width])?;let ns=fields.contact.sample_names().len();let(sc,sp,sd)=fields.contact.samples_vjp(e.global_macro,&e.output.state.solid,&e.previous.solid,StepParameters{design,time_scale:1.},&pb[..ns])?;let mut solid=carry.solid.clone();add(&mut solid,&sc)?;let bars=MacroOutputBars{solid,fluid:carry.fluid.clone(),lag:carry.lag.clone(),samples:pb[ns..].to_vec(),origin_s:carry.origin_s};let mut g=e.linearization.adjoint(fields,design,&bars)?;add(&mut g.solid,&sp)?;add(&mut g.design,&sd)?;add(&mut g.design,&carry.design)?;external[i]=g.external.clone();g.external.fill(0.);carry=g;}out.push(MacroWindowGradient{name,value:v.value,initial:carry,external});}
 for(name,value,g)in model.event_design_terms(design,&bound)?{let mut bars=zero();bars.design=g;out.push(MacroWindowGradient{name,value,initial:bars,external:vec![vec![0.;initial.lagged_force_n.len()];entries.len()]});}Ok(out)
}
