// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use crate::moving_contact::contact_set_kinematics::ContactSetKinematics;
use std::{collections::BTreeMap,sync::Mutex};
use implexity_core::{CaeError,CaeResult};
use implexity_linalg::{dense::DenseMatrix,sparse::CsrMatrix};
use implexity_solve::{time_stepper::{TimeStepper,StepParameters,StepRecord,StepDiagnostics,StepTangent,StepCotangent},multirate_coupling::{FluxDrivenField,SubcycledField},checkpointed_history::{CheckpointPolicy,state_digest},state_store::StoreBudget,dynamic_program::DynamicProgram};
use crate::{problem::time::TimeKind,moving_contact::{separate_body::MovingFsiPairModel,resources::PersistentContactFields,collection::MultipleContact,mapped_pair_law::MappedPairLaw,coupled_tick_primal::MultiContactNativeState,history_branch::{ContactOwnerIdentity,ContactHistoryBranch},selected_transition::OnsetPolicy,segment_quadrature::SegmentClock,sample_projection::PairSampleProjection}};
use implexity_solve::checkpointed_history::{HistoryRun,run_history,history_adjoint_many};
use super::{avf_admission::AvfVelocityCertificate,macro_phase::{self,MacroPhaseOutput},macro_reverse::{MacroDirection,MacroOutputBars}};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
fn add(a:&mut[f64],b:&[f64])->CaeResult<()>{if a.len()!=b.len(){return Err(fail("checkpoint macro cotangent shape"));}for(a,b)in a.iter_mut().zip(b){*a+=b;}Ok(())}
#[derive(Clone,PartialEq)]struct Metadata{state_digest:[u64;2],branch:serde_json::Value,certificate:Option<serde_json::Value>}
pub struct CheckpointMacroStepper<'a,'b,L:ContactSetKinematics=MultipleContact<MappedPairLaw>>{pub fields:&'a PersistentContactFields<'b,L>,pub model:&'a MovingFsiPairModel,identity:String,names:Vec<String>,design:Vec<f64>,external:Vec<f64>,initial:Vec<f64>,owner:ContactOwnerIdentity,policy:OnsetPolicy,velocity:CsrMatrix,grid:usize,ticks:usize,horizon:usize,ns:usize,nfluid:usize,nf:usize,dt:f64,autonomous:bool,checkpoint:CheckpointPolicy,metadata:Mutex<BTreeMap<usize,Metadata>>,canonical_loose:Option<crate::moving_contact::canonical_loose_phase::LoosePhaseDriver<'a,'b,L>>,trace_lag_size:usize}
pub struct CheckpointControlGradient{pub name:String,pub value:f64,pub bodies:[Vec<f64>;2],pub initial_clock_s:f64,pub derivative_scope:&'static str}
#[derive(Clone)]
pub struct MacroHistoryArchive{identity:String,metadata:BTreeMap<usize,Metadata>}
pub struct RestrictedCheckpointControlGradient{pub name:String,pub value:f64,pub bodies:[Vec<f64>;2],pub derivative_scope:&'static str}
impl<'a,'b,L:ContactSetKinematics> CheckpointMacroStepper<'a,'b,L>{
 pub fn from_rest(model:&'a MovingFsiPairModel,fields:&'a PersistentContactFields<'b,L>,design:&[f64],external:&[f64],features:&serde_json::Value,source_graph:&str,velocity:CsrMatrix,policy:OnsetPolicy,grid:usize,ticks:usize)->CaeResult<Self>{
  let a=model.native_body(0)?;let b=model.native_body(1)?;let autonomous=match(&a.problem.time.kind,&b.problem.time.kind){(TimeKind::FixedHorizon{autonomous:x,..},TimeKind::FixedHorizon{autonomous:y,..})if x==y=>*x,_=>return Err(fail("checkpoint macro requires both native fixed horizons"))};let dt=a.problem.time.macro_step_s();let horizon=a.problem.time.history_steps();let checkpoint=a.problem.time.checkpoint.clone();if dt.to_bits()!=b.problem.time.macro_step_s().to_bits()||horizon!=b.problem.time.history_steps()||checkpoint!=b.problem.time.checkpoint||horizon==0||grid==0||ticks==0||!dt.is_finite()||dt<=0.||fields.contact.nominal_step_s().to_bits()!=dt.to_bits()||(fields.fluid.inner().nominal_fluid_step_s()*ticks as f64-dt).abs()>8.*f64::EPSILON*dt||design.len()!=fields.contact.design_size()||design.len()!=fields.fluid.design_size(){return Err(fail("checkpoint macro authored numerical policy/cadence/design differs"));}let ns=fields.contact.state_size();let nfluid=fields.fluid.state_size();let nf=fields.contact.trace_operator().nrows();if external.len()!=nf||external.iter().any(|v|!v.is_finite())||velocity.ncols()!=ns||velocity.nrows()!=nf{return Err(fail("checkpoint macro physical external/velocity ownership"));}
  let solid=fields.contact.initial_state(design)?;let fluid=fields.fluid.initial_state(design)?;let count=fields.contact.law().contact_count();if solid.len()!=ns||fluid.len()!=nfluid||solid[ns-count..].iter().any(|v|*v!=0.)||macro_phase::physical_uv(fields,&solid,design)?.1.iter().any(|v|*v!=0.){return Err(fail("checkpoint macro from-rest native state is not declared rest"));}let bound_features=fields.contact.law().bound_owner_features(features)?;let features=&bound_features;let owner=ContactOwnerIdentity::new(features,source_graph,design,1.,0.,policy)?;let branch=ContactHistoryBranch::from_selected(&owner,&vec![false;count],policy.residual_tolerance*policy.gap_target_fraction)?;let mut initial=solid.clone();initial.extend(fluid);initial.extend(vec![0.;nf]);initial.push(0.);let meta=Metadata{state_digest:state_digest(&initial),branch:branch.checkpoint(&solid)?,certificate:None};let mut metadata=BTreeMap::new();metadata.insert(0,meta);let names=super::macro_response::sample_names(fields);let identity=implexity_core::json::canonical_sha256(&serde_json::json!({"schema":"checkpointed-fixed-branch-pair-macro/1","source_graph":source_graph,"features":features,"body_problem_identities":[a.problem.identity(),b.problem.identity()],"design_sha256":implexity_core::json::sha256_hex(&design.iter().flat_map(|x|x.to_le_bytes()).collect::<Vec<_>>()),"external_sha256":implexity_core::json::sha256_hex(&external.iter().flat_map(|x|x.to_le_bytes()).collect::<Vec<_>>()),"grid":grid,"ticks":ticks,"checkpoint":format!("{:?}",checkpoint),"initial_branch":branch.checkpoint(&solid)?}));
  Ok(Self{fields,model,identity,names,design:design.to_vec(),external:external.to_vec(),initial,owner,policy,velocity,grid,ticks,horizon,ns,nfluid,nf,dt,autonomous,checkpoint,metadata:Mutex::new(metadata),canonical_loose:None,trace_lag_size:0})
 }

 pub fn from_rest_canonical_loose(model:&'a MovingFsiPairModel,fields:&'a PersistentContactFields<'b,L>,design:&[f64],external:&[f64],features:&serde_json::Value,source_graph:&str,velocity:CsrMatrix,policy:OnsetPolicy,grid:usize,ticks:usize)->CaeResult<Self>{
  let mut out=Self::from_rest(model,fields,design,external,features,source_graph,velocity,policy,grid,ticks)?;
  let driver=crate::moving_contact::canonical_loose_phase::LoosePhaseDriver::new(model,fields,design,features,source_graph,policy,grid)?;
  let state=driver.initial_state(design)?;out.trace_lag_size=state.trace_lags.len();out.identity=implexity_core::json::canonical_sha256(&serde_json::json!({"schema":"checkpointed-canonical-loose-contact-phases/1","base":out.identity,"trace_lag_size":out.trace_lag_size,"packed_work_counters":2}));out.initial=out.pack_canonical_loose(&state)?;let metadata=Metadata{state_digest:state_digest(&out.initial),branch:state.branch.checkpoint(&state.solid)?,certificate:None};*out.metadata.lock().map_err(|_|fail("checkpoint canonical loose metadata lock"))?=BTreeMap::from([(0,metadata)]);out.canonical_loose=Some(driver);Ok(out)
 }
 fn pack_canonical_loose(&self,state:&crate::moving_contact::canonical_loose_phase::LoosePhaseState)->CaeResult<Vec<f64>>{if state.solid.len()!=self.ns||state.fluid.len()!=self.nfluid||state.trace_lags.len()!=self.trace_lag_size{return Err(fail("checkpoint canonical loose endpoint layout"));}let mut out=state.solid.clone();out.extend(&state.fluid);out.extend(&state.trace_lags);out.push(state.cumulative_work_defect_j);out.push(state.cumulative_abs_body_work_j);out.push(state.origin_s);if out.iter().any(|v|!v.is_finite())||state.cumulative_abs_body_work_j<0.{return Err(fail("checkpoint canonical loose finite endpoint/work"));}Ok(out)}
 fn decode_canonical_loose(&self,n:usize,z:&[f64])->CaeResult<crate::moving_contact::canonical_loose_phase::LoosePhaseState>{
  if self.canonical_loose.is_none()||z.len()!=self.state_size()||z.iter().any(|v|!v.is_finite()){return Err(fail("checkpoint canonical loose complete finite state"));}let meta=self.metadata.lock().map_err(|_|fail("checkpoint canonical loose metadata lock"))?.get(&n).cloned().ok_or_else(||fail("checkpoint canonical loose branch/admission metadata missing"))?;if meta.state_digest!=state_digest(z){return Err(fail("checkpoint canonical loose state/metadata identity"));}let origin=*z.last().unwrap();if origin.to_bits()!=(n as f64*self.dt).to_bits(){return Err(fail("checkpoint canonical loose native global clock"));}let owner=self.owner.for_phase(1.,origin)?;let solid=z[..self.ns].to_vec();let branch=ContactHistoryBranch::restore(&meta.branch,&solid,&owner,self.fields.contact.law().contact_count(),self.policy.residual_tolerance*self.policy.gap_target_fraction)?;let certificate=meta.certificate.as_ref().map(|v|AvfVelocityCertificate::restore(v,&implexity_core::json::canonical_sha256(v),&solid,&owner,&branch.selected(),self.policy)).transpose()?;let tail=self.ns+self.nfluid+self.trace_lag_size;
  Ok(crate::moving_contact::canonical_loose_phase::LoosePhaseState{solid,fluid:z[self.ns..self.ns+self.nfluid].to_vec(),trace_lags:z[self.ns+self.nfluid..tail].to_vec(),origin_s:origin,branch,velocity_certificate:certificate,cumulative_work_defect_j:z[tail],cumulative_abs_body_work_j:z[tail+1]})
 }
 pub fn admit_canonical_native_interface(&self)->CaeResult<serde_json::Value>{self.canonical_loose.as_ref().ok_or_else(||fail("checkpoint owner is not canonical loose integration"))?.admit_native_interface(self.model,&self.design)}
 pub fn admit_canonical_interface(&self,modes:&[Vec<f64>],mass_action:&dyn Fn(&[f64])->Vec<f64>)->CaeResult<Vec<f64>>{let driver=self.canonical_loose.as_ref().ok_or_else(||fail("checkpoint owner is not canonical loose integration"))?;driver.admit_interface(&self.design,&self.decode_canonical_loose(0,&self.initial)?,modes,mass_action)}
 fn advance_canonical_loose(&self,n:usize,z:&[f64],p:StepParameters<'_>)->CaeResult<StepRecord>{
  self.check(n,p)?;let previous=self.decode_canonical_loose(n-1,z)?;let out=self.canonical_loose.as_ref().ok_or_else(||fail("canonical loose owner absent"))?.advance(n,&previous,p.design,&self.external)?;let state=self.pack_canonical_loose(&out.state)?;let meta=Metadata{state_digest:state_digest(&state),branch:out.state.branch.checkpoint(&out.state.solid)?,certificate:out.state.velocity_certificate.as_ref().map(|c|c.value(&out.state.solid)).transpose()?};let mut metadata=self.metadata.lock().map_err(|_|fail("checkpoint canonical loose metadata lock"))?;if let Some(old)=metadata.get(&n){if old!=&meta{return Err(fail("checkpoint canonical loose replay branch/certificate differs"));}}else{metadata.insert(n,meta);}drop(metadata);
  let mut samples=self.fields.contact.samples(n,&out.state.solid,&previous.solid,p)?;samples.extend(out.fluid_samples);let mut ledger=out.fluid_ledger;ledger.insert(implexity_solve::multirate_coupling::LEDGER_INTERFACE_WORK_A.into(),out.fluid_interface_work_j);ledger.insert(implexity_solve::multirate_coupling::LEDGER_INTERFACE_WORK_B.into(),out.body_interface_work_j);ledger.insert(implexity_solve::multirate_coupling::LEDGER_INTERFACE_WORK_DEFECT.into(),out.interface_work_defect_j);ledger.insert("cumulative_interface_work_defect_J".into(),out.state.cumulative_work_defect_j);ledger.insert("cumulative_abs_body_interface_work_J".into(),out.state.cumulative_abs_body_work_j);if let Some(r)=out.relative_cumulative_work_defect{ledger.insert("relative_cumulative_interface_work_defect".into(),r);}if let Some(a)=out.terminal_work_admission{ledger.insert("terminal_interface_work_admitted".into(),if a{1.}else{0.});}let mut diagnostics=out.fluid_diagnostics;diagnostics.newton_iterations+=out.phases.records.iter().map(|r|r.result.iterations).sum::<usize>();diagnostics.coupling_iterations=1;
  Ok(StepRecord{state,samples,ledger,diagnostics})
 }
 fn check(&self,n:usize,p:StepParameters<'_>)->CaeResult<()>{if n==0||n>self.horizon||p.time_scale!=1.||p.design.len()!=self.design.len()||p.design.iter().zip(&self.design).any(|(a,b)|a.to_bits()!=b.to_bits()){return Err(fail("checkpoint macro exact fixed design/global index"));}Ok(())}
 fn decode(&self,n:usize,z:&[f64])->CaeResult<(MultiContactNativeState,Option<AvfVelocityCertificate>,ContactOwnerIdentity)>{if self.canonical_loose.is_some(){return Err(fail("canonical loose predictor-history derivative/replay adapter is not yet qualified"));}if z.len()!=self.state_size()||z.iter().any(|v|!v.is_finite()){return Err(fail("checkpoint macro full finite state"));}let meta=self.metadata.lock().map_err(|_|fail("checkpoint macro metadata lock"))?.get(&n).cloned().ok_or_else(||fail("checkpoint macro missing typed branch/admission metadata"))?;if meta.state_digest!=state_digest(z){return Err(fail("checkpoint macro state/metadata binding differs"));}let origin=*z.last().unwrap();let owner=self.owner.for_phase(1.,origin)?;let solid=z[..self.ns].to_vec();let count=self.fields.contact.law().contact_count();let branch=ContactHistoryBranch::restore(&meta.branch,&solid,&owner,count,self.policy.residual_tolerance*self.policy.gap_target_fraction)?;let certificate=meta.certificate.as_ref().map(|v|AvfVelocityCertificate::restore(v,&implexity_core::json::canonical_sha256(v),&solid,&owner,&branch.selected(),self.policy)).transpose()?;Ok((MultiContactNativeState{solid,fluid:z[self.ns..self.ns+self.nfluid].to_vec(),lagged_force_n:z[self.ns+self.nfluid..self.ns+self.nfluid+self.nf].to_vec(),origin_s:origin,branch},certificate,owner))}
 fn pack(&self,s:&MultiContactNativeState)->CaeResult<Vec<f64>>{if s.solid.len()!=self.ns||s.fluid.len()!=self.nfluid||s.lagged_force_n.len()!=self.nf{return Err(fail("checkpoint macro native endpoint shape"));}let mut z=s.solid.clone();z.extend(&s.fluid);z.extend(&s.lagged_force_n);z.push(s.origin_s);if z.iter().any(|v|!v.is_finite()){return Err(fail("checkpoint macro finite packed endpoint"));}Ok(z)}
 fn evaluate_step(&self,n:usize,z:&[f64],p:StepParameters<'_>)->CaeResult<(MultiContactNativeState,ContactOwnerIdentity,MacroPhaseOutput)>{self.check(n,p)?;let(previous,cert,owner)=self.decode(n-1,z)?;let out=macro_phase::advance(self.fields,&previous,p.design,&self.external,1,self.ticks,&owner,&self.velocity,self.policy,self.grid,SegmentClock::NativeTickEnd,cert.as_ref())?;let packed=self.pack(&out.state)?;let meta=Metadata{state_digest:state_digest(&packed),branch:out.state.branch.checkpoint(&out.state.solid)?,certificate:Some(out.phases.velocity_certificate.value(&out.state.solid)?)};let mut metadata=self.metadata.lock().map_err(|_|fail("checkpoint macro metadata lock"))?;if let Some(old)=metadata.get(&n){if old!=&meta{return Err(fail("checkpoint macro branch/admission replay differs"));}}else{metadata.insert(n,meta);}Ok((previous,owner,out))}
 pub fn checkpoint_metadata(&self)->CaeResult<serde_json::Value>{let metadata=self.metadata.lock().map_err(|_|fail("checkpoint macro metadata lock"))?;Ok(serde_json::json!({"schema":"checkpointed-macro-branch-admission-metadata/1","owner_identity":self.identity,"entries":metadata.iter().map(|(n,m)|serde_json::json!({"global_macro":n,"packed_state_digest":m.state_digest,"branch":m.branch,"certificate":m.certificate})).collect::<Vec<_>>()}))}
 pub fn restore_metadata(&self,payload:&serde_json::Value,trusted_payload_sha256:&str)->CaeResult<()>{if implexity_core::json::canonical_sha256(payload)!=trusted_payload_sha256||payload.as_object().map(|o|o.len())!=Some(3)||payload["schema"]!="checkpointed-macro-branch-admission-metadata/1"||payload["owner_identity"]!=self.identity{return Err(fail("checkpoint macro trusted metadata identity"));}let entries=payload["entries"].as_array().ok_or_else(||fail("checkpoint macro metadata entries"))?;if entries.is_empty()||entries.len()>self.horizon+1{return Err(fail("checkpoint macro metadata horizon"));}let mut incoming=BTreeMap::new();for e in entries{if e.as_object().map(|o|o.len())!=Some(4){return Err(fail("checkpoint macro metadata entry keys"));}let n=e["global_macro"].as_u64().filter(|n|*n<=self.horizon as u64).ok_or_else(||fail("checkpoint macro metadata global index"))?as usize;let d=e["packed_state_digest"].as_array().filter(|d|d.len()==2).ok_or_else(||fail("checkpoint macro metadata digest"))?;let state_digest=[d[0].as_u64().ok_or_else(||fail("checkpoint macro digest lane"))?,d[1].as_u64().ok_or_else(||fail("checkpoint macro digest lane"))?];let certificate=if e["certificate"].is_null(){None}else{Some(e["certificate"].clone())};if incoming.insert(n,Metadata{state_digest,branch:e["branch"].clone(),certificate}).is_some(){return Err(fail("checkpoint macro duplicate metadata index"));}}let mut metadata=self.metadata.lock().map_err(|_|fail("checkpoint macro metadata lock"))?;if incoming.get(&0)!=metadata.get(&0){return Err(fail("checkpoint macro native rest metadata differs"));}for(n,m)in &incoming{if let Some(old)=metadata.get(n){if old!=m{return Err(fail("checkpoint macro existing metadata differs"));}}}metadata.extend(incoming);Ok(())}
 pub fn admit_initial_derivative(&self)->CaeResult<()>{let count=self.fields.contact.law().contact_count();let selected=self.decode(0,&self.initial)?.0.branch.selected();let gaps=self.fields.contact.law().scaled_gap_rows(&self.initial[..self.ns],&self.design)?.0;if gaps.len()!=count||selected.iter().enumerate().any(|(k,a)|if *a{self.initial[self.ns-count+k]<=0.}else{gaps[k]<=0.}){return Err(fail("checkpoint macro rest is biactive/grazing; ordinary topology gradient requires a qualified localized event owner"));}Ok(())}
 pub fn run(&self)->CaeResult<HistoryRun>{run_history(self,StepParameters{design:&self.design,time_scale:1.},&self.initial,1,Some(self.horizon),None,self.checkpoint.clone(),&StoreBudget::from_environment()?)}
 pub fn evaluate_program(&self,run:&HistoryRun,projection:&PairSampleProjection,program:&DynamicProgram)->CaeResult<BTreeMap<String,f64>>{self.evaluate_program_mode(run,projection,program,true)}
 pub fn evaluate_forward_program(&self,run:&HistoryRun,projection:&PairSampleProjection,program:&DynamicProgram)->CaeResult<BTreeMap<String,f64>>{self.evaluate_program_mode(run,projection,program,false)}
 fn evaluate_program_mode(&self,run:&HistoryRun,projection:&PairSampleProjection,program:&DynamicProgram,require_fixed_period_pullback:bool)->CaeResult<BTreeMap<String,f64>>{
  self.adopt_archive(&self.archive()?,run)?;if projection.source_names()!=self.sample_names(){return Err(fail("macro forward response sample ownership differs"));}let source=run.samples();let mut samples=DenseMatrix::zeros(source.nrows,projection.names().len());for r in 0..source.nrows{let row=projection.values(&source.data[r*source.ncols..(r+1)*source.ncols])?;let n=samples.ncols;samples.data[r*n..(r+1)*n].copy_from_slice(&row);}
  let bound=program.bind(projection.names(),&["design_volume_fraction","removed_volume_fraction","removed_volume_m3","removal_depth_m"])?;bound.admit(self.horizon,false,self.autonomous)?;let values=bound.evaluate(&samples,self.dt,false,self.autonomous)?;let mut responses=BTreeMap::new();for(n,x)in values{if require_fixed_period_pullback&&x.d_period_s!=0.{return Err(fail("fixed-horizon functional period derivative unavailable"));}responses.insert(n,x.value);}for(n,x,_)in self.model.event_design_terms(&self.design,&bound)?{responses.insert(n,x);}Ok(responses)
 }
 pub fn archive(&self)->CaeResult<MacroHistoryArchive>{Ok(MacroHistoryArchive{identity:self.identity.clone(),metadata:self.metadata.lock().map_err(|_|fail("macro metadata mutex"))?.clone()})}
 pub fn adopt_archive(&self,archive:&MacroHistoryArchive,run:&HistoryRun)->CaeResult<()>{if archive.identity!=self.identity||run.record()["stepper"]!=self.identity||run.first_step()!=1||run.steps()!=self.horizon||state_digest(run.initial_state())!=state_digest(&self.initial)||archive.metadata.get(&0).map(|m|m.state_digest)!=Some(state_digest(&self.initial))||archive.metadata.get(&self.horizon).map(|m|m.state_digest)!=Some(state_digest(run.final_state())){return Err(fail("macro history archive source/design/state/window binding"));}*self.metadata.lock().map_err(|_|fail("macro metadata mutex"))?=archive.metadata.clone();Ok(())}
 pub fn controls(&self,controls:[&[f64];2],projection:&PairSampleProjection,program:&DynamicProgram,run:&HistoryRun)->CaeResult<Vec<CheckpointControlGradient>>{
  self.admit_initial_derivative()?;let design=self.model.event_physical_design(controls)?;if design.len()!=self.design.len()||design.iter().zip(&self.design).any(|(a,b)|a.to_bits()!=b.to_bits())||run.first_step()!=1||run.steps()!=self.horizon||run.initial_state().iter().zip(&self.initial).any(|(a,b)|a.to_bits()!=b.to_bits())||run.initial_state().len()!=self.initial.len()||projection.source_names()!=self.names{return Err(fail("checkpoint macro original full-window/control binding"));}let kinds=["design_volume_fraction","removed_volume_fraction","removed_volume_m3","removal_depth_m"];let bound=program.bind(projection.names(),&kinds)?;bound.admit(run.steps(),false,self.autonomous)?;let source=run.samples();let mut samples=DenseMatrix::zeros(source.nrows,projection.names().len());for r in 0..source.nrows{let row=projection.values(&source.data[r*source.ncols..(r+1)*source.ncols])?;let n=samples.ncols;samples.data[r*n..(r+1)*n].copy_from_slice(&row);}let mut out=vec![];let split=self.model.native_body(0)?.chain.len();
  let values=bound.evaluate(&samples,self.dt,false,self.autonomous)?;let mut sample_bars=vec![];let mut terminals=vec![];for(_,v)in &values{if v.d_period_s!=0.{return Err(fail("checkpoint macro fixed-horizon period derivative unavailable"));}let mut bars=DenseMatrix::zeros(source.nrows,source.ncols);for r in 0..source.nrows{let x=projection.pullback(&v.d_samples.data[r*samples.ncols..(r+1)*samples.ncols])?;bars.data[r*source.ncols..(r+1)*source.ncols].copy_from_slice(&x);}sample_bars.push(bars);terminals.push(vec![0.;self.state_size()]);}
  let gradients=history_adjoint_many(self,StepParameters{design:&design,time_scale:1.},run,&sample_bars,&terminals)?;for((name,v),mut g)in values.into_iter().zip(gradients){add(&mut g.design,&self.initial_state_vjp(&design,&g.initial_state)?)?;if g.time_scale!=0.{return Err(fail("checkpoint macro fixed-time derivative unavailable"));}let a=self.model.native_body(0)?.chain.pullback(controls[0],&g.design[..split])?;let b=self.model.native_body(1)?.chain.pullback(controls[1],&g.design[split..])?;out.push(CheckpointControlGradient{name,value:v.value,bodies:[a,b],initial_clock_s:*g.initial_state.last().unwrap(),derivative_scope:"ordinary_fixed_branch_from_rest"});}
  for(name,value,g)in self.model.event_design_terms(&design,&bound)?{out.push(CheckpointControlGradient{name,value,bodies:[self.model.native_body(0)?.chain.pullback(controls[0],&g[..split])?,self.model.native_body(1)?.chain.pullback(controls[1],&g[split..])?],initial_clock_s:0.,derivative_scope:"explicit_design_term"});}Ok(out)
 }
 pub fn controls_restricted_unloaded_initial_design(&self,controls:[&[f64];2],projection:&PairSampleProjection,program:&DynamicProgram,run:&HistoryRun)->CaeResult<Vec<RestrictedCheckpointControlGradient>>{
  let design=self.model.event_physical_design(controls)?;if design.len()!=self.design.len()||design.iter().zip(&self.design).any(|(a,b)|a.to_bits()!=b.to_bits())||run.first_step()!=1||run.steps()!=self.horizon||run.initial_state().iter().zip(&self.initial).any(|(a,b)|a.to_bits()!=b.to_bits())||run.initial_state().len()!=self.initial.len()||projection.source_names()!=self.names{return Err(fail("checkpoint macro original full-window/control binding"));}let kinds=["design_volume_fraction","removed_volume_fraction","removed_volume_m3","removal_depth_m"];let bound=program.bind(projection.names(),&kinds)?;bound.admit(run.steps(),false,self.autonomous)?;let source=run.samples();let mut samples=DenseMatrix::zeros(source.nrows,projection.names().len());for r in 0..source.nrows{let row=projection.values(&source.data[r*source.ncols..(r+1)*source.ncols])?;let n=samples.ncols;samples.data[r*n..(r+1)*n].copy_from_slice(&row);}let mut out=vec![];let split=self.model.native_body(0)?.chain.len();
  let values=bound.evaluate(&samples,self.dt,false,self.autonomous)?;let mut sample_bars=vec![];let mut terminals=vec![];for(_,v)in &values{if v.d_period_s!=0.{return Err(fail("checkpoint macro fixed-horizon period derivative unavailable"));}let mut bars=DenseMatrix::zeros(source.nrows,source.ncols);for r in 0..source.nrows{let x=projection.pullback(&v.d_samples.data[r*samples.ncols..(r+1)*samples.ncols])?;bars.data[r*source.ncols..(r+1)*source.ncols].copy_from_slice(&x);}sample_bars.push(bars);terminals.push(vec![0.;self.state_size()]);}
  let prefix=RestInitialControlPullback{stepper:self};let gradients=implexity_solve::checkpointed_history::history_control_pullback_many(self,StepParameters{design:&design,time_scale:1.},run,&sample_bars,&terminals,&prefix)?;for((name,v),g)in values.into_iter().zip(gradients){let a=self.model.native_body(0)?.chain.pullback(controls[0],&g.design[..split])?;let b=self.model.native_body(1)?.chain.pullback(controls[1],&g.design[split..])?;out.push(RestrictedCheckpointControlGradient{name,value:v.value,bodies:[a,b],derivative_scope:"design_only_unloaded_initial_prefix_then_ordinary_fixed_branch_suffix"});}
  for(name,value,g)in self.model.event_design_terms(&design,&bound)?{out.push(RestrictedCheckpointControlGradient{name,value,bodies:[self.model.native_body(0)?.chain.pullback(controls[0],&g[..split])?,self.model.native_body(1)?.chain.pullback(controls[1],&g[split..])?],derivative_scope:"explicit_design_term"});}Ok(out)
 }
}
impl<L:ContactSetKinematics> TimeStepper for CheckpointMacroStepper<'_,'_,L>{
 fn identity(&self)->&str{&self.identity}fn state_size(&self)->usize{if self.canonical_loose.is_some(){self.ns+self.nfluid+self.trace_lag_size+3}else{self.ns+self.nfluid+self.nf+1}}fn design_size(&self)->usize{self.design.len()}fn sample_names(&self)->&[String]{&self.names}fn nominal_step_s(&self)->f64{self.dt}
 fn initial_state(&self,design:&[f64])->CaeResult<Vec<f64>>{self.check(1,StepParameters{design,time_scale:1.})?;Ok(self.initial.clone())}
 fn initial_state_vjp(&self,design:&[f64],bar:&[f64])->CaeResult<Vec<f64>>{if self.canonical_loose.is_some(){return Err(fail("canonical loose initial/control derivative is not yet qualified"));}self.check(1,StepParameters{design,time_scale:1.})?;if bar.len()!=self.state_size()||bar.iter().any(|v|!v.is_finite()){return Err(fail("checkpoint macro initial full-state cotangent"));}let mut g=self.fields.contact.initial_state_vjp(design,&bar[..self.ns])?;add(&mut g,&self.fields.fluid.initial_state_vjp(design,&bar[self.ns..self.ns+self.nfluid])?)?;Ok(g)}
 fn advance(&self,n:usize,z:&[f64],p:StepParameters<'_>)->CaeResult<StepRecord>{if self.canonical_loose.is_some(){return self.advance_canonical_loose(n,z,p);}let(previous,_,out)=self.evaluate_step(n,z,p)?;let mut samples=self.fields.contact.samples(n,&out.state.solid,&previous.solid,p)?;samples.extend(&out.samples);let mut ledger=BTreeMap::new();ledger.insert("body_lagged_work_J".into(),out.body_lagged_work_j);ledger.insert("external_work_J".into(),out.external_work_j);ledger.insert("native_fluid_reaction_work_J".into(),out.native_fluid_reaction_work_j);ledger.insert("lagged_work_defect_J".into(),out.lagged_work_defect_j);Ok(StepRecord{state:self.pack(&out.state)?,samples,ledger,diagnostics:StepDiagnostics::default()})}
 fn tangent(&self,n:usize,z:&[f64],current:&[f64],p:StepParameters<'_>,dz:&[f64],dd:Option<&[f64]>,time:f64)->CaeResult<StepTangent>{if dz.len()!=self.state_size()||time!=0.{return Err(fail("checkpoint macro tangent full fixed-time input"));}let(previous,owner,out)=self.evaluate_step(n,z,p)?;let packed=self.pack(&out.state)?;if packed.len()!=current.len()||packed.iter().zip(current).any(|(a,b)|a.to_bits()!=b.to_bits()){return Err(fail("checkpoint macro tangent endpoint replay differs"));}let j=super::streamed_macro_reverse::linearize(self.fields,&previous,p.design,&self.external,&out,&owner,self.policy,1,SegmentClock::NativeTickEnd,self.checkpoint.clone(),&self.identity)?;let zero=vec![0.;self.design_size()];let dd=dd.unwrap_or(&zero);let d=MacroDirection{solid:dz[..self.ns].to_vec(),fluid:dz[self.ns..self.ns+self.nfluid].to_vec(),lag:dz[self.ns+self.nfluid..self.ns+self.nfluid+self.nf].to_vec(),external:vec![0.;self.nf],design:dd.to_vec(),origin_s:*dz.last().unwrap()};let t=j.tangent(self.fields,&previous,p.design,&d)?;let mut samples=vec![];for k in 0..self.fields.contact.sample_names().len(){let mut b=vec![0.;self.fields.contact.sample_names().len()];b[k]=1.;let(a,z,g)=self.fields.contact.samples_vjp(n,&out.state.solid,&previous.solid,p,&b)?;samples.push(a.iter().zip(&t.solid).map(|(a,b)|a*b).sum::<f64>()+z.iter().zip(&d.solid).map(|(a,b)|a*b).sum::<f64>()+g.iter().zip(dd).map(|(a,b)|a*b).sum::<f64>());}samples.extend(t.samples);let mut state=t.solid;state.extend(t.fluid);state.extend(t.lag);state.push(t.origin_s);Ok(StepTangent{state,samples})}
 fn adjoint(&self,n:usize,z:&[f64],current:&[f64],p:StepParameters<'_>,state_bar:&[f64],sample_bar:&[f64])->CaeResult<StepCotangent>{let mut out=self.adjoint_many(n,z,current,p,&[state_bar.to_vec()],&[sample_bar.to_vec()])?;Ok(out.remove(0))}
 fn adjoint_many(&self,n:usize,z:&[f64],current:&[f64],p:StepParameters<'_>,state_bars:&[Vec<f64>],sample_bars:&[Vec<f64>])->CaeResult<Vec<StepCotangent>>{
  if state_bars.len()!=sample_bars.len(){return Err(fail("checkpoint macro reverse batch size"));}for(state_bar,sample_bar)in state_bars.iter().zip(sample_bars){if state_bar.len()!=self.state_size()||sample_bar.len()!=self.names.len()||state_bar.iter().chain(sample_bar).any(|v|!v.is_finite()){return Err(fail("checkpoint macro adjoint complete finite bars"));}}if state_bars.is_empty(){return Ok(vec![]);}let(previous,owner,out)=self.evaluate_step(n,z,p)?;let packed=self.pack(&out.state)?;if packed.len()!=current.len()||packed.iter().zip(current).any(|(a,b)|a.to_bits()!=b.to_bits()){return Err(fail("checkpoint macro adjoint endpoint replay differs"));}let j=super::streamed_macro_reverse::linearize(self.fields,&previous,p.design,&self.external,&out,&owner,self.policy,1,SegmentClock::NativeTickEnd,self.checkpoint.clone(),&self.identity)?;let na=self.fields.contact.sample_names().len();let mut result=vec![];
  let mut rhs=vec![];let mut direct=vec![];for(state_bar,sample_bar)in state_bars.iter().zip(sample_bars){let(sc,sp,sd)=self.fields.contact.samples_vjp(n,&out.state.solid,&previous.solid,p,&sample_bar[..na])?;let mut solid=state_bar[..self.ns].to_vec();add(&mut solid,&sc)?;rhs.push(MacroOutputBars{solid,fluid:state_bar[self.ns..self.ns+self.nfluid].to_vec(),lag:state_bar[self.ns+self.nfluid..self.ns+self.nfluid+self.nf].to_vec(),samples:sample_bar[na..].to_vec(),origin_s:*state_bar.last().unwrap()});direct.push((sp,sd));}let gradients=j.adjoint_many(self.fields,p.design,&rhs)?;for(g,(sp,sd))in gradients.into_iter().zip(direct){let mut previous=g.solid;add(&mut previous,&sp)?;previous.extend(g.fluid);previous.extend(g.lag);previous.push(g.origin_s);let mut design=g.design;add(&mut design,&sd)?;result.push(StepCotangent{previous,design,time_scale:0.});}Ok(result)
 }
}

struct RestInitialControlPullback<'a,'b,'c,L:ContactSetKinematics>{stepper:&'a CheckpointMacroStepper<'b,'c,L>}
impl<L:ContactSetKinematics> implexity_solve::checkpointed_history::InitialControlPullback for RestInitialControlPullback<'_,'_,'_,L>{
 fn design_pullback(&self,stepper:&dyn TimeStepper,p:StepParameters<'_>,previous:&[f64],current:&[f64],state_bars:&[Vec<f64>],sample_bars:&[Vec<f64>])->CaeResult<Vec<Vec<f64>>>{
  let f=self.stepper;if stepper.identity()!=f.identity()||previous.len()!=f.initial.len()||previous.iter().zip(&f.initial).any(|(a,b)|a.to_bits()!=b.to_bits())||state_bars.len()!=sample_bars.len(){return Err(fail("restricted from-rest control pullback owner/initial state differs"));}let(z,_,out)=f.evaluate_step(1,previous,p)?;let packed=f.pack(&out.state)?;if packed.len()!=current.len()||packed.iter().zip(current).any(|(a,b)|a.to_bits()!=b.to_bits()){return Err(fail("restricted from-rest prefix full native replay differs"));}let prefix=super::rest_design_prefix::UnloadedRestDesignPrefix::bind(f.model,f.fields,&z,p.design,&f.external,&out,&f.identity,f.checkpoint.clone())?;let na=f.fields.contact.sample_names().len();let mut result=vec![];
  for(sb,ob)in state_bars.iter().zip(sample_bars){if sb.len()!=f.state_size()||ob.len()!=f.names.len()||sb.iter().chain(ob).any(|v|!v.is_finite()){return Err(fail("restricted from-rest complete output bars"));}let(_,_,direct)=f.fields.contact.samples_vjp(1,&out.state.solid,&z.solid,p,&ob[..na])?;let bar=MacroOutputBars{solid:sb[..f.ns].to_vec(),fluid:sb[f.ns..f.ns+f.nfluid].to_vec(),lag:sb[f.ns+f.nfluid..f.ns+f.nfluid+f.nf].to_vec(),samples:ob[na..].to_vec(),origin_s:*sb.last().unwrap()};let mut g=prefix.design_pullback(f.fields,&bar)?;add(&mut g,&direct)?;result.push(g);}Ok(result)
 }
}
