// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use crate::moving_contact::contact_set_kinematics::ContactSetKinematics;
use implexity_core::{CaeError,CaeResult};
use implexity_linalg::sparse::CsrMatrix;
use implexity_solve::{multirate_coupling::{FluxDrivenField,SubcycledField},time_stepper::StepParameters};
use super::{resources::PersistentContactFields,collection::MultipleContact,mapped_pair_law::MappedPairLaw,history_branch::{ContactOwnerIdentity,ContactHistoryBranch},selected_transition::OnsetPolicy,coupled_tick_primal::MultiContactNativeState,phase_subdivision::{PhaseHistory,advance_constant_flux_phases},segment_quadrature::{SegmentClock,SegmentTrace}};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
fn dot(a:&[f64],b:&[f64])->f64{a.iter().zip(b).map(|(a,b)|a*b).sum()}
fn add(a:&mut[f64],b:&[f64]){for(a,b)in a.iter_mut().zip(b){*a+=b;}}
fn blend(a:&[f64],b:&[f64],t:f64)->Vec<f64>{a.iter().zip(b).map(|(a,b)|(1.-t)*a+t*b).collect()}
pub struct MacroPhaseOutput{pub state:MultiContactNativeState,pub phases:PhaseHistory,pub samples:Vec<f64>,pub accumulated_reaction_n_s:Vec<f64>,pub body_lagged_work_j:f64,pub external_work_j:f64,pub native_fluid_reaction_work_j:f64,pub lagged_work_defect_j:f64,pub fluid_ticks:usize,pub body_phase_solves:usize,pub macro_dt_s:f64,pub fluid_dt_s:f64}
pub struct CarrierPath{pub displacement:Vec<Vec<f64>>,pub velocity:Vec<Vec<f64>>,pub duration_s:f64}
pub struct TickCarrier{pub start:Vec<f64>,pub end:Vec<f64>,pub midpoints:Vec<Vec<f64>>,pub velocities:Vec<Vec<f64>>,pub start_velocity:Vec<f64>,pub end_velocity:Vec<f64>,pub boundaries:Vec<f64>}
pub fn physical_uv<L:ContactSetKinematics>(fields:&PersistentContactFields<'_,L>,state:&[f64],design:&[f64])->CaeResult<(Vec<f64>,Vec<f64>)>{let(mut u,mut v)=(vec![],vec![]);let(mut offset,mut dp)=(0,0);for b in 0..2{let f=fields.contact.native().body_field(b)?;let n=f.state_size();let nd=f.design_size();if offset+n>state.len()||dp+nd>design.len(){return Err(fail("macro phase native prefix layout"));}let h=f.core().history(StepParameters{design:&design[dp..dp+nd],time_scale:1.})?;let p=f.core().to_physical(&state[offset..offset+n]);u.extend_from_slice(&p[h.layout.u()..h.layout.u()+h.layout.n3]);v.extend_from_slice(&p[h.layout.v()..h.layout.v()+h.layout.n3]);offset+=n;dp+=nd;}if offset!=fields.contact.law().native_states()||dp!=design.len(){return Err(fail("macro phase independent body ownership"));}Ok((u,v))}
pub fn carrier_path<L:ContactSetKinematics>(fields:&PersistentContactFields<'_,L>,previous:&[f64],phases:&PhaseHistory,design:&[f64])->CaeResult<CarrierPath>{let(a,b)=physical_uv(fields,previous,design)?;let mut p=CarrierPath{displacement:vec![a],velocity:vec![b],duration_s:phases.total_duration_s};for r in &phases.records{let(a,b)=physical_uv(fields,&r.result.state,design)?;p.displacement.push(a);p.velocity.push(b);}Ok(p)}
impl CarrierPath{
 pub fn at(&self,t:f64)->CaeResult<(Vec<f64>,Vec<f64>)>{let n=self.displacement.len().checked_sub(1).ok_or_else(||fail("macro carrier empty path"))?;if n==0||self.velocity.len()!=n+1||!self.duration_s.is_finite()||self.duration_s<=0.||!t.is_finite()||!(0. ..=1.).contains(&t){return Err(fail("macro carrier normalized position"));}let k=((t*n as f64).floor()as usize).min(n-1);let f=(t*n as f64-k as f64).clamp(0.,1.);Ok((blend(&self.displacement[k],&self.displacement[k+1],f),self.displacement[k+1].iter().zip(&self.displacement[k]).map(|(b,a)|(b-a)/(self.duration_s/n as f64)).collect()))}
 pub fn tick(&self,k:usize,ticks:usize)->CaeResult<TickCarrier>{if ticks==0||k>=ticks{return Err(fail("macro carrier tick index"));}let grid=self.displacement.len()-1;let left=k as f64/ticks as f64;let right=(k+1)as f64/ticks as f64;let mut b=vec![0.];for j in 1..grid{let x=j as f64/grid as f64;if x>left&&x<right{b.push((x-left)/(right-left));}}b.push(1.);let(start,start_velocity)=self.at(left)?;let(end,end_velocity)=self.at(right)?;let(mut midpoints,mut velocities)=(vec![],vec![]);for w in b.windows(2){let t=left+0.5*(w[0]+w[1])*(right-left);let(u,v)=self.at(t)?;midpoints.push(u);velocities.push(v);}Ok(TickCarrier{start,end,midpoints,velocities,start_velocity,end_velocity,boundaries:b})}
}
pub fn advance<L:ContactSetKinematics>(fields:&PersistentContactFields<'_,L>,previous:&MultiContactNativeState,design:&[f64],external:&[f64],first_sample_tick:usize,fluid_ticks:usize,owner:&ContactOwnerIdentity,velocity_trace:&CsrMatrix,policy:OnsetPolicy,grid:usize,clock:SegmentClock,previous_certificate:Option<&super::avf_admission::AvfVelocityCertificate>)->CaeResult<MacroPhaseOutput>{
 super::avf_admission::require_avf(&fields.contact,design,1.)?;let dt=fields.contact.nominal_step_s();let df=fields.fluid.inner().nominal_fluid_step_s();let nf=fields.contact.trace_operator().nrows();let extent=df*fluid_ticks as f64;
 if fluid_ticks==0||first_sample_tick==0||first_sample_tick.checked_add(fluid_ticks-1).is_none()||!dt.is_finite()||dt<=0.||!df.is_finite()||df<=0.||(extent-dt).abs()>8.*f64::EPSILON*dt||previous.solid.len()!=fields.contact.state_size()||previous.fluid.len()!=fields.fluid.state_size()||previous.lagged_force_n.len()!=nf||external.len()!=nf||previous.fluid.iter().chain(&previous.lagged_force_n).chain(external).any(|x|!x.is_finite()){return Err(fail("macro phase authored body/fluid cadence or layout"));}
 owner.check_clock(previous.origin_s)?;owner.check_parameters(design,1.,policy)?;let force:Vec<_>=previous.lagged_force_n.iter().zip(external).map(|(a,b)|a+b).collect();let mut observe=|_r:&super::phase_subdivision::PhaseRecord|{Ok(())};
 let phases=advance_constant_flux_phases(&fields.contact,&previous.solid,&force,StepParameters{design,time_scale:1.},velocity_trace,policy,&previous.branch,owner,previous.origin_s,grid,&mut observe,previous_certificate)?;
 if phases.total_duration_s.to_bits()!=dt.to_bits()||phases.records.len()!=grid{return Err(fail("macro phase body cadence identity"));}
 let path=carrier_path(fields,&previous.solid,&phases,design)?;let mut population=previous.fluid.clone();let mut reaction=vec![0.;nf];let mut samples=vec![0.;fields.fluid.sample_names().len()];let mut fluid_work=0.;let na=fields.fluid.inner().sample_names().len();
 for k in 0..fluid_ticks{let t=path.tick(k,fluid_ticks)?;let origin=previous.origin_s+k as f64*df;let (out,branches)=super::segment_quadrature::advance_with_branches(&fields.fluid,&population,design,SegmentTrace{origin_s:origin,clock,sample_tick:first_sample_tick+k,boundaries:&t.boundaries,start:&t.start,end:&t.end,midpoints:&t.midpoints,velocities_m_s:&t.velocities})?;add(&mut reaction,&out.impulse_n_s);add(&mut reaction,&out.start_compensation_n_s);add(&mut reaction,&out.end_compensation_n_s);for(j,x)in out.samples.iter().enumerate(){samples[j]+=*x*if j<na{1.}else{1./fluid_ticks as f64};}fluid_work+=dot(&out.start_compensation_n_s,&t.start_velocity)+dot(&out.end_compensation_n_s,&t.end_velocity);for(j,b)in branches.iter().enumerate(){let w=t.boundaries[j+1]-t.boundaries[j];fluid_work+=w*(dot(&b.before_impulse_n_s,&t.velocities[j])+dot(&b.after_impulse_n_s,&t.velocities[j]));}population=out.state;}
 let lag:Vec<_>=reaction.iter().map(|x|x/dt).collect();let du:Vec<_>=path.displacement.last().unwrap().iter().zip(&path.displacement[0]).map(|(a,b)|a-b).collect();let body=dot(&previous.lagged_force_n,&du);let ext=dot(external,&du);let end=previous.origin_s+dt;let next_owner=owner.for_phase(1.,end)?;let branch=ContactHistoryBranch::from_selected(&next_owner,&phases.final_branch.selected(),policy.residual_tolerance*policy.gap_target_fraction)?;
 if !end.is_finite()||lag.iter().chain(&samples).any(|x|!x.is_finite())||![body,ext,fluid_work].iter().all(|x|x.is_finite()){return Err(fail("macro phase native finite ledger/state"));}
 Ok(MacroPhaseOutput{state:MultiContactNativeState{solid:phases.final_state.clone(),fluid:population,lagged_force_n:lag,origin_s:end,branch},phases,samples,accumulated_reaction_n_s:reaction,body_lagged_work_j:body,external_work_j:ext,native_fluid_reaction_work_j:fluid_work,lagged_work_defect_j:body-fluid_work,fluid_ticks,body_phase_solves:grid,macro_dt_s:dt,fluid_dt_s:df})
}
