// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use crate::moving_contact::contact_set_kinematics::ContactSetKinematics;
use implexity_core::{CaeError,CaeResult};
use implexity_solve::{multirate_coupling::{FluxDrivenField,SubcycledField},time_stepper::StepParameters,checkpointed_history::{HistoryRun,CheckpointPolicy},time_stepper::TimeStepper};
use super::{resources::PersistentContactFields,collection::MultipleContact,mapped_pair_law::MappedPairLaw,coupled_tick_primal::MultiContactNativeState,history_branch::{ContactOwnerIdentity,ContactHistoryBranch},selected_transition::OnsetPolicy,selected_derivative::{SelectedContactLinearization,SelectedContactDirection,contact_set_selected_linearization,require_history_branch_preserved},macro_phase::{MacroPhaseOutput,CarrierPath,carrier_path,physical_uv},carrier_history::{CarrierFluidStepper,CarrierHistoryBars},segment_quadrature::SegmentClock};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
fn add(a:&mut[f64],b:&[f64]){for(a,b)in a.iter_mut().zip(b){*a+=b;}}
pub struct MacroBars{pub solid:Vec<f64>,pub fluid:Vec<f64>,pub lag:Vec<f64>,pub external:Vec<f64>,pub design:Vec<f64>,pub origin_s:f64}
pub struct MacroDirection{pub solid:Vec<f64>,pub fluid:Vec<f64>,pub lag:Vec<f64>,pub external:Vec<f64>,pub design:Vec<f64>,pub origin_s:f64}
pub struct MacroOutputBars{pub solid:Vec<f64>,pub fluid:Vec<f64>,pub lag:Vec<f64>,pub samples:Vec<f64>,pub origin_s:f64}
pub struct FixedMacroLinearization<'a>{pub body:Vec<SelectedContactLinearization>,pub carrier:CarrierFluidStepper<'a>,pub carrier_parameters:Vec<f64>,pub carrier_run:HistoryRun,pub macro_dt_s:f64,pub state_size:usize,pub design_size:usize,pub flux_size:usize,pub base_endpoint_samples:Vec<f64>}
pub(crate) fn displacement_bar<L:ContactSetKinematics>(fields:&PersistentContactFields<'_,L>,design:&[f64],u:&[f64])->CaeResult<Vec<f64>>{let(mut out,mut off,mut dp,mut q)=(vec![0.;fields.contact.state_size()],0,0,0);for b in 0..2{let f=fields.contact.native().body_field(b)?;let h=f.core().history(StepParameters{design:&design[dp..dp+f.design_size()],time_scale:1.})?;if q+h.layout.n3>u.len(){return Err(fail("macro physical trace cotangent shape"));}for i in 0..h.layout.n3{out[off+h.layout.u()+i]=u[q+i]/f.core().scale()[h.layout.u()+i];}off+=f.state_size();dp+=f.design_size();q+=h.layout.n3;}if q!=u.len(){return Err(fail("macro physical trace cotangent ownership"));}Ok(out)}
pub fn linearize<'a,L:ContactSetKinematics>(fields:&'a PersistentContactFields<'_,L>,previous:&MultiContactNativeState,design:&[f64],external:&[f64],base:&MacroPhaseOutput,owner:&ContactOwnerIdentity,policy:OnsetPolicy,first_tick:usize,clock:SegmentClock,checkpoint_policy:CheckpointPolicy)->CaeResult<FixedMacroLinearization<'a>>{
 let identity=implexity_core::json::canonical_sha256(&serde_json::json!({"native_contact_checkpoint":previous.branch.checkpoint(&previous.solid)?,"macro_dt_bits":format!("{:016x}",base.macro_dt_s.to_bits()),"fluid_dt_bits":format!("{:016x}",base.fluid_dt_s.to_bits())}));linearize_bound(fields,previous,design,external,base,owner,policy,first_tick,clock,checkpoint_policy,&identity)
}
pub fn linearize_bound<'a,L:ContactSetKinematics>(fields:&'a PersistentContactFields<'_,L>,previous:&MultiContactNativeState,design:&[f64],external:&[f64],base:&MacroPhaseOutput,owner:&ContactOwnerIdentity,policy:OnsetPolicy,first_tick:usize,clock:SegmentClock,checkpoint_policy:CheckpointPolicy,source_model_identity:&str)->CaeResult<FixedMacroLinearization<'a>>{
 if source_model_identity.len()!=64||!source_model_identity.bytes().all(|c|c.is_ascii_hexdigit()){return Err(fail("macro derivative source/model identity"));}
 let n=fields.contact.law().native_states();let count=fields.contact.law().contact_count();if previous.solid.len()!=fields.contact.state_size()||design.len()!=fields.contact.design_size()||external.len()!=previous.lagged_force_n.len()||external.iter().chain(design).any(|x|!x.is_finite())||base.phases.records.is_empty(){return Err(fail("macro derivative complete input shape"));}
 require_history_branch_preserved(&previous.branch,&base.state.branch)?;let mut selected=previous.branch.selected();let gaps=fields.contact.law().scaled_gap_rows(&previous.solid,design)?.0;for k in 0..count{if (selected[k]&&previous.solid[n+k]<=0.)||(!selected[k]&&gaps[k]<=0.){return Err(fail("macro derivative input tie or grazing"));}}
 let force:Vec<_>=previous.lagged_force_n.iter().zip(external).map(|(a,b)|a+b).collect();let mut body=vec![];
 for r in &base.phases.records{if selected!=r.result.active{return Err(fail("macro branch transition requires localized event derivative"));}let phase_owner=owner.for_phase(r.time_scale,r.begin_s)?;let next=ContactHistoryBranch::from_selected(&phase_owner.advance_clock(fields.contact.nominal_step_s()*r.time_scale)?,&r.result.active,r.result.numerical_target)?;body.push(contact_set_selected_linearization(&fields.contact,&r.previous,&force,StepParameters{design,time_scale:r.time_scale},policy,&r.result,&phase_owner,&next)?);selected=r.result.active.clone();}
 let path=carrier_path(fields,&previous.solid,&base.phases,design)?;let replay_identity=implexity_core::json::canonical_sha256(&serde_json::json!({"source_model_identity":source_model_identity,"native_contact_checkpoint":previous.branch.checkpoint(&previous.solid)?,"macro_dt_bits":format!("{:016x}",base.macro_dt_s.to_bits()),"fluid_dt_bits":format!("{:016x}",base.fluid_dt_s.to_bits()),"body_phases":base.body_phase_solves,"fluid_ticks":base.fluid_ticks}));let carrier=CarrierFluidStepper::new(&fields.fluid,base.fluid_ticks,first_tick,&path,design.len(),clock,&replay_identity)?;let parameters=carrier.parameters(design,&path,previous.origin_s)?;let run=carrier.run(&previous.fluid,&parameters,checkpoint_policy)?;
 if run.final_state().len()!=base.state.fluid.len()||run.final_state().iter().zip(&base.state.fluid).any(|(a,b)|a.to_bits()!=b.to_bits()){return Err(fail("macro carrier checkpoint replay differs from captured primal"));}
 Ok(FixedMacroLinearization{body,carrier,carrier_parameters:parameters,carrier_run:run,macro_dt_s:base.macro_dt_s,state_size:previous.solid.len(),design_size:design.len(),flux_size:previous.lagged_force_n.len(),base_endpoint_samples:base.samples.clone()})
}
impl FixedMacroLinearization<'_>{
 pub fn tangent<L:ContactSetKinematics>(&self,fields:&PersistentContactFields<'_,L>,previous:&MultiContactNativeState,design:&[f64],d:&MacroDirection)->CaeResult<MacroOutputBars>{
 if d.solid.len()!=self.state_size||d.fluid.len()!=previous.fluid.len()||d.lag.len()!=self.flux_size||d.external.len()!=self.flux_size||d.design.len()!=self.design_size||d.solid.iter().chain(&d.fluid).chain(&d.lag).chain(&d.external).chain(&d.design).any(|x|!x.is_finite())||!d.origin_s.is_finite(){return Err(fail("macro complete finite direction"));}
 let force:Vec<_>=d.lag.iter().zip(&d.external).map(|(a,b)|a+b).collect();let mut states=vec![d.solid.clone()];for j in &self.body{states.push(j.tangent(&SelectedContactDirection{previous:states.last().unwrap().clone(),flux:force.clone(),design:d.design.clone(),time_scale:0.})?);}
 let mut displacement=vec![];for x in &states{displacement.push(physical_uv(fields,x,design)?.0);}let path=CarrierPath{velocity:vec![vec![0.;self.flux_size];states.len()],displacement,duration_s:self.macro_dt_s};let dp=self.carrier.parameters(&d.design,&path,d.origin_s)?;let mut fluid=previous.fluid.clone();let mut df=d.fluid.clone();let mut samples=vec![0.;self.base_endpoint_samples.len()];let mut impulse=vec![0.;self.flux_size];let p=StepParameters{design:&self.carrier_parameters,time_scale:1.};
 for n in 1..=self.carrier_run.steps(){let out=self.carrier.advance(n,&fluid,p)?;let q=self.carrier.tangent(n,&fluid,&out.state,p,&df,Some(&dp),0.)?;for(a,b)in samples.iter_mut().zip(&q.samples){*a+=b;}for k in 0..3{let off=samples.len()+k*self.flux_size;add(&mut impulse,&q.samples[off..off+self.flux_size]);}fluid=out.state;df=q.state;}
 Ok(MacroOutputBars{solid:states.pop().unwrap(),fluid:df,lag:impulse.into_iter().map(|x|x/self.macro_dt_s).collect(),samples,origin_s:d.origin_s})
 }

 pub fn adjoint<L:ContactSetKinematics>(&self,fields:&PersistentContactFields<'_,L>,design:&[f64],bar:&MacroOutputBars)->CaeResult<MacroBars>{
  if bar.solid.len()!=self.state_size||bar.fluid.len()!=fields.fluid.state_size()||bar.lag.len()!=self.flux_size||bar.samples.len()!=self.base_endpoint_samples.len()||bar.solid.iter().chain(&bar.fluid).chain(&bar.lag).chain(&bar.samples).any(|x|!x.is_finite())||!bar.origin_s.is_finite(){return Err(fail("macro output cotangent finite shape"));}
  let impulse:Vec<_>=bar.lag.iter().map(|x|x/self.macro_dt_s).collect();let CarrierHistoryBars{fluid,design:mut db,displacement,origin_s}=self.carrier.pullback(&self.carrier_run,&self.carrier_parameters,&bar.fluid,&bar.samples,&impulse)?;let mut states=vec![vec![0.;self.state_size];self.body.len()+1];if displacement.len()!=states.len(){return Err(fail("macro carrier/body phase count"));}
  for (s,u)in states.iter_mut().zip(&displacement){add(s,&displacement_bar(fields,design,u)?);}add(states.last_mut().unwrap(),&bar.solid);let mut force=vec![0.;self.flux_size];for i in(0..self.body.len()).rev(){let b=self.body[i].adjoint(&states[i+1])?;add(&mut states[i],&b.previous);add(&mut force,&b.flux);add(&mut db,&b.design);}
  Ok(MacroBars{solid:states.remove(0),fluid,lag:force.clone(),external:force,design:db,origin_s:bar.origin_s+origin_s})
 }
}
