// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use crate::moving_contact::contact_set_kinematics::ContactSetKinematics;
use implexity_core::{CaeError,CaeResult};
use implexity_solve::{multirate_coupling::{FluxDrivenField,SubcycledField},checkpointed_history::{CheckpointPolicy,HistoryRun}};
use crate::moving_contact::{separate_body::MovingFsiPairModel,resources::PersistentContactFields,collection::MultipleContact,mapped_pair_law::MappedPairLaw,coupled_tick_primal::MultiContactNativeState,segment_quadrature::SegmentClock};
use super::{macro_phase::{MacroPhaseOutput,carrier_path},macro_reverse::MacroOutputBars,carrier_history::CarrierFluidStepper};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
fn zero(x:&[f64])->bool{x.iter().all(|v|v.is_finite()&&*v==0.)}
pub struct UnloadedRestDesignPrefix<'a>{carrier:CarrierFluidStepper<'a>,parameters:Vec<f64>,run:HistoryRun,nd:usize,ns:usize,nf:usize,dt:f64,identity:String}
impl<'a> UnloadedRestDesignPrefix<'a>{
 pub fn bind<L:ContactSetKinematics>(model:&MovingFsiPairModel,fields:&'a PersistentContactFields<'_,L>,previous:&MultiContactNativeState,design:&[f64],external:&[f64],base:&MacroPhaseOutput,source_model_identity:&str,checkpoint:CheckpointPolicy)->CaeResult<Self>{
  if source_model_identity.len()!=64||!source_model_identity.bytes().all(|x|x.is_ascii_hexdigit())||design.len()!=fields.contact.design_size()||design.iter().any(|v|!v.is_finite())||previous.solid.len()!=fields.contact.state_size()||previous.lagged_force_n.len()!=fields.contact.trace_operator().nrows()||external.len()!=previous.lagged_force_n.len()||!zero(&previous.solid)||!zero(&previous.lagged_force_n)||!zero(external)||previous.origin_s!=0.||previous.branch.selected().iter().any(|v|*v)||!fields.contact.law().fixed_reference_geometry(){return Err(fail("restricted rest design prefix requires exact unloaded native reference state and fixed reference features"));}
  for i in 0..2{let b=model.native_body(i)?;if !std::ptr::eq(fields.contact.native().body_field(i)?.core().model(),&b.soft){return Err(fail("restricted rest prefix native body/model ownership differs"));}if !fields.contact.native().body_field(i)?.core().model().potentials.is_empty(){return Err(fail("restricted rest design prefix requires intrinsic unforced material reference without auxiliary nodal potentials"));}if !b.problem.solid.contact_planes.is_empty()||b.problem.solid.supports.iter().any(|s|s.motion.is_some()){return Err(fail("restricted rest design prefix excludes plane potentials and prescribed support motion"));}}
  if !zero(&fields.contact.initial_state(design)?)||fields.fluid.initial_state(design)?.iter().zip(&previous.fluid).any(|(a,b)|a.to_bits()!=b.to_bits())||previous.fluid.len()!=fields.fluid.state_size()||base.phases.records.is_empty()||!base.macro_dt_s.is_finite()||base.macro_dt_s<=0.||!zero(&base.state.solid)||base.phases.records.iter().any(|r|!zero(&r.previous)||!zero(&r.result.state)||r.result.active.iter().any(|v|*v)||r.result.original_residual_norm!=0.){return Err(fail("restricted rest design prefix requires actual zero-state phase replay"));}
  let gaps=fields.contact.law().scaled_gap_rows(&previous.solid,design)?.0;if gaps.iter().any(|g|!g.is_finite()||*g<0.){return Err(fail("restricted rest design prefix initial geometry intersects"));}let dg=fields.contact.law().scaled_gap_design_rows(&previous.solid,design)?.to_csr()?;if dg.data().iter().any(|v|*v!=0.){return Err(fail("restricted rest design prefix reference contact geometry depends on design"));}
  let path=carrier_path(fields,&previous.solid,&base.phases,design)?;if path.displacement.iter().chain(&path.velocity).any(|v|!zero(v)){return Err(fail("restricted rest design prefix native carrier is not fixed at reference"));}
  let identity=implexity_core::json::canonical_sha256(&serde_json::json!({"schema":"unloaded-native-rest-design-manifold/1","source_model_identity":source_model_identity,"body_identities":[model.native_body(0)?.problem.identity(),model.native_body(1)?.problem.identity()],"design_sha256":implexity_core::json::sha256_hex(&design.iter().flat_map(|v|v.to_le_bytes()).collect::<Vec<_>>()),"initial_solid_sha256":implexity_core::json::sha256_hex(&previous.solid.iter().flat_map(|v|v.to_le_bytes()).collect::<Vec<_>>()),"macro_dt_bits":format!("{:016x}",base.macro_dt_s.to_bits()),"fluid_ticks":base.fluid_ticks,"body_phases":base.body_phase_solves,"scope":"design-only fixed-reference unloaded from-rest prefix; no ambient state/force/lag derivative"}));
  let carrier=CarrierFluidStepper::new(&fields.fluid,base.fluid_ticks,1,&path,design.len(),SegmentClock::NativeTickEnd,&identity)?;let parameters=carrier.parameters(design,&path,0.)?;let run=carrier.run(&previous.fluid,&parameters,checkpoint)?;if run.final_state().len()!=base.state.fluid.len()||run.final_state().iter().zip(&base.state.fluid).any(|(a,b)|a.to_bits()!=b.to_bits()){return Err(fail("restricted rest design prefix native fluid replay differs"));}Ok(Self{carrier,parameters,run,nd:design.len(),ns:previous.solid.len(),nf:previous.lagged_force_n.len(),dt:base.macro_dt_s,identity})
 }
 pub fn identity(&self)->&str{&self.identity}
 pub fn design_pullback<L:ContactSetKinematics>(&self,fields:&PersistentContactFields<'_,L>,bar:&MacroOutputBars)->CaeResult<Vec<f64>>{
  if bar.solid.len()!=self.ns||bar.fluid.len()!=fields.fluid.state_size()||bar.lag.len()!=self.nf||bar.samples.len()!=fields.fluid.sample_names().len()||bar.solid.iter().chain(&bar.fluid).chain(&bar.lag).chain(&bar.samples).any(|v|!v.is_finite())||!bar.origin_s.is_finite(){return Err(fail("restricted rest design prefix complete output cotangent shape"));}
  let impulse:Vec<_>=bar.lag.iter().map(|v|v/self.dt).collect();let mut c=self.carrier.pullback(&self.run,&self.parameters,&bar.fluid,&bar.samples,&impulse)?;let initial=fields.fluid.initial_state_vjp(&self.parameters[..self.nd],&c.fluid)?;if c.design.len()!=self.nd||initial.len()!=self.nd{return Err(fail("restricted rest design prefix native initial pullback shape"));}for(a,b)in c.design.iter_mut().zip(initial){*a+=b;}Ok(c.design)
 }
}
