// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use crate::moving_contact::contact_set_kinematics::ContactSetKinematics;
use implexity_core::{CaeError,CaeResult};
pub use crate::moving_contact::selected_transition::{OnsetPolicy,OnsetResult};
use implexity_solve::{multirate_coupling::FluxDrivenField,time_stepper::StepParameters};
use implexity_linalg::sparse::CsrMatrix;
use implexity_solve::{factorization::Factorization,local_condensation::LocalEliminationPartition};
use crate::moving_contact::{contact_field::ContactField,mapped_pair_law::MappedPairLaw};
use crate::moving_contact::collection::MultipleContact;
fn fail(s:impl std::fmt::Display)->CaeError{CaeError::contract(s.to_string())}
fn norm(r:&[f64])->f64{r.iter().map(|v|v.abs()).fold(0.,f64::max)}
fn assembled_residual<L:ContactSetKinematics>(field:&ContactField<crate::moving_contact::separate_body::PairSolidField<'_>,L>,x:&[f64],previous:&[f64],flux:&[f64],p:StepParameters<'_>,active:&[bool],inverse:&[f64],target:f64)->CaeResult<(Vec<f64>,Vec<f64>,f64)>{let original=field.residual(1,x,previous,flux,p)?;let(mut r,gaps)=(original.clone(),field.law().scaled_gap_rows(x,p.design)?.0);let n=field.law().native_states();for k in 0..active.len(){r[n+k]=if active[k]{gaps[k]-target}else{-x[n+k]*inverse[k]};}if r.iter().chain(&gaps).any(|v|!v.is_finite()){return Err(fail("contact onset residual overflow"));}Ok((r,gaps,norm(&original)))}
fn solve_contact_transition_with_branch<L:ContactSetKinematics>(field:&ContactField<crate::moving_contact::separate_body::PairSolidField<'_>,L>,previous:&[f64],flux:&[f64],p:StepParameters<'_>,velocity_trace:&CsrMatrix,policy:OnsetPolicy,previous_active:Option<&[bool]>,previous_certificate:Option<&crate::moving_contact::macro_control::avf_admission::AvfVelocityCertificate>,owner_identity:&crate::moving_contact::history_branch::ContactOwnerIdentity)->CaeResult<(OnsetResult,Vec<f64>)>{
 if !policy.normal_velocity_tolerance_m_s.is_finite()||policy.normal_velocity_tolerance_m_s<0.||velocity_trace.ncols()!=field.state_size()||velocity_trace.nrows()!=field.trace_operator().nrows()||!policy.residual_tolerance.is_finite()||policy.residual_tolerance<=0.||!policy.gap_target_fraction.is_finite()||!(0. ..=0.5).contains(&policy.gap_target_fraction)||policy.maximum_newton_iterations==0||policy.maximum_active_set_iterations==0||!p.time_scale.is_finite()||p.time_scale<=0.||previous.len()!=field.state_size()||previous.iter().chain(flux).any(|v|!v.is_finite()){return Err(fail("contact onset explicit policy/state"));}
 let n=field.law().native_states();let count=field.law().contact_count();let partition=field.local_elimination_groups()?.map(|groups|LocalEliminationPartition::new(n+count,groups).map_err(fail)).transpose()?;let inverse=field.law().inverse_force_scales(previous,p)?;let previous_gaps=field.law().scaled_gap_rows(previous,p.design)?.0;let previous_velocity=velocity_trace.matvec(previous).map_err(fail)?;let previous_normal=field.law().normal_velocities(previous,p.design,&previous_velocity)?;let mut active:Vec<bool>=match previous_active{Some(a)=>{if a.len()!=count||(0..count).any(|k|!a[k]&&previous[n+k]*inverse[k]>policy.residual_tolerance){return Err(fail("contact predecessor branch/residual disagreement"));}a.to_vec()},None=>(0..count).map(|k|previous[n+k]>0.||previous_gaps[k]==0.).collect()};let previous_admission=if let Some(c)=previous_certificate{c.check(previous,owner_identity,&active,policy)?;c.transported().to_vec()}else{previous_normal.clone()};if (0..count).any(|k|previous[n+k]<0.||active[k]&&(previous_gaps[k]>policy.residual_tolerance||previous_admission[k]< -policy.normal_velocity_tolerance_m_s)){return Err(fail("closed contact transition requires a nonclosing admitted event/rest predecessor"));}let target=policy.residual_tolerance*policy.gap_target_fraction;let mut x=previous.to_vec();
 for iteration in 0..policy.maximum_newton_iterations{
  let(r,gaps,physical)=assembled_residual(field,&x,previous,flux,p,&active,&inverse,target)?;
  if norm(&r)<=policy.residual_tolerance&&physical<=policy.residual_tolerance&&gaps.iter().all(|g|*g>=0.)&&x[n..].iter().all(|l|*l>=0.){field.check_state_domain(1,&x,previous,p)?;let velocity=velocity_trace.matvec(&x).map_err(fail)?;let normals=field.law().normal_velocities(&x,p.design,&velocity)?;field.law().residual_path_certificates(previous,&x,p.design,policy.residual_tolerance)?;let transported=crate::moving_contact::macro_control::avf_admission::transported(field,previous,&x,p,velocity_trace)?;let admission:Vec<_>=(0..count).map(|k|if previous_active.map(|a|a[k]).unwrap_or(false)&&previous[n+k]>0.&&active[k]&&x[n+k]>0.{transported[k]}else{normals[k]}).collect();if (0..count).any(|k|active[k]&&(x[n+k]<=0.||admission[k]< -policy.normal_velocity_tolerance_m_s)){if physical<=policy.residual_tolerance&&x[n..].iter().all(|l|*l==0.)&&normals.iter().all(|v|v.abs()<=policy.normal_velocity_tolerance_m_s){return Ok((OnsetResult{state:x,active:vec![false;count],scaled_gaps:gaps,original_residual_norm:physical,numerical_target:target,iterations:iteration,normal_velocities_m_s:normals},admission));}return Err(fail("contact transition closing velocity or unsupported active multiplier"));}return Ok((OnsetResult{state:x,active,scaled_gaps:gaps,original_residual_norm:physical,numerical_target:target,iterations:iteration,normal_velocities_m_s:normals},admission));}
  let current=field.current_jacobian(1,&x,previous,flux,p)?.to_csr()?;let gap_rows=field.law().scaled_gap_rows(&x,p.design)?.1.to_csr()?;let mut selected=None;
  for _ in 0..policy.maximum_active_set_iterations{
   let(r,_,_)=assembled_residual(field,&x,previous,flux,p,&active,&inverse,target)?;let(mut ri,mut ci,mut vs)=(vec![],vec![],vec![]);for i in 0..n{let(js,v)=current.row(i);for(&j,&a)in js.iter().zip(v){ri.push(i);ci.push(j);vs.push(a);}}for k in 0..count{if active[k]{let(js,v)=gap_rows.row(k);for(&j,&a)in js.iter().zip(v){ri.push(n+k);ci.push(j);vs.push(a);}}else{ri.push(n+k);ci.push(n+k);vs.push(-inverse[k]);}}
   let matrix=CsrMatrix::from_triplets(n+count,n+count,&ri,&ci,&vs).map_err(fail)?;let factor=Factorization::correction_with_partition(implexity_solve::matrix::Jacobian::Csr(matrix),n+count,None,partition.as_ref())?;let direction=factor.solve(&r.iter().map(|v|-v).collect::<Vec<_>>(),false)?.0;let trial:Vec<_>=x.iter().zip(&direction).map(|(a,b)|a+b).collect();let trial_gap=field.law().scaled_gap_rows(&trial,p.design)?.0;let mut changed=false;for k in 0..count{if active[k]&&trial[n+k]<0.{active[k]=false;changed=true;}else if !active[k]&&trial_gap[k]<0.{if previous_gaps[k]>0.&&previous[n+k]==0.{return Err(fail("open contact needs localized physical impulse before closed transition"));}active[k]=true;changed=true;}}if !changed{selected=Some(direction);break;}
  }
  let direction=selected.ok_or_else(||fail("contact onset cone/active set did not settle"))?;let mut alpha=field.admissible_step(1,&x,&direction,previous,p,1.)?;if alpha<=0.{return Err(fail("contact onset native/continuous-path refusal"));}let old_merit=norm(&assembled_residual(field,&x,previous,flux,p,&active,&inverse,target)?.0);let mut next=None;
  for _ in 0..24{alpha=field.admissible_step(1,&x,&direction,previous,p,alpha)?;if alpha<=0.{return Err(fail("contact transition complete-path refinement refused"));}let trial:Vec<_>=x.iter().zip(&direction).map(|(a,b)|a+alpha*b).collect();if trial.iter().all(|v|v.is_finite())&&trial[n..].iter().all(|v|*v>=0.){let rr=assembled_residual(field,&trial,previous,flux,p,&active,&inverse,target)?.0;if norm(&rr)<old_merit{next=Some(trial);break;}}alpha*=0.5;}
  x=next.ok_or_else(||fail("contact onset original-law residual/merit trial refused"))?;
 }
 Err(fail("contact onset native Newton iteration limit"))
}

pub fn solve_contact_history_transition<L:ContactSetKinematics>(field:&ContactField<crate::moving_contact::separate_body::PairSolidField<'_>,L>,previous:&[f64],flux:&[f64],p:StepParameters<'_>,velocity_trace:&CsrMatrix,policy:OnsetPolicy,branch:&crate::moving_contact::history_branch::ContactHistoryBranch,owner_identity:&crate::moving_contact::history_branch::ContactOwnerIdentity,previous_certificate:Option<&crate::moving_contact::macro_control::avf_admission::AvfVelocityCertificate>)->CaeResult<(OnsetResult,crate::moving_contact::history_branch::ContactHistoryBranch,crate::moving_contact::macro_control::avf_admission::AvfVelocityCertificate)>{crate::moving_contact::macro_control::avf_admission::require_avf(field,p.design,p.time_scale)?;owner_identity.check_parameters(p.design,p.time_scale,policy)?;branch.check_binding(owner_identity,field.law().contact_count(),policy.residual_tolerance*policy.gap_target_fraction)?;let selected=branch.selected();let (result,transported)=solve_contact_transition_with_branch(field,previous,flux,p,velocity_trace,policy,Some(&selected),previous_certificate,owner_identity)?;let next=crate::moving_contact::history_branch::ContactHistoryBranch::from_selected(&owner_identity.advance_clock(field.nominal_step_s()*p.time_scale)?,&result.active,result.numerical_target)?;let certificate=crate::moving_contact::macro_control::avf_admission::certificate(next.clone(),&result.state,p.time_scale,transported,result.normal_velocities_m_s.clone());Ok((result,next,certificate))}
