// SPDX-License-Identifier: Apache-2.0
// METAPLEXIS-DISCLAIMER-BEGIN sha256=c7c02258f245d1dcd6db1e8066ef4f6bc1bf36430d91bf9aab026671723c058f
// Open-access statement and disclaimer: see DISCLAIMER.md.
// METAPLEXIS-DISCLAIMER-END

use crate::moving_contact::contact_set_kinematics::ContactSetKinematics;
use implexity_core::{CaeError,CaeResult};
use implexity_solve::{multirate_coupling::{FluxDrivenField,SubcycledField},time_stepper::{StepParameters,TimeStepper},checkpointed_history::{CheckpointPolicy,HistoryRun}};
use super::{resources::PersistentContactFields,collection::MultipleContact,mapped_pair_law::MappedPairLaw,coupled_tick_primal::MultiContactNativeState,history_branch::{ContactOwnerIdentity,ContactHistoryBranch},selected_transition::OnsetPolicy,selected_derivative::{SelectedContactLinearization,SelectedContactDirection,contact_set_selected_linearization,require_history_branch_preserved},macro_phase::{MacroPhaseOutput,CarrierPath,carrier_path,physical_uv},carrier_history::{CarrierFluidStepper,CarrierHistoryBars},segment_quadrature::SegmentClock,macro_reverse::{MacroBars,MacroDirection,MacroOutputBars,displacement_bar}};
fn fail(s:&str)->CaeError{CaeError::contract(s)}
fn add(a:&mut[f64],b:&[f64])->CaeResult<()>{if a.len()!=b.len(){return Err(fail("streamed macro cotangent shape"));}for(a,b)in a.iter_mut().zip(b){*a+=b;}Ok(())}
pub struct StreamedMacroLinearization<'a>{pub carrier:CarrierFluidStepper<'a>,pub carrier_parameters:Vec<f64>,pub carrier_run:HistoryRun,base:&'a MacroPhaseOutput,owner:ContactOwnerIdentity,force:Vec<f64>,policy:OnsetPolicy,state_size:usize,design_size:usize,flux_size:usize}
pub fn linearize<'a,L:ContactSetKinematics>(fields:&'a PersistentContactFields<'_,L>,previous:&MultiContactNativeState,design:&[f64],external:&[f64],base:&'a MacroPhaseOutput,owner:&ContactOwnerIdentity,policy:OnsetPolicy,first_tick:usize,clock:SegmentClock,checkpoint_policy:CheckpointPolicy,source_model_identity:&str)->CaeResult<StreamedMacroLinearization<'a>>{
 if source_model_identity.len()!=64||!source_model_identity.bytes().all(|c|c.is_ascii_hexdigit())||previous.solid.len()!=fields.contact.state_size()||design.len()!=fields.contact.design_size()||external.len()!=previous.lagged_force_n.len()||external.iter().chain(design).any(|x|!x.is_finite())||base.phases.records.is_empty(){return Err(fail("streamed macro derivative source/input shape"));}owner.check_clock(previous.origin_s)?;owner.check_parameters(design,1.,policy)?;require_history_branch_preserved(&previous.branch,&base.state.branch)?;let selected=previous.branch.selected();let n=fields.contact.law().native_states();let count=fields.contact.law().contact_count();let gaps=fields.contact.law().scaled_gap_rows(&previous.solid,design)?.0;for k in 0..count{if(selected[k]&&previous.solid[n+k]<=0.)||(!selected[k]&&gaps[k]<=0.){return Err(fail("streamed macro input tie/grazing"));}}for r in &base.phases.records{if selected!=r.result.active{return Err(fail("streamed macro branch transition requires localized derivative"));}}let force:Vec<_>=previous.lagged_force_n.iter().zip(external).map(|(a,b)|a+b).collect();let path=carrier_path(fields,&previous.solid,&base.phases,design)?;let identity=implexity_core::json::canonical_sha256(&serde_json::json!({"source_model_identity":source_model_identity,"contact_checkpoint":previous.branch.checkpoint(&previous.solid)?,"macro_dt_bits":format!("{:016x}",base.macro_dt_s.to_bits()),"fluid_dt_bits":format!("{:016x}",base.fluid_dt_s.to_bits()),"body_phases":base.body_phase_solves,"fluid_ticks":base.fluid_ticks}));let carrier=CarrierFluidStepper::new(&fields.fluid,base.fluid_ticks,first_tick,&path,design.len(),clock,&identity)?;let parameters=carrier.parameters(design,&path,previous.origin_s)?;let run=carrier.run(&previous.fluid,&parameters,checkpoint_policy)?;if run.final_state().len()!=base.state.fluid.len()||run.final_state().iter().zip(&base.state.fluid).any(|(a,b)|a.to_bits()!=b.to_bits()){return Err(fail("streamed macro carrier replay differs"));}Ok(StreamedMacroLinearization{carrier,carrier_parameters:parameters,carrier_run:run,base,owner:owner.clone(),force,policy,state_size:previous.solid.len(),design_size:design.len(),flux_size:previous.lagged_force_n.len()})
}
impl StreamedMacroLinearization<'_>{
 fn factor<L:ContactSetKinematics>(&self,i:usize,fields:&PersistentContactFields<'_,L>,design:&[f64])->CaeResult<SelectedContactLinearization>{let r=self.base.phases.records.get(i).ok_or_else(||fail("streamed macro phase index"))?;let owner=self.owner.for_phase(r.time_scale,r.begin_s)?;let next=ContactHistoryBranch::from_selected(&owner.advance_clock(fields.contact.nominal_step_s()*r.time_scale)?,&r.result.active,r.result.numerical_target)?;contact_set_selected_linearization(&fields.contact,&r.previous,&self.force,StepParameters{design,time_scale:r.time_scale},self.policy,&r.result,&owner,&next)}
 pub fn tangent<L:ContactSetKinematics>(&self,fields:&PersistentContactFields<'_,L>,previous:&MultiContactNativeState,design:&[f64],d:&MacroDirection)->CaeResult<MacroOutputBars>{if d.solid.len()!=self.state_size||d.fluid.len()!=previous.fluid.len()||d.lag.len()!=self.flux_size||d.external.len()!=self.flux_size||d.design.len()!=self.design_size||d.solid.iter().chain(&d.fluid).chain(&d.lag).chain(&d.external).chain(&d.design).any(|x|!x.is_finite())||!d.origin_s.is_finite(){return Err(fail("streamed macro finite direction"));}let force:Vec<_>=d.lag.iter().zip(&d.external).map(|(a,b)|a+b).collect();let mut state=d.solid.clone();let mut displacement=vec![physical_uv(fields,&state,design)?.0];for i in 0..self.base.phases.records.len(){let j=self.factor(i,fields,design)?;state=j.tangent(&SelectedContactDirection{previous:state,flux:force.clone(),design:d.design.clone(),time_scale:0.})?;displacement.push(physical_uv(fields,&state,design)?.0);}let path=CarrierPath{velocity:vec![vec![0.;self.flux_size];displacement.len()],displacement,duration_s:self.base.macro_dt_s};let dp=self.carrier.parameters(&d.design,&path,d.origin_s)?;let mut fluid=previous.fluid.clone();let mut df=d.fluid.clone();let mut samples=vec![0.;self.base.samples.len()];let mut impulse=vec![0.;self.flux_size];let p=StepParameters{design:&self.carrier_parameters,time_scale:1.};for n in 1..=self.carrier_run.steps(){let out=self.carrier.advance(n,&fluid,p)?;let q=self.carrier.tangent(n,&fluid,&out.state,p,&df,Some(&dp),0.)?;for(a,b)in samples.iter_mut().zip(&q.samples){*a+=b;}for k in 0..3{let off=samples.len()+k*self.flux_size;add(&mut impulse,&q.samples[off..off+self.flux_size])?;}fluid=out.state;df=q.state;}Ok(MacroOutputBars{solid:state,fluid:df,lag:impulse.into_iter().map(|x|x/self.base.macro_dt_s).collect(),samples,origin_s:d.origin_s})}
 pub fn adjoint<L:ContactSetKinematics>(&self,fields:&PersistentContactFields<'_,L>,design:&[f64],bar:&MacroOutputBars)->CaeResult<MacroBars>{let mut out=self.adjoint_many(fields,design,std::slice::from_ref(bar))?;Ok(out.remove(0))}
 pub fn adjoint_many<L:ContactSetKinematics>(&self,fields:&PersistentContactFields<'_,L>,design:&[f64],bars:&[MacroOutputBars])->CaeResult<Vec<MacroBars>>{let mut carriers=vec![];let mut states=vec![];let mut forces=vec![];let phases=self.base.phases.records.len();for bar in bars{if bar.solid.len()!=self.state_size||bar.fluid.len()!=fields.fluid.state_size()||bar.lag.len()!=self.flux_size||bar.samples.len()!=self.base.samples.len()||bar.solid.iter().chain(&bar.fluid).chain(&bar.lag).chain(&bar.samples).any(|x|!x.is_finite())||!bar.origin_s.is_finite(){return Err(fail("streamed macro complete bars"));}let impulse:Vec<_>=bar.lag.iter().map(|x|x/self.base.macro_dt_s).collect();let c=self.carrier.pullback(&self.carrier_run,&self.carrier_parameters,&bar.fluid,&bar.samples,&impulse)?;if c.displacement.len()!=phases+1{return Err(fail("streamed macro phase/carrier count"));}carriers.push(c);states.push(bar.solid.clone());forces.push(vec![0.;self.flux_size]);}for i in(0..phases).rev(){let factor=self.factor(i,fields,design)?;for k in 0..bars.len(){add(&mut states[k],&displacement_bar(fields,design,&carriers[k].displacement[i+1])?)?;let g=factor.adjoint(&states[k])?;states[k]=g.previous;add(&mut forces[k],&g.flux)?;add(&mut carriers[k].design,&g.design)?;}}let mut result=vec![];for(k,c)in carriers.into_iter().enumerate(){add(&mut states[k],&displacement_bar(fields,design,&c.displacement[0])?)?;let CarrierHistoryBars{fluid,design,origin_s,..}=c;result.push(MacroBars{solid:std::mem::take(&mut states[k]),fluid,lag:forces[k].clone(),external:std::mem::take(&mut forces[k]),design,origin_s:bars[k].origin_s+origin_s});}Ok(result)}
}
